feature/system/gnmi/metadata/feature.textproto, feature/system/gnmi/metadata/tests/annotation_test/annotation_test.go, feature/system/gnmi/metadata/tests/annotation_test/annotation_test.md
Co-authored-by: Sean Zhang <sezhang@google.com>
Signed-off-by: Sean Zhang <sezhang@google.com>
=> Initial commit of gNMI-1.8 test and test plan.

feature/bgp/policybase/ate_tests/route_installation_test/route_installation_test.go, feature/bgp/policybase/ate_tests/route_installation_test/route_installation_test.md
Co-authored-by: Arun Jude <aarunca@google.com>
Co-authored-by: Daniel Lepage <dplepage@google.com>
Co-authored-by: Hariram Natarajan <hariramnat@google.com>
=> Initial commit for RT-1.2 BGP Policy & Route Installation

CONTRIBUTING.md
Updated test folder and test file naming
=> Contribution guide directory and folder naming

feature/gnoi/tests/ping_test/ping_test.go, feature/gnoi/tests/ping_test/ping_test.md
Co-authored-by: Sean Zhang <sezhang@google.com>
=> Initial import of gNOI-5.1: Ping test.

feature/gnoi/tests/traceroute_test/traceroute_test.go, feature/gnoi/tests/traceroute_test/traceroute_test.md
Co-authored-by: Sean Zhang <sezhang@google.com>
=> Initial import of gNOI-5.2: Traceroute test.

feature/experimental/lacp_and_base_interface/singleton_interface/feature.textproto, internal/deviations/deviations.go
Move feature profile to cover L3 rather than L2 MTU.
PiperOrigin-RevId: 450695295
=> Change feature profile to cover L3 rather than L2 MTU

feature/gnmi/ate_tests/telemetry_interface_packet_counters_test/README.md, feature/gnmi/ate_tests/telemetry_interface_packet_counters_test/telemetry_interface_packet_counters_test.go
Co-authored-by: Sean Zhang <sezhang@google.com>
=> open source telemetry_interface_packet_counters_test.

feature/gribi/ate_tests/route_removal_via_flush_test/README.md, feature/gribi/ate_tests/route_removal_via_flush_test/route_removal_via_flush_test.go
Co-authored-by: Yu Shi <yuyushi@google.com>
=> Open source route removal via flush test.

feature/experimental/backup_nhg/ate_tests/backup_nhg_test/README.md, feature/experimental/backup_nhg/ate_tests/backup_nhg_test/backup_nhg_test.go
Co-authored-by: Brandon Stoll <bstoll@google.com>
=> open source backup_nhg_test.

feature/gribi/ate_tests/get_rpc_test/README.md, feature/gribi/ate_tests/get_rpc_test/get_rpc_test.go
=> Validate gRIBI Get RPC. Coauthored by  hariramnat@google.com and deepgajjar@google.com

feature/interface/aggregate/ate_tests/balancing_test/README.md, feature/interface/aggregate/ate_tests/balancing_test/balancing_test.go
Co-authored-by: Likai Liu <liulk@google.com>
=> open source balancing_test.

feature/gribi/ate_tests/ordering_ack_test/README.md, feature/gribi/ate_tests/ordering_ack_test/ordering_ack_test.go
Co-authored-by: Likai Liu <liulk@google.com>
=> Open source ordering ack test

feature/bgp/bgp_test.go, feature/bgp/gracefulrestart/gracefulrestart_test.go, feature/bgp/neighbor_test.go, feature/bgp/peergroup_test.go, feature/device/device_test.go, feature/lldp/lldp_test.go, feature/system/ntp/ntp.go, feature/system/ntp/ntp_test.go, feature/system/system.go, feature/system/system_test.go
Add System base and NTP config libraries.
=> Add System base and NTP config libraries

feature/experimental/isis/ate_tests/lsp_updates_test/README.md, feature/experimental/isis/ate_tests/lsp_updates_test/lsp_updates_test.go
Co-authored-by: Dan Lepage <dan-lepage@users.noreply.github.com>
=> RT-2.2 open sourcing

feature/interface/aggregate/ate_tests/aggregate_test/aggregate_test.go
Hi ,
I have added the changes for below github issues in this pull request: 
https://github.com/openconfig/featureprofiles/issues/239
https://github.com/openconfig/featureprofiles/issues/200
Thanks,
Avaneesh
=> RT-5.2 aggregate test : Adding type and clearing aggregate link

internal/deviations/deviations.go
Remove references to internal bug reports.
=> Update deviations.go - Remove references to internal bug reports.

feature/sflow/collector.go, feature/sflow/collector_test.go, feature/sflow/interface.go, feature/sflow/interface_test.go, feature/sflow/sflow.go, feature/sflow/sflow_test.go
=> Add SFLOW config library

feature/gribi/ate_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
=> Use deviation for default network instance

feature/interface/aggregate/aggregate.go, feature/interface/aggregate/aggregate_test.go, feature/interface/aggregate/feature.textproto, feature/interface/singleton/feature.textproto, feature/interface/singleton/interface.go, feature/interface/singleton/interface_test.go, feature/interface/singleton/subinterface.go, feature/interface/singleton/subinterface_test.go, feature/interface/staticarp/feature.textproto, feature/interface/staticarp/staticarp.go, feature/interface/staticarp/staticarp_test.go
Also fixed some missing config/telemetry paths in the textproto.
=> Created singleton and aggregte interface config library

feature/experimental/gribi/ate_tests/ack_in_presence_other_routes/route_ack_test.go
change ip string with ip+cidr for network definition
=> replace IP string by ateDstNetCIDR

topologies/kne/arista_ixia.textproto
New ixia-c version
[https://github.com/open-traffic-generator/ixia-c/releases/tag/v0.0.1-3002]
=> Admin PR - new ixia-c version 3002

.github/workflows/pull_request.yml, CONTRIBUTING.md, feature/bgp/addpath/ate_tests/route_propagation_test/route_propagation_test.go, feature/bgp/tests/local_bgp_test/local_bgp_test.go, feature/device/device_test.go, feature/experimental/backup_nhg/ate_tests/backup_nhg_test/backup_nhg_test.go, feature/experimental/isis/ate_tests/base_adjacencies_test/base_adjacencies_test.go, feature/experimental/isis/ate_tests/internal/session/session.go, feature/experimental/isis/ate_tests/lsp_updates_test/lsp_updates_test.go, feature/gribi/ate_tests/base_leader_election_test/base_leader_election_test.go, feature/gribi/ate_tests/get_rpc_test/get_rpc_test.go, feature/gribi/ate_tests/ordering_ack_test/ordering_ack_test.go, feature/gribi/ate_tests/route_removal_via_flush_test/route_removal_via_flush_test.go, feature/gribi/ate_tests/weighted_balancing_test/setup_test.go, feature/gribi/otg_tests/base_leader_election_test/base_leader_election_test.go, feature/gribi/tests/gribigo_compliance_test/gribigo_compliance_test.go, feature/networkinstance/networkinstance_test.go, internal/deviations/deviations.go, tools/validate_paths.go
=> Fix hard-coded "default" to *deviations.DefaultNetworkInstance

feature/gnmi/ate_tests/telemetry_interface_packet_counters_test/telemetry_interface_packet_counters_test.go
Fix fmt errors and CLA authentication
=> Fixing failed counter test for unsupported paths

feature/experimental/backup_nhg/ate_tests/backup_nhg_test/README.md
Update the test plan to focus on interested scenarios:
* Replace next-hop IP in the backup NHG with a routing instance.
=> Update README.md of backup_nhg_test

feature/interface/aggregate/ate_tests/balancing_test/balancing_test.go
7a08fe7d-2965-422e-9928-a689a923bb24
=> Fix balancing test

feature/gribi/ate_tests/leader_failover_test/README.md, feature/gribi/ate_tests/leader_failover_test/leader_failover_test.go, internal/gribi/gribi.go
8ba20945-8c41-410f-91a5-97f8a8134e51
=> Move leader_failover_test out of experimental

feature/bgp/gracefulrestart/ate_tests/bgp_graceful_restart_test/bgp_graceful_restart_test.go, feature/bgp/policybase/ate_tests/route_installation_test/route_installation_test.go
Changed Replace(t, nil) to Delete(t)
Fixes following issues.
https://github.com/openconfig/featureprofiles/issues/389
https://github.com/openconfig/featureprofiles/issues/388
=> changed Replace(t, nil) with Delete(t)

feature/bgp/addpath/otg_tests/route_propagation_test/README.md, feature/bgp/addpath/otg_tests/route_propagation_test/route_propagation_test.go, feature/gribi/otg_tests/ack_in_presence_other_routes/README.md, feature/gribi/otg_tests/ack_in_presence_other_routes/route_ack_test.go, feature/gribi/otg_tests/leader_failover_test/README.md, feature/gribi/otg_tests/leader_failover_test/leader_failover_test.go, topologies/kne/arista_ixia.textproto
- base ate tests copy to otg_tests folders
- new ixia-c version
=> Admin PR - copy of ate-tests RT-1.3, TE-3.6 and TE-4.2

feature/gribi/ate_tests/get_rpc_test/README.md
* Get() returns last ACKed status of RIB and FIB programming status.
=> Update Get() test expectation

feature/interface/singleton/ate_tests/singleton_test/README.md, feature/interface/singleton/ate_tests/singleton_test/singleton_test.go, internal/attrs/attrs.go, internal/deviations/deviations.go
=> Restore setting of L2 MTU and --deviation_omit_l2_mtu

feature/lldp/tests/core_lldp_tlv_population_test/core_lldp_tlv_population_test.go
Fixing as per comments from #380 #374 #303 
497fb450-43de-40e8-81d7-c027475620ca
a18ee9e0-5e02-487a-8ea4-ac19888a5c05
=> fix core_lldp_tlv_population_test

internal/attrs/attrs.go
=> attrs only set L2 MTU if an MTU is specified.

feature/experimental/p4rt/wbb.p4info.pb.txt
Opensourcing WBB P4 Info for vendor testing of P4RT
=> OpenSource P4Info file for P4RT testing

feature/gnmi/ate_tests/telemetry_port_speed_test/telemetry_port_speed_test.go
Update port speed test to clean up port configuration between test iterations.
New aggregate interfaces were being allocated for each test iteration but the IP address configuration remained on the old aggregate interface.  This would result in duplicate IP address assignments.
PiperOrigin-RevId: 469816796
=> Port speed test updates

feature/gribi/ate_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
e9998a03-b0d3-41bb-9763-a56212034668
=> Fix base_hierarchical_route_installation_test

feature/gribi/ate_tests/ipv4_entry_test/README.md, feature/gribi/ate_tests/ipv4_entry_test/ipv4_entry_test.go
=> Add TE-2.1: gRIBI IPv4 Entry test

feature/interface/singleton/ate_tests/singleton_test/singleton_test.go, feature/interface/singleton/otg_tests/singleton_test/singleton_test.go
#383 
Id: 5bf479c3-0dcf-4594-9629-0ce69dcf410a
=> RT-5.1 singleton unicast packet fix less-than check

feature/gribi/ate_tests/ack_in_presence_other_routes/route_ack_test.go
Fix for #324 
1d5e4b89-5bac-4d4d-8d9c-84b913ffdfe9
=> Update test such that static protocol is updated with identifier and name

feature/interface/aggregate/ate_tests/balancing_test/balancing_test.go
=> RT-5.3 sets interface types explicitly

feature/qos/ecn/feature.textproto
=> feature.textproto for qos/ecn

feature/experimental/qos/ate_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go
Validate that the qos output interface queue counters exist and are updated correctly with the traffic from different traffic classes
=>  Create experimental qos_output_queue_counters_test

feature/system/gnmi/cliorigin/mixed_oc_cli_origin_support_test/README.md, feature/system/gnmi/cliorigin/mixed_oc_cli_origin_support_test/mixed_oc_cli_origin_support_test.go
Co-authored-by: Hariram Natarajan hariramnat@google.com, Sean Zhang sezhang@google.com
=> OpenSource gNMI mixed_oc_cli_origin_support_test

feature/system/gnmi/cliorigin/ate_tests/cli_origin_test/cli_origin_test.go
Hi ,
I have added the changes for below github issues in this pull request:
https://github.com/openconfig/featureprofiles/issues/273
Thanks,
Avaneesh
=> Update CLI Origin Test to be vendor agnostic

feature/gnoi/system/feature.textproto
Add KillProcess RPC into GNOI feature profile
=> Add KillProcess RPC into GNOI feature profile

feature/platform/tests/optics_power_and_bias_current_test/optics_power_and_bias_current_test.go
Create helper function to get transceiver name for each vendor. Fixes optics_power_and_bias_current_test
Test successfully ran on hardware.
=> Create helper function to get transceiver name

feature/gribi/ate_tests/gribi_scaling/README.md, feature/gribi/ate_tests/gribi_scaling/gribi_scaling_test.go
Co-authored-by: Hariram Natarajan hariramnat@google.com
=> OpenSource gRIBI Scaling test

feature/interface/singleton/ate_tests/singleton_test/README.md, feature/interface/singleton/ate_tests/singleton_test/singleton_test.go, feature/interface/singleton/otg_tests/singleton_test/README.md, feature/interface/singleton/otg_tests/singleton_test/singleton_test.go, tools/check_ip_addresses.pl
Test Result Id: 6d925554-a3f5-44bc-9804-39eb9cae5ce5
=> Modify RT-5.1: singleton to verify negotiated-port-speed

feature/experimental/gribi/ate_tests/supervisor_failure/README.md, feature/experimental/gribi/ate_tests/supervisor_failure/Supervisor_Failure_test.go
=> Code commit for TE-8.2

feature/bgp/gracefulrestart/ate_tests/bgp_graceful_restart_test/bgp_graceful_restart_test.go
Hi,
I  have added peer group information to bgp v6 peer.
Please review and provide approval.
Thanks,
Prabha
=> added peergroup info

feature/gribi/ate_tests/weighted_balancing_test/README.md, feature/gribi/ate_tests/weighted_balancing_test/weighted_balancing_test.go, feature/gribi/otg_tests/weighted_balancing_test/README.md, feature/gribi/otg_tests/weighted_balancing_test/weighted_balancing_test.go
Update weight to more practical numbers.
=> Update target weight in TE-3.2

feature/gribi/ate_tests/hierarchical_weight_resolution_test/README.md, feature/gribi/ate_tests/hierarchical_weight_resolution_test/hierarchical_weight_resolution_test.go, internal/deviations/deviations.go
cf1fb7e7-b681-4ccf-bf17-bf052bc417aa
=> Open source hierarchical_weight_resolution_test

feature/lldp/tests/core_lldp_tlv_population_test/core_lldp_tlv_population_test.go
lldp changes for issue#460 ( https://github.com/openconfig/featureprofiles/issues/460 )
=> lldp changes for issue#460

internal/attrs/attrs.go
Adding AddToOTG function to internal/attrs/attrs.go
This is very useful for quick OTG configurations
=> AddToOTG function to attr package

feature/experimental/gribi/ate_tests/dut_daemon_failure/README.md, feature/experimental/gribi/ate_tests/dut_daemon_failure/dut_daemon_failure_test.go
Included in this commit:
* Test script (new): dut_daemon_failure_test.go
* Documentation (new): README.md
Resolves #162
=> Code commit for TE-8.1: DUT Daemon Failure

feature/gribi/otg_tests/gribigo_compliance_test/gribigo_compliance_test.go
This is an update to the test to use the attrs.AddToOTG helper merged in #605
Fixes #596
=> OTG Test Update - TE-15.1

feature/experimental/bgp/ate_tests/base_bgp_session_parameters/README.md, feature/experimental/bgp/ate_tests/base_bgp_session_parameters/base_bgp_session_parameters_test.go
Hi,
I have updated with TODO items in this test . 
please review and approve.
Thanks,
Prabha
=> RT1.1 base_bgp_session_parameters_test.go

feature/interface/aggregate/otg_tests/balancing_test/balancing_test.go
Removed operStatus check on the aggr
Corrected the otg device endpoints for the ipv6 traffic
Fixes #559
=> OTG Test Update - RT-5.3

feature/experimental/gnoi/copying_debug_files_test/README.md, feature/experimental/gnoi/copying_debug_files_test/copying_debug_files_test.go
test case to address https://github.com/openconfig/featureprofiles/issues/99. 
the test case needs to be made to work later.
=> gnoi 5.3 commit to experimental

feature/system/gnmi/cliorigin/ate_tests/mixed_oc_cli_origin_support_test/mixed_oc_cli_origin_support_test.go
=> gNMI-1.12: add juniper cli command

feature/system/ntp/tests/server_test.go, internal/deviations/deviations.go
Adding AssociationType as Server to NTP Server config
=> Adding AssociationType as Server to NTP Server config

feature/experimental/policy/policy_vrf_selection/otg_tests/base_vrf_selection/README.md, feature/experimental/policy/policy_vrf_selection/otg_tests/base_vrf_selection/base_vrf_selection_test.go, feature/experimental/policy/policy_vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/README.md, feature/experimental/policy/policy_vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
Copies of **_RT-3.1: Policy based VRF selection_** and **_RT-3.2: Multiple <Protocol, DSCP> Rules for VRF Selection_** into feature/experimental/policy/policy_vrf_selection/otg_tests folder
OTG conversions will follow in 2 separate PRs after this approval
=> ADMIN PR - ATE copies of RT-3.1 and RT-3.2

feature/gnmi/ate_tests/telemetry_port_speed_test/telemetry_port_speed_test.go
added lag type when deviation is required
=> added deviation lag type

feature/gribi/ate_tests/ack_in_presence_other_routes/route_ack_test.go
=> updated string to int

feature/experimental/qos/ate_tests/qos_policy_config_test/qos_policy_config_test.go
Created an experimental code to configure QoS Classifiers
=> Create an experimental qos_policy_config_test.go

feature/experimental/backup_nhg/ate_tests/backup_nhg_test/backup_nhg_test.go, feature/experimental/backup_nhg/otg_tests/backup_nhg_test/backup_nhg_test.go, feature/experimental/bgp/ate_tests/base_bgp_session_parameters/base_bgp_session_parameters_test.go, feature/experimental/gribi/ate_tests/dut_daemon_failure/dut_daemon_failure_test.go, feature/experimental/isis/ate_tests/base_adjacencies_test/base_adjacencies_test.go, feature/experimental/isis/ate_tests/internal/session/attrs.go, feature/experimental/isis/otg_tests/base_adjacencies_test/base_adjacencies_test.go, feature/experimental/isis/otg_tests/internal/session/attrs.go, feature/experimental/p4rt/ate_tests/google_discovery_protocol_packetin_test/google_discovery_protocol_packetin_test.go, feature/experimental/p4rt/ate_tests/google_discovery_protocol_packetout_test/google_discovery_protocol_packetout_test.go, feature/experimental/p4rt/ate_tests/traceroute_packetout_test/packetout_test.go, feature/experimental/p4rt/ate_tests/traceroute_packetout_test/traceroute_packetout_test.go, feature/experimental/platform/tests/optics_thresholds_test/optics_thresholds_test.go, feature/experimental/policy/policy_vrf_selection/ate_tests/base_vrf_selection/base_vrf_selection_test.go, feature/experimental/policy/policy_vrf_selection/ate_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go, feature/experimental/policy/policy_vrf_selection/otg_tests/base_vrf_selection/base_vrf_selection_test.go, feature/experimental/policy/policy_vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go, feature/experimental/qos/ate_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go, feature/experimental/security/aaa/kne_tests/tls_authentication_over_grpc_test/tls_authentication_over_grpc_test.go
Depends on https://github.com/openconfig/featureprofiles/pull/779
=> Migrate experimental to new lib

feature/experimental/isis/ate_tests/internal/session/session.go, feature/experimental/isis/otg_tests/internal/session/session.go
This is a one-line comment fix.
=> Fix comment on IS-IS session helper.

feature/lldp/tests/core_lldp_tlv_population_test/core_lldp_tlv_population_test.go, feature/platform/ate_tests/telemetry_inventory_test/telemetry_inventory_test.go, feature/platform/tests/optics_power_and_bias_current_test/optics_power_and_bias_current_test.go, feature/system/gnmi/cliorigin/ate_tests/cli_origin_test/cli_origin_test.go, feature/system/gnmi/cliorigin/ate_tests/mixed_oc_cli_origin_support_test/mixed_oc_cli_origin_support_test.go, feature/system/ntp/tests/server_test.go, feature/system/ntp/tests/system_ntp_test.go, feature/system/tests/banner_test.go, feature/system/tests/hostname_test.go, feature/system/tests/time_test.go
Depends on https://github.com/openconfig/featureprofiles/pull/779
=> Migrate everything else to new telemetry lib

feature/experimental/qos/otg_tests/qos_output_queue_counters_test/README.md, feature/experimental/qos/otg_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go
OTG conversion of DP-1.4: QoS Interface Output Queue Counters
Fixes #796 
Output log [here](https://drive.google.com/file/d/17ujGxbMEa3McwWTpzvsIvCsuHQNtD4uF/view?usp=share_link)
=> OTG Test - DP-1.4: QoS Interface Output Queue Counters

feature/experimental/isis/ate_tests/internal/session/session.go, feature/experimental/isis/otg_tests/internal/session/session.go
Proposal for [issue 702](https://github.com/openconfig/featureprofiles/issues/702)
=> added prot enabled

feature/experimental/qos/ate_tests/qos_policy_config_test/qos_policy_config_test.go
Added an experimental qos forwarding-groups config test
=> Update experimental qos_policy_config_test.go

go.mod, go.sum
This latest version includes a partial rollback that fixes:
https://github.com/openconfig/ondatra/issues/56
=> ADMIN PR: Upgrade to latest Ondatra for partial rollback

feature/experimental/p4rt/ate_tests/google_discovery_protocol_packetout_test/google_discovery_protocol_packetout_test.go, feature/gnoi/system/tests/ping_test/ping_test.go, feature/gribi/ate_tests/ack_in_presence_other_routes/route_ack_test.go, feature/gribi/ate_tests/base_leader_election_test/base_leader_election_test.go, feature/gribi/ate_tests/route_removal_via_flush_test/route_removal_via_flush_test.go, feature/gribi/otg_tests/ack_in_presence_other_routes/route_ack_test.go, feature/gribi/otg_tests/base_leader_election_test/base_leader_election_test.go, feature/gribi/otg_tests/route_removal_via_flush_test/route_removal_via_flush_test.go
Added NI Deviations for subset of tests. Added an additional constraint in  gNOI-5.1 Ping Test since the interface is expected to be in the mgmt NI in commit 0440fca10188c54b7a967cd1fea345d2651aed44
=> Ni deviation

feature/qos/ate_tests/qos_policy_config_test/README.md
Reformat README using mdformat tool to make the doc style consistent
=> Reformat README using mdformat tool to make the doc style consistent

feature/gnoi/system/tests/supervisor_switchover_test/supervisor_switchover_test.go, internal/args/args.go, internal/fptest/doc.go, topologies/binding/options.go
PiperOrigin-RevId: 494593179
making "Dual RP/SUP" to be required for the test to pass (Arista 7208 and Nokia will start failing it)
=> making "Dual RP/SUP" to be required for the test to pass

feature/bgp/feature.textproto, feature/networkinstance/feature.textproto
This was removed in openconfig/public#749
=> Remove network-instance enabled leaf.

feature/qos/ate_tests/bursty_traffic_test/README.md
Convert QoS test case to README file
=> Create README.md for DP-1.11: QoS Bursty traffic test

topologies/kne/juniper.config, topologies/kne/juniper_ixia.textproto
juniper_ixia.textproto - Removed reference to cptx image which isnt needed
juniper.config - Corrected the number of sub-ports
=> Changes to juniper_ixia.textproto and juniper.config files

feature/qos/ate_tests/one_sp_queue_traffic_test/README.md
Convert QoS test case to README
=> Create README.md for DP-1.7: One strict priority queue traffic test

feature/qos/ate_tests/two_sp_queue_traffic_test/README.md
Convert QoS test case to README file
=> Create README.md for DP-1.8: Two strict priority queue traffic test

feature/qos/ecn/ate_tests/ecn_enabled_traffic_test/README.md
Convert QoS test case to README
=> Create README.md for DP-1.12: ECN enabled traffic test

feature/qos/ate_tests/wrr_traffic_test/README.md
Convert QoS test case to README file
=> Create README.md for DP-1.9: WRR traffic test

feature/system/gnmi/metadata/tests/annotation_test/annotation_test.go
Currently our devices require metadata update to be accompanied by another update for an OC path (no single metadata update is allowed). This deviation allows setting metadata along with another update.
=> gnmi-1.8: add NoMetadataSingleUpdate deviation

feature/gnoi/system/tests/ping_test/ping_test.go
Creating this PR as request from @xw-g for further discussions
=> added deviations to gNOI-5.1

feature/experimental/gribi/ate_tests/dut_daemon_failure/dut_daemon_failure_test.go
added process name to gRIBIDaemons for Nokia
=> added nokia to gRIBIDaemons

feature/experimental/qos/ate_tests/mixed_sp_wrr_traffic_test/mixed_sp_wrr_traffic_test.go
Added QoS traffic from 2 input interfaces
Test case:
- https://github.com/openconfig/featureprofiles/blob/main/feature/qos/ate_tests/mixed_sp_wrr_traffic_test/README.md
=> Create an experimental mixed_sp_wrr_traffic_test.go - part 1

feature/gnoi/system/tests/traceroute_test/README.md, feature/gnoi/system/tests/traceroute_test/traceroute_test.go
ref: https://github.com/openconfig/featureprofiles/pull/687
=> change minTraceroutePktSize

feature/qos/ate_tests/mixed_sp_wrr_traffic_test/README.md
Added the README file back for easy reference
=> Create README.md for DP-1.10: Mixed strict priority and WRR traffic test

feature/experimental/qos/ate_tests/mixed_sp_wrr_traffic_test/mixed_sp_wrr_traffic_test.go
Added qos config and different traffic flows.
=> Update experimental QoS traffic test mixed_sp_wrr_traffic_test.go

feature/experimental/bgp/ate_tests/base_bgp_session_parameters/base_bgp_session_parameters_test.go
Updating script to configure BGP at `oc.NetworkInstance_Protocol` level instead of `oc.NetworkInstance_Protocol_Bgp`.
This enables missing configuration of `name` and `identifier` at `NetworkInstance_Protocol` level.
Also enabling AfiSafi configuration under Bgp.global.
=> RT-1.1: Enabling NetworkInstance_Protocol name and identifier configuration

feature/experimental/qos/ate_tests/mixed_sp_wrr_traffic_test/mixed_sp_wrr_traffic_test.go
Made cosmetic changes to make test cases more clear
=> Update experimental test code mixed_sp_wrr_traffic_test.go

feature/experimental/qos/ate_tests/qos_ecn_config_test/qos_ecn_config_test.go
Added the config verification test. The tSkipf() needs to be removed to enable the config verification test code.
=> Update experimental test code qos_ecn_config_test.go

feature/experimental/qos/ate_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go
=> Update experimental qos_output_queue_counters_test.go with QoS config instead of default one

feature/experimental/qos/ate_tests/mixed_sp_wrr_traffic_test/README.md, feature/experimental/qos/ate_tests/mixed_sp_wrr_traffic_test/mixed_sp_wrr_traffic_test.go
Updated the DSCP mapping based on the QoS test plan
=> Update experimental test code and README files with correct DSCP mapping based on the test plan

feature/gribi/otg_tests/gribi_scaling/gribi_scaling_test.go
PR #848, #600, #715, and #634 updated the ATE version of this test without updating the OTG version.
=> Update OTG gribi_scaling_test to match the ATE version of the test.

feature/experimental/p4rt/otg_tests/google_discovery_protocol_packetout_test/README.md, feature/experimental/p4rt/otg_tests/google_discovery_protocol_packetout_test/google_discovery_protocol_packetout_test.go
OTG Test: P4RT-3.2: Google Discovery Protocol: PacketOut [here](https://github.com/openconfig/featureprofiles/blob/main/feature/experimental/p4rt/ate_tests/google_discovery_protocol_packetout_test/google_discovery_protocol_packetout_test.go)
resolves #882
=> OTG Test: P4RT-3.2: Google Discovery Protocol: PacketOut

tools/list_tests.sh
Added `kne_tests` path for SEC-3.1
fixed RegEx to include P4RT tests
Removed obsolete dir structure
=> uplift list_tests

feature/bgp/prefixlimit/ate_tests/bgp_prefix_limit_test/bgp_prefix_limit_test.go
Modification :
BGP Restart timer to 90 and
and Traffic Duration to 90
=> BGP Retry modification

feature/experimental/qos/ate_tests/one_sp_queue_traffic_test/one_sp_queue_traffic_test.go
=> Update experimental test code one_sp_queue_traffic_test.go

feature/interface/singleton/otg_tests/singleton_test/singleton_test.go
- Update to match ATE test changes.
- Always PushConfig/StartProtocols before running traffic.
- FIx the computation of traffic loss.
=> Update OTG singleton_test with fixes + ATE updates

feature/experimental/policy/policy_vrf_selection/ate_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
Added instance type configuration for DEFAULT instance
=> Added instance type configuration for DEFAULT instance

feature/experimental/isis/ate_tests/internal/session/session.go, feature/experimental/isis/otg_tests/internal/session/session.go
=> Remove the recently new added config deleting operation

feature/experimental/qos/ate_tests/mixed_sp_wrr_traffic_test/mixed_sp_wrr_traffic_test.go, feature/experimental/qos/ate_tests/one_sp_queue_traffic_test/one_sp_queue_traffic_test.go, feature/experimental/qos/ate_tests/qos_policy_config_test/qos_policy_config_test.go, feature/experimental/qos/ate_tests/two_sp_queue_traffic_test/two_sp_queue_traffic_test.go
=> Fixed the typo

feature/experimental/qos/ate_tests/mixed_sp_wrr_traffic_test/mixed_sp_wrr_traffic_test.go, feature/experimental/qos/ate_tests/one_sp_queue_traffic_test/one_sp_queue_traffic_test.go, feature/experimental/qos/ate_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go, feature/experimental/qos/ate_tests/qos_policy_config_test/README.md, feature/experimental/qos/ate_tests/qos_policy_config_test/qos_policy_config_test.go, feature/experimental/qos/ate_tests/two_sp_queue_traffic_test/two_sp_queue_traffic_test.go
Rollback https://github.com/openconfig/featureprofiles/pull/1100 for sequence# change in scheduler policy
=> QoS: Rollback PR1100 for sequence# change in scheduler policy

feature/experimental/qos/ate_tests/wrr_traffic_test/wrr_traffic_test.go
Update experimental wrr_traffic_test.go with increased traffic runtime from 20 secs to 120 secs
=> Update experimental wrr_traffic_test.go with increased traffic runtime from 20 secs to 120 secs

feature/experimental/qos/ate_tests/wrr_traffic_test/wrr_traffic_test.go
Fixed the test description  typo in experimental wrr_traffic_test.go
=> Fixed the test description typos in experimental wrr_traffic_test.go

feature/experimental/qos/otg_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go
Changes made on the ATE test
Fixes #796
=> OTG Test Update - DP-1.4: QoS Interface Output Queue Counters

feature/experimental/qos/ate_tests/qos_ecn_config_test/qos_ecn_config_test.go, feature/experimental/qos/ate_tests/qos_policy_config_test/qos_policy_config_test.go
=> Enable EQoS CN weight config

feature/experimental/qos/ate_tests/mixed_sp_wrr_traffic_test/mixed_sp_wrr_traffic_test.go
QoS: Check TransmitOctets and DroppedOctets counters are updated in addition to TransmitPkts and DroppedPkts
- TransmitPkts
- TransmitOctets
- DroppedPkts
- DroppedOctets
=> Update experimental mixed_sp_wrr_traffic_test.go to check TransmitOctets and DroppedOctets counters

feature/experimental/qos/ate_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go
DP-1.4- Added scheduler binding to forwarding group and the required interface ref config
=> DP-1.4- Added scheduler binding to forwarding group and the required interface ref config 

tools/addrundata/list_csv.go, tools/addrundata/list_csv_test.go, tools/addrundata/list_json.go, tools/addrundata/list_testtracker.go, tools/addrundata/list_testtracker_test.go, tools/addrundata/main.go
Also renamed -list=json to -list=testtracker.
=> addrundata list simplified JSON rundata

internal/deviations/deviations.go
Update the description for deviation deviation_qos_dropped_octets
=> Updating the deviation_qos_dropped_octets deviation description

feature/gribi/ate_tests/hierarchical_weight_resolution_test/hierarchical_weight_resolution_test.go
Hi,
Increasing traffic flows to 2k from 1k. 
Thanks,
Prabha
=> TE3.3 hierarchical_weight_resolution_test.go 

go.mod, go.sum, topologies/binding/new.go
This includes a point upgrade to Ondatra for improved kne topology support
=> Soft deprecate the use of the kne-topo flag

feature/experimental/isis/otg_tests/base_adjacencies_test/base_adjacencies_test.go
- Replicate the changes to the corresponding ATE test made in https://github.com/openconfig/featureprofiles/pull/1085.
=> Stop validating the PSNP Processed and Received states

feature/experimental/policy/policy_vrf_selection/ate_tests/base_vrf_selection/base_vrf_selection_test.go, feature/experimental/policy/policy_vrf_selection/otg_tests/base_vrf_selection/base_vrf_selection_test.go
Add deviation logic for DeprecatedVlanID
=> Add deviation logic for DeprecatedVlanID

feature/qos/ate_tests/qos_ecn_config_test/qos_ecn_config_test.go
=> Cisco dp 1.3

feature/experimental/isis/otg_tests/base_adjacencies_test/base_adjacencies_test.go, feature/experimental/isis/otg_tests/internal/session/session.go
Replicating changes from https://github.com/openconfig/featureprofiles/pull/953
=> Update OTG base_adjacencies_test with changes from PR#953

feature/experimental/qos/ate_tests/wrr_traffic_test/wrr_traffic_test.go
This PR is for changing weights for cisco in accordance with https://github.com/openconfig/featureprofiles/pull/1242/
=> Update wrr_traffic_test.go 

feature/experimental/p4rt/ate_tests/traceroute_packetout_test/packetout_test.go, feature/experimental/p4rt/ate_tests/traceroute_packetout_test/traceroute_packetout_test.go
Reverts openconfig/featureprofiles#1399
=> Revert "Fix P4RT-5.2: Traceroute Packetout test"

feature/bgp/policybase/otg_tests/route_installation_test/route_installation_test.go
Copy changes from https://github.com/openconfig/featureprofiles/pull/871 to the OTG version of the test.
=> Missed deviations for BGP route install OTG test

feature/gribi/ate_tests/ipv4_entry_test/README.md, feature/gribi/ate_tests/ipv4_entry_test/ipv4_entry_test.go, feature/gribi/otg_tests/ipv4_entry_test/README.md, feature/gribi/otg_tests/ipv4_entry_test/ipv4_entry_test.go
For WBB Delete mode is not required so removing delete mode from tests
=> removed delete mode for ipv4_entry_test

feature/experimental/gribi/ate_tests/route_removal_during_failover_test/route_removal_during_failover_test.go
- Adding support for vendor Arista for the `coreFileCheck` functionality in this test and thereby fixing the test.
=> Add Arista support for coreFileCheck functionality in TE-13.2

feature/bgp/prefixlimit/ate_tests/bgp_prefix_limit_test/bgp_prefix_limit_test.go, feature/experimental/p4rt/tests/p4rt_election/p4rt_election_test.go
Instead thread the needed deviation value though to where it is used.
=> Avoid duplicative ondatra.DUT calls

feature/interface/aggregate/ate_tests/aggregate_test/aggregate_test.go, internal/deviations/deviations.go
This pull remove deviation InterfaceOperStatus.
=> Remove deviation InterfaceOperStatus

feature/gribi/ate_tests/base_hierarchical_route_installation_test/README.md, feature/gribi/ate_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go, feature/gribi/otg_tests/base_hierarchical_route_installation_test/README.md, feature/gribi/otg_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
This pull remove the cases that use gribi delete mode.
=> TE-3.1: remove test for gribi delete mode

feature/gribi/ate_tests/persistence_mode_test/README.md, feature/gribi/ate_tests/persistence_mode_test/persistence_mode_test.go, feature/gribi/otg_tests/persistence_mode_test/README.md, feature/gribi/otg_tests/persistence_mode_test/persistence_mode_test.go
This pr remove the cases that use gribi delete mode.
=> TE-4.2: remove grib delete mode from test

feature/gribi/ate_tests/ordering_ack_test/README.md, feature/gribi/ate_tests/ordering_ack_test/ordering_ack_test.go, feature/gribi/otg_tests/ordering_ack_test/README.md, feature/gribi/otg_tests/ordering_ack_test/ordering_ack_test.go
This pull remove the cases that use gribi delete mode.
=> TE-3.5: Remove gribi delete mode

feature/gribi/otg_tests/gribigo_compliance_test/gribigo_compliance_test.go
Reference: https://github.com/openconfig/featureprofiles/pull/1012
=> Replicate PR1012 in OTG GRIBI compliance test

feature/gnmi/ate_tests/telemetry_basic_check_test/README.md, feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go, feature/gnmi/otg_tests/telemetry_basic_check_test/README.md, feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go, internal/components/components.go, internal/deviations/deviations.go
This PR implements sw version check according to the updates specified in #1313 
---
<sup>
=> gNMI-1.10: update sw version check according to the new README

feature/experimental/isis/ate_tests/base_adjacencies_test/base_adjacencies_test.go, feature/experimental/isis/otg_tests/base_adjacencies_test/base_adjacencies_test.go, internal/deviations/deviations.go
Remove IS-IS hello padding Adaptive mode deviation for RT-2.1 IS-IS test
=> RT-2.1 | Remove IS-IS hello padding Adaptive mode deviation

feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go, feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go, internal/deviations/deviations.go
Remove deviation MissingCPUMfgName.
=> Remove deviation MissingCPUMfgName

feature/gnmi/ate_tests/telemetry_port_speed_test/telemetry_port_speed_test.go, feature/interface/aggregate/ate_tests/aggregate_forwarding_viable_test/aggregate_forwarding_viable_test.go, feature/interface/aggregate/ate_tests/aggregate_test/aggregate_test.go, feature/interface/aggregate/ate_tests/balancing_test/balancing_test.go, feature/interface/aggregate/otg_tests/aggregate_test/aggregate_test.go, feature/interface/aggregate/otg_tests/balancing_test/balancing_test.go, internal/deviations/deviations.go
PiperOrigin-RevId: 529219560
Move deviation AggregateAtomicUpdate to accessor
=> Move deviation AggregateAtomicUpdate to accessor

feature/experimental/gribi/ate_tests/route_addition_during_failover_test/route_addition_during_failover_test.go, feature/experimental/gribi/ate_tests/route_removal_during_failover_test/route_removal_during_failover_test.go, feature/experimental/gribi/otg_tests/route_addition_during_failover_test/route_addition_during_failover_test.go, feature/experimental/gribi/otg_tests/route_removal_during_failover_test/route_removal_during_failover_test.go, feature/experimental/policy/policy_vrf_selection/ate_tests/base_vrf_selection/base_vrf_selection_test.go, feature/experimental/policy/policy_vrf_selection/ate_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go, feature/experimental/policy/policy_vrf_selection/otg_tests/base_vrf_selection/base_vrf_selection_test.go, feature/experimental/policy/policy_vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go, feature/gribi/ate_tests/gribi_scaling/gribi_scaling_test.go, feature/gribi/ate_tests/hierarchical_weight_resolution_test/hierarchical_weight_resolution_test.go, feature/gribi/otg_tests/gribi_scaling/gribi_scaling_test.go, internal/deviations/deviations.go
PiperOrigin-RevId: 529270653
Move DeprecatedVlanID to accessor method
=> Move DeprecatedVlanID to accessor method

feature/gnoi/system/tests/chassis_reboot_status_and_cancel_test/chassis_reboot_status_and_cancel_test.go, internal/deviations/deviations.go
Move GNOIStatusWithEmptySubcomponent to accessor
=> Move GNOIStatusWithEmptySubcomponent to accessor

feature/bgp/tests/local_bgp_test/local_bgp_test.go, feature/experimental/bgp/ate_tests/base_bgp_session_parameters/base_bgp_session_parameters_test.go, internal/deviations/deviations.go
Move deviation ConnectRetry to accessor
=> Move deviation ConnectRetry to accessor

feature/bgp/policybase/ate_tests/route_installation_test/route_installation_test.go, feature/bgp/policybase/otg_tests/route_installation_test/route_installation_test.go, internal/deviations/deviations.go
Move MissingPrePolicyReceivedRoutes to accessor function
=> Move MissingPrePolicyReceivedRoutes to accessor

tools/addrundata/case.go, tools/addrundata/case_test.go, tools/addrundata/suite_test.go
=> Check that the testbed is specified in the metadata

feature/experimental/gribi/ate_tests/route_removal_during_failover_test/route_removal_during_failover_test.go, feature/experimental/gribi/otg_tests/route_removal_during_failover_test/route_removal_during_failover_test.go, feature/experimental/policy/policy_vrf_selection/ate_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go, feature/experimental/policy/policy_vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go, feature/gribi/ate_tests/gribi_scaling/gribi_scaling_test.go, feature/gribi/otg_tests/gribi_scaling/gribi_scaling_test.go, internal/deviations/deviations.go
PiperOrigin-RevId: 529584691
Move NoMixOfTaggedAndUntaggedSubinterfaces to accessor method
=> Move NoMixOfTaggedAndUntaggedSubinterfaces to accessor method

feature/experimental/isis/ate_tests/internal/session/session.go, feature/experimental/isis/otg_tests/internal/session/session.go, feature/experimental/system/gnmi/benchmarking/ate_tests/internal/setup/setup.go, internal/deviations/deviations.go
Move deviations ISISprotocolEnabledNotRequired and ISISInstanceEnabledNotRequired to accessor
=> Move deviations ISISprotocolEnabledNotRequired and ISISInstanceEnabledNotRequired to accessor

feature/experimental/gribi/ate_tests/route_addition_during_failover_test/route_addition_during_failover_test.go, feature/experimental/gribi/ate_tests/route_removal_during_failover_test/route_removal_during_failover_test.go, feature/experimental/gribi/otg_tests/route_addition_during_failover_test/route_addition_during_failover_test.go, feature/experimental/gribi/otg_tests/route_removal_during_failover_test/route_removal_during_failover_test.go, internal/deviations/deviations.go
Move GRIBIDelayedAckResponse to accessor method
=> Move GRIBIDelayedAckResponse to accessor method

feature/gribi/ate_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go, feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
Increased number of flows to achieve consistent load balancing by adding IPIP traffic and incrementing inner source and destination IP address. This is similar to the traffic flow used in TE-3.3(hierarchical_weight_resolution_test.go)
=> TE-3.7: Increasing number of flows to achieve consistent loadbalancing

cloudbuild/cloudbuild.yaml, cloudbuild/test.sh
Also change behavior of presubmit to now fail if any of the vendors fail the test (instead of reporting fail only for timeouts) now that all vendors are expected to pass
=> Fix juniper in presubmit

feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go, feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go, feature/qos/ate_tests/bursty_traffic_test/bursty_traffic_test.go, feature/qos/ate_tests/mixed_sp_wrr_traffic_test/mixed_sp_wrr_traffic_test.go, feature/qos/ate_tests/qos_basic_test/qos_basic_test.go, feature/qos/ate_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go, feature/qos/otg_tests/bursty_traffic_test/bursty_traffic_test.go, feature/qos/otg_tests/qos_basic_test/qos_basic_test.go, feature/qos/otg_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go, internal/deviations/deviations.go
PiperOrigin-RevId: 529570104
Move QOSDroppedOctets to accessor method
=> Move QOSDroppedOctets to accessor method

feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go, feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go, internal/deviations/deviations.go
This PR removes missing -deviation_missing_interface_hardware_port
=> gNMI-1.10: Remove missing hw port deviation

internal/rundata/rundata.go, internal/rundata/rundata_test.go
=> Rundata should use the metadata facility.

feature/bgp/tests/local_bgp_test/local_bgp_test.go, feature/experimental/bgp/ate_tests/base_bgp_session_parameters/base_bgp_session_parameters_test.go, internal/deviations/deviations.go
Move deviation NetworkInstanceTableDeletionRequired to accessor method
=> Move deviation NetworkInstanceTableDeletionRequired to accessor method

internal/pathutil/pathutil.go, internal/pathutil/pathutil_test.go
=> Add a utility for computing the root path to the featureprofiles repo.

feature/experimental/gribi/ate_tests/backup_nhg_action/backup_nhg_action_test.go, feature/experimental/gribi/otg_tests/backup_nhg_action/backup_nhg_action_test.go, feature/experimental/policy/policy_vrf_selection/ate_tests/base_vrf_selection/base_vrf_selection_test.go, feature/experimental/policy/policy_vrf_selection/otg_tests/base_vrf_selection/base_vrf_selection_test.go, feature/gribi/ate_tests/ack_in_presence_other_routes/route_ack_test.go, feature/gribi/ate_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go, feature/gribi/ate_tests/get_rpc_test/get_rpc_test.go, feature/gribi/otg_tests/ack_in_presence_other_routes/route_ack_test.go, feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go, feature/gribi/otg_tests/get_rpc_test/get_rpc_test.go, feature/system/gnmi/set/tests/gnmi_set_test/gnmi_set_test.go, internal/deviations/deviations.go
PiperOrigin-RevId: 529714724
Move StaticProtocolName to accessor method
=> Move StaticProtocolName to accessor method

feature/experimental/isis/ate_tests/internal/session/attrs.go, feature/experimental/isis/otg_tests/internal/session/attrs.go, feature/interface/singleton/ate_tests/singleton_test/singleton_test.go, feature/interface/singleton/otg_tests/singleton_test/singleton_test.go, internal/attrs/attrs.go, internal/deviations/deviations.go
PiperOrigin-RevId: 529787041
Move OmitL2MTU to accessor
=> Move OmitL2MTU to accessor

feature/experimental/p4rt/ate_tests/google_discovery_protocol_packetin_test/google_discovery_protocol_packetin_test.go, feature/experimental/p4rt/ate_tests/lldp_packetin_test/lldp_packetin_test.go, feature/experimental/p4rt/ate_tests/traceroute_packetin_test/packetin_test.go, feature/experimental/p4rt/ate_tests/traceroute_packetin_test/traceroute_packetin_test.go, feature/experimental/p4rt/ate_tests/traceroute_packetout_test/traceroute_packetout_test.go, feature/experimental/p4rt/otg_tests/google_discovery_protocol_packetin_test/google_discovery_protocol_packetin_test.go, feature/experimental/p4rt/otg_tests/lldp_packetin_test/lldp_packetin_test.go, feature/experimental/p4rt/otg_tests/traceroute_packetin_test/packetin_test.go, feature/experimental/p4rt/otg_tests/traceroute_packetin_test/traceroute_packetin_test.go, feature/experimental/p4rt/otg_tests/traceroute_packetout_test/traceroute_packetout_test.go
=> Filter only the valid packets in P4RT PacketIn Tests

feature/gnoi/os/tests/osinstall/osinstall_test.go
Add validation of system/state/software-version
=> Add validation of software version

feature/platform/tests/power_admin_down_up_test/README.md, feature/platform/tests/power_admin_down_up_test/metadata.textproto, feature/platform/tests/power_admin_down_up_test/power_admin_down_up_test.go
New test to check power-admin-state leaf
=> Fp test power down up

feature/experimental/backup_nhg/otg_tests/backup_nhg_test/README.md, feature/experimental/backup_nhg/otg_tests/backup_nhg_test/backup_nhg_test.go
References:
- https://github.com/openconfig/featureprofiles/pull/1316
- https://github.com/openconfig/featureprofiles/pull/1406
=> Replicate PR1316/PR1406 in OTG backup_nhg_test

feature/experimental/p4rt/tests/p4rt_election/p4rt_election_test.go, internal/deviations/deviations.go
* Use status Codes for logging instead of integers.
* Remove `p4rt_missing_delete` deviation.
=> cleanup p4rt election test and remove deviation

feature/experimental/p4rt/otg_tests/performance_test/README.md, feature/experimental/p4rt/otg_tests/performance_test/metadata.textproto, feature/experimental/p4rt/otg_tests/performance_test/performance_test.go
OTG conversion of P4RT-6:1
resolves #1700
=> OTG: P4RT-6.1: Required Packet I/O rate: Performance

topologies/kne/juniper/cptx/dutate.textproto, topologies/kne/juniper/cptx/dutate_lag.textproto, topologies/kne/juniper/cptx/dutdut.textproto
- Interface name updated to the correct names in the /kne/juniper/cptx folder
=> kne/juniper/cptx .textproto files update

internal/deviations/byexceptions.go, proto/metadata.proto, proto/metadata_go_proto/metadata.pb.go
- Add comments above flag declaration in byexceptions file.
- Refactor "Set to true" comments  comments in metadata.proto file.
=> Cleanup deviation comments

cloudbuild/virtual.sh, topologies/kne/nokia/srlinux/dut.textproto, topologies/kne/nokia/srlinux/dutate.textproto, topologies/kne/nokia/srlinux/dutate_lag.textproto, topologies/kne/nokia/srlinux/dutdut.textproto, topologies/kne/nokia/srlinux/topology.textproto
Changed interface key nomenclature, removed public image link for tagged srlinux:latest
=> Fixing KNE textproto for Nokia

feature/experimental/p4rt/ate_tests/performance_test/performance_test.go, feature/experimental/p4rt/otg_tests/performance_test/performance_test.go
increase the time wait to 60 seconds seeing much better chance for the test to pass.
=> read ATE counters and get packets taking much longer time sometime

feature/experimental/bgp/ate_tests/bgp_2byte_4byte_asn/metadata.textproto
Adding the deviations for the platform.
=> Update metadata.textproto for bgp_2byte_4byte_asn test

feature/experimental/bgp/ate_tests/bgp_long_lived_graceful_restart/bgp_long_lived_graceful_restart_test.go, feature/experimental/bgp/ate_tests/bgp_long_lived_graceful_restart/metadata.textproto
* Add routing process
* Add config to disable LLGR.
* Add deviations for Arista
=> bgp_llgr_arista_specific_fixes

feature/experimental/p4rt/otg_tests/performance_test/performance_test.go
change includes the fixes for
1. LLP and GDP packet counters , currently it is counted that falls only under switch case-2
2. removed unused variables and functions
=> P4RT6.1: porting PR#1702 changes to OTG

feature/platform/tests/optics_power_and_bias_current_test/optics_power_and_bias_current_test.go
/components/component[name=%s]/transceiver/thresholds/threshold[severity=%s]/state/laser-temperature-%s
/components/component[name=%s]/transceiver/thresholds/threshold[severity=%s]/state/output-power-%s
/components/component[name=%s]/transceiver/thresholds/threshold[severity=%s]/state/input-power-%s
=> New Transceiver leafs required

.github/workflows/required_otg_changes_check.js
Tested via both adding a new ATE file and modifying an ATE file in previous test commits.
=> Add checks for added/removed ATE test files

topologies/kne/juniper/cptx/topology.textproto
Corrected the port numbering for the topologies for cPTX
=> topology.textproto: Corrected the port numbering for the topologies for cPTX

.github/workflows/go.yml, feature/experimental/tunnel/otg_tests/tunnel_acl_based_test/README.md, feature/experimental/tunnel/otg_tests/tunnel_acl_based_test/tun_acl_dscp_test.go
#1972 was merged with some CI checks failing.
* Update IP addressing to match CONTRIBUTING.md
* Fix README.md header
* Add libpcap dependency to CI checks.
=> Update tun_acl_dscp_test to resolve CI errors

topologies/kne/juniper/cptx/config.cfg
Added the default base configs for cptx
=> Default base configs needed for cptx

feature/experimental/bgp/ate_tests/base_bgp_session_parameters/base_bgp_session_parameters_test.go
Logic was changed from get to await under PR https://github.com/openconfig/featureprofiles/commit/b7690688d6f4146835acaf7f80470049d034217c
Changed await call timeout value from 10seconds to 60seconds since it was too short
=> updated timeout value to 60seconds for the await call

.github/ISSUE_TEMPLATE/config.yml
This will require all issues to be created using one of the templates.  Currently there are two issue templates (bug for problems with an existing test and enhancement which is a request to add to a test or create a new test)  
This only applies to issues, not pull requests
=> Require issue template

feature/gribi/ate_tests/base_hierarchical_nhg_update/README.md, feature/gribi/ate_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go, feature/gribi/otg_tests/base_hierarchical_nhg_update/README.md, feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go, internal/args/args.go
TE3.7 Added Drain Implementation Test and modified existing Base Hierarchial NHG test.
Will modify the OTG part after review. Thanks.
=> TE3.7 Added Drain Implementation Test and modified existing test.

feature/platform/tests/telemetry_inventory_test/README.md
The test implements coverage for storage and temperature instant.
=> Fix some TODO items

feature/interface/aggregate/otg_tests/aggregate_forwarding_viable_test/aggregate_forwarding_viable_test.go
=> OTG RT5.4: Add FEC related config

.github/ISSUE_TEMPLATE/new_test_requirement.md, doc/test-requirements-template.md
Replaces #2067 which contained an unsigned commit
=> Add template for creating test requirement README files

feature/experimental/bgp/ate_tests/bgp_2byte_4byte_asn_policy_test/README.md, feature/experimental/bgp/ate_tests/bgp_2byte_4byte_asn_policy_test/metadata.textproto
Update TC number for RT-1.20 to RT-1.24
This commit resolves - #2120
=> Update RT-1.20 to RT-1.24

feature/gribi/mplsutil/compliance.go, feature/gribi/mplsutil/topo.go, feature/gribi/otg_tests/mpls_compliance/README.md, feature/gribi/otg_tests/mpls_compliance/gribi_mpls_compliance_test.go, feature/gribi/otg_tests/mpls_compliance/metadata.textproto
* (A) feature/gribi/mplsutil/...
- Add utilities for gRIBI MPLS compliance testing.
* (A) feature/gribi/otg_tests/mpls_compliance/...
- Add initial gRIBI MPLS compliance test.
=> Add gRIBI MPLS compliance test basics.

feature/qos/otg_tests/qos_basic_test/qos_basic_test.go
As part of PR-2026 ,part of config was removed by mistake and corrected it.
=> DP-1.14: Fixing error in forwarding group config

tools/allowed_file_types.sh
=> Allow PEM cert files

feature/platform/tests/telemetry_inventory_test/telemetry_inventory_test.go
firmware-version leaf is not required for all transceiver types. It is required for 400G transceivers.
=> Skip firmware-version telemetry check for non 400G transceivers

feature/experimental/backup_nhg/otg_tests/backup_nhg_test/README.md, feature/experimental/backup_nhg/otg_tests/backup_nhg_test/backup_nhg_test.go
* Configure Port-1 to be in Default VRF.
* Install baseline IPv4 route in DEFAULT vrf.
=> Changing backup_nhg_test plan to have Port1 in DEFAULT vrf

feature/experimental/isis/otg_tests/isis_change_lsp_lifetime_test/metadata.textproto
=> Update metadata.textproto for Arista

doc/test-requirements-template.md
This adds more structure to the subtest headings.
=> Change subtest format heading

feature/platform/fabric/otg_tests/fabric_redundancy_test/README.md, feature/platform/fabric/otg_tests/fabric_redundancy_test/metadata.textproto
=> Fix test-id in README and metadata

feature/platform/tests/optics_power_and_bias_current_test/README.md
Use canonical path name format
=> Use canonical path name format

feature/system/tests/system_base_test/README.md, feature/system/tests/system_base_test/g_protocol_test.go, feature/system/tests/system_base_test/metadata.textproto, topologies/kne/arista/ceos/config.cfg, topologies/kne/arista/ceos/dutate.textproto
This test will validate that all services are running on standard IANA ports.
=> Add g* protocol tests

topologies/kne/arista/ceos/dut.textproto, topologies/kne/arista/ceos/dutate.textproto, topologies/kne/arista/ceos/dutate_lag.textproto, topologies/kne/arista/ceos/dutdut.textproto, topologies/kne/arista/ceos/dutdutate.textproto, topologies/kne/arista/ceos/topology.textproto
Fixes issue introduced in #2264, now all topos for arista should work with the new config
=> Fix gnmi ports for arista due to new config

feature/mtu/largeippacket/otg_tests/large_ip_packet_transmission/README.md, feature/mtu/largeippacket/otg_tests/large_ip_packet_transmission/large_ip_packet_transmission_test.go, feature/mtu/largeippacket/otg_tests/large_ip_packet_transmission/metadata.textproto
* test description outlined four input/output ports, but this will run with one or more ports just fine for the bundle flavor
* if using a kne setup will need to make sure to have two lag groups configured! (obvious in hindsight but easy to forget :p) 
* tested on both kne/virtual and real hardware
* my first fp test so be gentle :D
=> feat: mtu-1.3: large ip packet transmission

feature/gnoi/packet_link_qualification/tests/packet_link_qualification_test/README.md, feature/gnoi/packet_link_qualification/tests/packet_link_qualification_test/packet_link_qualification_test.go
=> verify generator/reflector interface oper-state is TESTING

feature/experimental/bgp/otg_tests/bgp_afi_safi_defaults/bgp_afi_safi_defaults_test.go
Reverts openconfig/featureprofiles#2354
the PR does help some platform to passing in full, but seeing a side effect to another platform where the ipv4 bgp peers wouldn't come up in the peer_group and global level testing.
=> Revert "BGP Afi Safi defaults test fix"

feature/experimental/bgp/otg_tests/bgp_tcp_mss_path_mtu/bgp_tcp_mss_path_mtu_test.go, feature/experimental/bgp/otg_tests/bgp_tcp_mss_path_mtu/metadata.textproto
* Add relevant deviations for L2 MTU and ISIS config
=> RT-1.21: BGP TCP MSS and PMTUD: Fix test code for Arista

feature/system/gnmi/set/tests/gnmi_set_test/gnmi_set_test.go
There was a breaking change to the schemaless queries in ygnmi that caused it.
This is a short-term fix. The longterm fix is at
https://github.com/openconfig/featureprofiles/pull/2472 but there was a bug exposed that needed to be addressed first.
Tested manually that the SetRequest JSON now contains "config" leaves.
=> Fix for gnmi_set_test.

feature/experimental/p4rt/otg_tests/traceroute_packetout_test/traceroute_packetout_test.go
The following changes fixes the traceroute_packetout_test failure when run on a DUT where the ingress port and the egress port are part of different FAPs. In such a case, the P4Runtime device id needs to be configured for both the FAPs. But the test was only configuring the device id for the FAP corresponding to the egress interface.
=> Fix traceroute_packetout_test failure in EOS when run on a DUT with multiple Switch asics/FAPs

feature/sflow/otg_tests/sflow_base_test/sflow_base_test.go, feature/staticroute/otg_tests/basic_static_route_support_test/README.md, feature/staticroute/otg_tests/basic_static_route_support_test/basic_static_route_support_test.go, feature/staticroute/otg_tests/basic_static_route_support_test/metadata.textproto, internal/cfgplugins/staticroute.go, internal/otgutils/actions.go
=> RT-1.26 Basic Static Route Test - Implementation

feature/security/gnsi/authz/tests/authz/testdata/policy.json
resolves https://github.com/openconfig/featureprofiles/issues/2454
=> Fix authz policy

feature/gnoi/os/tests/osinstall/osinstall_test.go
moved deviation after subint configs
=> Vendor deviation fix for gnoi-4.1

feature/gnoi/system/tests/ping_test/ping_test.go, feature/interface/aggregate/otg_tests/aggregate_forwarding_viable_test/aggregate_forwarding_viable_test.go
* Increase Load balancing tolerance to 0.1 from 0.01
* Increase traffic duration to 1 minute
* Wait for up to a Minute to check the forwarding-viable state leaf.
* Add a Count of 10 to the Ping Request for IPv4 with L3
=> Small fixes

feature/gribi/otg_tests/ipv4_entry_test/ipv4_entry_test.go, feature/gribi/otg_tests/weighted_balancing_test/port_flap_rebalanced_test.go, feature/gribi/otg_tests/weighted_balancing_test/setup_test.go
This PR contains fix in the FP test cases for the link flap issue. Essence of the fix is, there should not be any "setConfig" or "pushConfig" API call after the link state set to down.
=> kne link flap fix

feature/experimental/isis/otg_tests/isis_drain_test/isis_drain_test.go
Updating config order to avoid very intermittent failure.
=> RT-2.12: Updating config order

feature/platform/transceiver/zr_tunable_parameters_test/README.md
Add operational mode to the ZR tunable parameters test.
=> Add operational mode to the ZR tunable parameters test.

feature/platform/transceiver/zr_supply_voltage_test/README.md
Adding a 400ZR test for ZR supply voltage.
=> Adding a 400ZR test for ZR supply voltage.

topologies/binding/binding.go, topologies/binding/binding_test.go
This will make the diff of https://github.com/openconfig/featureprofiles/pull/2666 smaller.
=> Cleanup and improved testing of reserved dimensions

tools/addrundata/case.go, tools/addrundata/case_test.go
Add a line to stop removing tags from metadata in the addrundata tool
=> fix addrundata

feature/system/gnmi/metadata/tests/large_set_consistency_test/large_set_consistency_test.go
- obtain getRequest timestamps
- compare with setRequest timestamps
- Increase debugability (show timestamps for each thread)
=> refactor concurrency analysis gNMI-1.14

.github/workflows/pull_request.yml
```
* (M) .github/workflows/pull_request.yml
- Split the IP address check into a separate workflow to
avoid it being a required check
```
=> Do not require `check_ip_addresses.pl` to pass.

topologies/kne/nokia/srlinux/config.cfg
=> Fix KNE ACL configs pushed

feature/experimental/isis/otg_tests/isis_drain_test/README.md, feature/experimental/isis/otg_tests/isis_drain_test/metadata.textproto, testregistry.textproto
RT-2.12 conflicts with feature/isis/static-route_isis_redistribution/README.md
=> Fix test case ID and add to testregistry

feature/bgp/policybase/otg_tests/link_bandwidth_test/README.md
=> README update to use ibgp and send-community

feature/system/management/README.md, feature/system/management/metadata.textproto, testregistry.textproto
https://github.com/openconfig/featureprofiles/issues/2762
=> MGT-1 Management HA test readme

topologies/kne/nokia/srlinux/config.cfg
=> Migrate kne configs to grpc_server

feature/platform/transceiver/tests/zr_cd_test/README.md, feature/platform/transceiver/tests/zr_cd_test/metadata.textproto, feature/platform/transceiver/tests/zr_cd_test/zr_cd_test.go
=> Add Chromatic Dispersion (CD) test

feature/bgp/policybase/otg_tests/link_bandwidth_test/README.md
No change is needed to the test code.  This update:
- Improves the description to match the content of the test
- Adds paths used in the policies to the coverage section of the README
=> Update description and add paths to coverage

feature/bgp/policybase/otg_tests/prefix_set_test/bgp_prefix_set_test.go, feature/bgp/policybase/otg_tests/prefix_set_test/metadata.textproto
Adding arista deviation and OTG fix
=> Adding arista deviation and OTG fix

feature/interface/holdtime/otg_tests/holdtime_test/holddown_timers_test.go, feature/interface/holdtime/otg_tests/holdtime_test/metadata.textproto
RT-5.5: Interface hold-time test cases
=> RT-5.5: Interface hold-time

feature/experimental/backup_nhg/otg_tests/backup_nhg_test/backup_nhg_test.go
There is a small race condition possible in the test validation of the AFT telemetry where get for the nexthop  group AFT state may miss the expected nexthop entry since the get is done prematurely. As a fix, add a gnmi.Watch for the expected state.
=> Fix for TE-11.1: Backup NHG test due to Next hop entry missing

.github/workflows/readme_oc_path_and_rpc.yml, tools/fpcli/README.md, tools/internal/mdocspec/ocspec.go, tools/validate_readme_spec/validate_readme_spec.go
Also [improved error message](https://github.com/openconfig/featureprofiles/actions/runs/8927456688/job/24520868172) for when coverage section is not found on README, and add README for fpcli tool.
Tested at https://github.com/openconfig/featureprofiles/pull/2949
=> Validate README for OC coverage if any directory content was changed.

feature/gribi/otg_tests/gribi_scaling/README.md, feature/gribi/otg_tests/gribi_scaling/gribi_scaling_test.go, feature/gribi/otg_tests/gribi_scaling/metadata.textproto, internal/args/args.go, internal/iputil/iputil.go, internal/iputil/iputil_test.go, internal/tescale/scale.go
default scale params
- V4TunnelCount = 20000
- V4TunnelNHGCount = 256
- V4TunnelNHGSplitCount = 2
- EgressNHGSplitCount  = 16
- V4ReEncapNHGCount = 256
=> Refactor TE-14.1 with updated scale params

feature/bgp/static_route_bgp_redistribution/otg_tests/static_route_bgp_redistribution_test/README.md, feature/bgp/static_route_bgp_redistribution/otg_tests/static_route_bgp_redistribution_test/metadata.textproto
Add Arista specific deviations
=> RT-1.27: Add Arista deviation

feature/bgp/policybase/otg_tests/comm_match_action_test/README.md, feature/bgp/policybase/otg_tests/comm_match_action_test/metadata.textproto
Add Arista specific deviation to metadata.textproto
=> RT-7.8: Add Arista deviation

feature/experimental/gribi/otg_tests/route_addition_during_failover_test/README.md, feature/experimental/gribi/otg_tests/route_addition_during_failover_test/route_addition_during_failover_test.go, feature/experimental/gribi/otg_tests/route_removal_during_failover_test/README.md, feature/experimental/gribi/otg_tests/route_removal_during_failover_test/route_removal_during_failover_test.go
Added gribi client stop post switchover prior to reconnect
=> Added gribi client stop post switchover prior to reconnect

feature/platform/transceiver/tests/zr_fec_uncorrectable_frames_test/README.md, feature/platform/transceiver/tests/zr_fec_uncorrectable_frames_test/metadata.textproto, feature/platform/transceiver/tests/zr_fec_uncorrectable_frames_test/zr_fec_uncorrectable_frames_test.go, feature/platform/transceiver/tests/zr_low_power_mode_test/README.md, feature/platform/transceiver/tests/zr_low_power_mode_test/metadata.textproto, feature/platform/transceiver/tests/zr_low_power_mode_test/zr_low_power_mode_test.go, feature/platform/transceiver/tests/zr_supply_voltage_test/README.md, feature/platform/transceiver/tests/zr_supply_voltage_test/metadata.textproto, feature/platform/transceiver/tests/zr_supply_voltage_test/zr_supply_voltage_test.go, internal/cfgplugins/interface.go
This PR:
* Updates ZR tests with th following:
*  Interface config
* Correct way to bring interface up and down
* Update README with the correct yaml blocks and parameters which are being tested.
=> update ZR tests

feature/experimental/interface/my_station_mac/otg_tests/my_station_mac_test/README.md, feature/experimental/interface/my_station_mac/otg_tests/my_station_mac_test/my_station_mac_test.go
Hi,
I have added WaitForArp after pushconfig otg function.
=> TE-1.2 : Added wait for arp util func

feature/bgp/admin_distance/README.md, testregistry.textproto
iBGP, eBGP Administartive Distance (AD, route preference) setting
=> Initial commit of RT-1.34

CONTRIBUTING.md
The experimental folder is over-used and contains many tests which in fact do pass one or more DUT's.  The previous practice encouraged use of the experimental folder by default, for example, if only a README was created, but without automation, it was unknown if the test could pass.
Instead the default should be to use the regular feature folder for new README documentation without test automation.  The experimental folder should only be used if the test automation is written and proven not to pass on any known DUT.  The intent is this is a small hint to people that the test automation is not proven to work and therefore suspect to changes.
The problem with this approach is we typically write a README before the automation is implemented.  Later when the automation is added, even if …
=> Revise use of experimental folder and update OTG references

feature/bgp/admin_distance/otg_tests/admin_distance_test/README.md, feature/bgp/admin_distance/otg_tests/admin_distance_test/admin_distance_test.go, feature/bgp/admin_distance/otg_tests/admin_distance_test/metadata.textproto, internal/isissession/isissession.go
This test verifies that BGP routes with different admin distances are preferred over routes with higher admin distances.
=> BGP Admin Distance test

feature/bgp/policybase/otg_tests/import_export_multi_test/import_export_multi_test.go
adding otg verification for:
* MED
* AS Path
adding export policy to ATE port1 as per README
=> adding otg verification

feature/bgp/policybase/otg_tests/import_export_multi_test/import_export_multi_test.go, feature/bgp/policybase/otg_tests/import_export_multi_test/metadata.textproto
adding local preference verification
=> adding local preference verification

feature/mtu/largeippacket/otg_tests/large_ip_packet_transmission/metadata.textproto
=> MTU-1.3: Large IP Packet Transmi… Added omit_l2_mtu: true deviation

internal/otgutils/arp.go
increased the arp waitfor timeout
=> increased the arp waitfor timeout

feature/experimental/gribi/otg_tests/backup_nhg_action_pbf/backup_nhg_action_pbf_test.go
TE11.3 - case 3: tunnel viability triggers decap.
TE11.3 - case 4: resolution failure on new tunnels triggers decap in the backup NHG.
=> Additonal test cases for backup NHG action

feature/gribi/otg_tests/encap_frr/encap_frr_test.go
waiting time for all the components to be up after reboot increased
=> waiting time for all the components to be up after reboot increased

feature/bgp/static_route_bgp_redistribution/otg_tests/static_route_bgp_redistribution_test/metadata.textproto, feature/bgp/static_route_bgp_redistribution/otg_tests/static_route_bgp_redistribution_test/static_route_bgp_redistribution_test.go
- skip_setting_disable_metric_propagation
- same_policy_attached_to_all_afis
=> Added deviations

feature/experimental/bgp/otg_tests/link_bandwidth_test/README.md
- removal of support value 0 (zero) of link-bandwidth
- use of TRANS_ASN as unifid ASN of LBw
- relaxed validation fo ASN in LBw ext-community
=> Update of Policy definition - remove LBw w/ zero  value and ASN changes 

.github/workflows/readme_oc_path_and_rpc.yml, feature/security/gnsi/certz/test_data/README.md
Also remove irrelevant coverage in one of the files that was added.
=> Fix exempt list for README validation

feature/experimental/bgp/otg_tests/bgp_2byte_4byte_asn/README.md, feature/experimental/bgp/otg_tests/bgp_2byte_4byte_asn/bgp_2byte_4byte_asn_test.go, feature/gnmi/otg_tests/telemetry_port_speed_test/telemetry_port_speed_test.go
=> FNT nightly failure: Nokia

feature/interface/ip/ipv6_slaac_link_local/otg_tests/ipv6_slaac_link_local_test/metadata.textproto
Adding interface_enabled deviation for JUNIPER
=> RT-5.10: IPv6 Link Local generated by SLAAC

feature/experimental/bgp/otg_tests/link_bandwidth_test/metadata.textproto
Add skip_bgp_send_community_type deviation
=> Add skip_bgp_send_community_type deviation

feature/bgp/policybase/otg_tests/import_export_multi_test/metadata.textproto
RT-7.11: Remove deviation skip_prefix_set_mode
=> RT-7.11: Remove deviation skip_prefix_set_mode

feature/bgp/policybase/otg_tests/comm_match_action_test/bgp_comm_match_action_test.go, feature/bgp/policybase/otg_tests/comm_match_action_test/metadata.textproto
=> RT-7.8: Add bgp_community_set_refs deviation for Nokia

feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
https://github.com/openconfig/featureprofiles/pull/3247
** if !deviations.ExplicitGRIBIUnderNetworkInstance(args.dut) in script executed the else block when explicit_gribi_under_network_instance in metadata.textproto was set to true
** I see in #3247 the else part is retained while ExplicitGRIBIUnderNetworkInstance is removed, hence reverting the changes
=> reverted the changes in #3247

feature/interface/aggregate/otg_tests/aggregate_all_not_viable_test/README.md, feature/interface/aggregate/otg_tests/aggregate_all_not_viable_test/aggregate_all_not_forwarding_viable_test.go, feature/interface/aggregate/otg_tests/aggregate_all_not_viable_test/metadata.textproto
Adding new subtest and Updating with GRIBI NHG with backup NHG
=> Updating with GRIBI backup NHG

feature/gribi/otg_tests/gribi_scaling/gribi_scaling_test.go
Breaking more than 10k gribi entries from single modify request into multiple modify request with 10k operation entries each.
=> Updating test gribi_scale_test

testregistry.textproto
```
* (M) testregistry.textproto
- Add missing attestz test IDs.
```
=> Add `attestz-[123]` to the testregistry.

testregistry.textproto
Cleanup to ensure consistency.
=> Ensure `readme` links to a URL that loads, not a path in `featureprofiles`.

feature/interface/ip/ipv6_link_local/otg_tests/ipv6_link_local_test/ipv6_link_local_test.go, internal/deviations/deviations.go
Fixing explicit masklen configuration in LN 201
=> fixing explicit masklen config

testregistry.textproto
Creating a new test for Static GUE encapsulation to IPv4 tunnel
=> Update testregistry.textproto with Static GUE encapsulation to IPv4 tunnel

feature/networkinstance/otg_tests/defaults_test/README.md
Closing stale https://github.com/openconfig/featureprofiles/pull/1151/files which refers to ATE and updating the readme
=> removing stale pr 1151 and updating readme

.github/CODEOWNERS
=> Add alokmtri-g as codeowner for select features

.github/CODEOWNERS
=> Add sudhinj as codeowner for aft and sampling

feature/gribi/otg_tests/gribi_route_test/gribi_route_test.go
Added mandatory instance-type config for default network-instance
=> RT-14.2: Added mandatory instance-type config for default network-instance

feature/gribi/otg_tests/mpls_in_udp_scale/README.md, testregistry.textproto
Note, this test depends on 
* https://github.com/openconfig/featureprofiles/pull/3363 
* https://github.com/openconfig/featureprofiles/pull/3383
=> TE-18.3 gRIBI and Scheduler mpls-in-udp scale test

feature/isis/otg_tests/isis_extensions_segment_routing_test/README.md, testregistry.textproto
This PR is to create a Readme for IS-IS Extensions for Segment Routing
=> Create Readme for RT-2.15

feature/gribi/otg_tests/mpls_in_udp/README.md
Will create a separate README file for TE-18.1.5
=> TE-18.1.5 needs to be in a separate README file

feature/bgp/multipath/otg_tests/bgp_multipath_ecmp_test/bgp_multipath_ecmp_test.go
BGP may take time to propagate the ECMP routes, add Await to wait for the stable state.
=> RT-1.51: Add Await when checking for ECMP next hop

feature/system/management/otg_tests/management_ha_test/management_ha_test.go
Hi,
Moving interface bringup code to make sure interface is up and traffic chooses right path.
=> MGT-1 : management_ha_test.go

feature/bgp/prefixlimit/otg_tests/bgp_prefix_limit_test/README.md, feature/bgp/tests/local_bgp_test/README.md, feature/bgp/timers/otg_tests/bgp_keepalive_and_holdtimer_configuration_test/README.md, feature/gribi/otg_tests/get_rpc_test/README.md, feature/gribi/otg_tests/get_rpc_test/get_rpc_test.go
Updated Readme files for RT-1.5, RT-1.7, RT-1.10 for RPL under BGP peer-group AFI/SAFI instead of neighbor AFI/SAFI
=> Update Readme per PR#1538 changes

feature/isis/otg_tests/static_route_isis_redistribution/static_route_isis_redistribution_test.go
- Removed deviation func configEnableTbNative, it is now defined & imported from fptest/tableconnection.go
- Removed unwanted state passed in function.
=> RT2.12: Minor infrastructure fix

feature/isis/otg_tests/isis_interface_level_passive_test/metadata.textproto
fix the isis_interface_level_passive by adding the deviation to the metadata.textproto
=> fix isis_interface_level_passive

feature/tunnel/otg_tests/tunnel_interface_based_ipv6_gre_encapsulation_test/metadata.textproto
TUN-1.4: Add Arista deviation default_network_instance
=> TUN-1.4: Add Arista deviation

feature/platform/transceiver/chromatic_dispersion/tests/zr_cd_test/zr_cd_test.go
I have added code to close the streams after each iteration
=> zr_cd_test:added code to close streams

feature/gribi/otg_tests/basic_encap_test/metadata.textproto, feature/gribi/otg_tests/gribi_route_test/metadata.textproto, feature/gribi/otg_tests/vrf_policy_driven_te/metadata.textproto
This doesn't seems like a good usage of deviation (bypass one of the focus of the test).
=> Remove deviation ttl_copy_unsupported

feature/isis/otg_tests/base_adjacencies_test/README.md, feature/isis/otg_tests/base_adjacencies_test/base_adjacencies_test.go, feature/isis/otg_tests/base_adjacencies_test/metadata.textproto
=> added ISIS p2p circuit type and hello timer sub tests

feature/bgp/policybase/otg_tests/chained_policies_test/metadata.textproto, feature/bgp/policybase/otg_tests/default_policies_test/metadata.textproto, feature/bgp/policybase/otg_tests/prefix_set_test/metadata.textproto
Removing some deviation that should be no longer needed
=> Remove deviations 1.5

feature/bgp/otg_tests/bgp_afi_safi_defaults/README.md, feature/bgp/otg_tests/bgp_afi_safi_defaults/bgp_afi_safi_defaults_test.go
1)README.md is modified as per the Google requirement
2)Added the neighbor AFI/SAFI under global.
Have validated the changes against all vendors and they are all working as intended with no failures due to these changes.
=> fixed README.md related to global AFI-SAFI level behavior and also added the neighbor AFI-SAFI under global

feature/gnoi/packet_link_qualification/tests/packet_link_qualification_test/metadata.textproto
Add deviation default_network_instance
=> gNOI-2.1: Add deviation default_network_instance

feature/interface/ip/ipv6_ND/otg_tests/suppress_ipv6_nd_ra_test/README.md, feature/interface/ip/ipv6_ND/otg_tests/suppress_ipv6_nd_ra_test/metadata.textproto, feature/interface/ip/ipv6_ND/otg_tests/suppress_ipv6_nd_ra_test/suppress_ipv6_nd_ra_test.go, testregistry.textproto
https://github.com/openconfig/featureprofiles/issues/3321
=> IPv6 ND RA Suppress test

cloudbuild/virtual.sh, proto/metadata.proto, topologies/atedut_5.binding, topologies/atedut_5.testbed
Add topology DUT <-> ATE with 5 links
=> Add TESTBED_DUT_ATE_5LINKS topology to the topology list

feature/interface/singleton/otg_tests/singleton_test/README.md, feature/interface/singleton/otg_tests/singleton_test/singleton_test.go
* Add code to test unnumbered interface config and state
=> Add code to test unnumbered interface config and state

feature/system/system_base_test/tests/hostname_test/metadata.textproto, feature/system/system_base_test/tests/system_banner_test/metadata.textproto, feature/system/system_base_test/tests/system_g_protocol_test/metadata.textproto, feature/system/system_base_test/tests/system_time_test/metadata.textproto
* Change testbed for system_base_test tests to TESTBED_DUT
=> Change testbed for system_base_test tests to TESTBED_DUT

feature/interface/aggregate/otg_tests/aggregate_test/README.md, feature/interface/aggregate/otg_tests/aggregate_test/aggregate_test.go
* Add OC path for /lacp/interfaces/interface/config/interval
=> Add OC path for /lacp/interfaces/interface/config/interval

feature/p4rt/tests/metadata_validation_test/metadata.textproto
Hi 
This pull request is to remove the deviation P4RTModifyTableEntryUnsupported.
Thanks
=> removing deviation P4RTModifyTableEntryUnsupported from P4RT-2.2

feature/platform/fabric/otg_tests/fabric_redundancy_test/metadata.textproto
=> gNMI-1.16: Add deviation omit_l2_mtu

testregistry.textproto
The hashing test readme is WIP
=> Update the testregistry with ip_gue hashing FNT.

feature/gnoi/os/tests/osinstall/osinstall_test.go
If the package size is not sent, the server may
begin receiving content without knowing if it
would actually have the available space to store
it on the system.
This change allows the server to gracefully return
an error if the requested image would be too large
=> osinstall: send PackageSize in TransferRequest

feature/qos/otg_tests/Ingress_ARP_policing/README.md
This is in liue of https://github.com/openconfig/featureprofiles/pull/3527/files
As requested in the comment of above readme , created another new README.
=> Create README.md for CPT-1.1: Interface based ARP policer

feature/gribi/otg_tests/backup_nhg_action/backup_nhg_action_test.go, feature/gribi/otg_tests/backup_nhg_action_pbf/backup_nhg_action_pbf_test.go, feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go, feature/gribi/otg_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go, feature/gribi/otg_tests/ipv4_entry_test/ipv4_entry_test.go, feature/gribi/otg_tests/ipv4_entry_with_aggregate_ports_test/ipv4_entry_with_aggregate_ports_test.go, feature/policy_forwarding/policy_vrf_selection/otg_tests/base_vrf_selection/base_vrf_selection_test.go, feature/policy_forwarding/policy_vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
* Replace use of deprecated function FetchConfig with GetConfig
=> Replace use of FetchConfig with GetConfig

feature/isis/otg_tests/base_adjacencies_test/base_adjacencies_test.go, feature/isis/otg_tests/base_adjacencies_test/metadata.textproto
- Enabling deviation isis_explicit_level_authentication_config
- Updating deadline/timeout values during checks for consistent results
=> RT:2.1: Enabling deviation isis_explicit_level_authentication_config

testregistry.textproto
Registering new test for Static Mac Address feature.
=> RT-9.3 Static MAC address - Registering test

feature/gnoi/system/tests/per_component_reboot_test/metadata.textproto, feature/gnoi/system/tests/per_component_reboot_test/per_component_reboot_test.go
* Add code to verify trapstats rate after line card reboot for Juniper devices
=> Add code to verify trapstats rate after line card reboot in Juniper

feature/interface/aggregate/otg_tests/balancing_test/README.md
- Fixing some wording issues and removing TODO's
- Adding canonical OC
=> Modifying the readme

feature/bgp/otg_tests/base_bgp_session_parameters/README.md, feature/bgp/otg_tests/base_bgp_session_parameters/base_bgp_session_parameters_test.go
This Test is to include BGP session check with Martian IP
=> To Include BGP session Adjacency with Martian IP

feature/interface/singleton/otg_tests/singleton_test/README.md, feature/interface/singleton/otg_tests/singleton_test/singleton_test.go
* Revert changes for unnumbered sub-interfaces
=> Revert changes for unnumbered sub-interfaces

feature/bgp/tests/local_bgp_test/local_bgp_test.go
Update package name for feature/bgp/tests/local_bgp_test/local_bgp_test.go
=> Update pkg name for feature/bgp/tests/local_bgp_test/local_bgp_test.go

feature/platform/transceiver/chromatic_dispersion/tests/zr_cd_test/zr_cd_test.go, feature/platform/transceiver/firmware_version/tests/zr_firmware_version_test/zr_firmware_version_test.go, feature/platform/transceiver/input_output_power/tests/zr_input_output_power_test/zr_input_output_power_test.go, feature/platform/transceiver/laser_bias_current/tests/zr_laser_bias_current_test/zr_laser_bias_current_test.go, feature/platform/transceiver/logical_channels/tests/zr_logical_channels_test/zr_logical_channels_test.go, feature/platform/transceiver/performance_metrics/tests/zr_pm_test/zr_pm_test.go, feature/platform/transceiver/tunable_parameters/tests/zr_tunable_parameters_test/zr_tunable_parameters_test.go
Updating the logic for the failing tests.
=> Zr transceiver update

feature/tunnel/otg_tests/mpls_over_udp_tunnel_hashing_test/README.md, testregistry.textproto
Adding new test for TUN-2.9 covering hashing on the 5-tuple for MPLSoUDP tunnel.
=> adding new test TUN-2.9 for hashing test

feature/bgp/static_route_bgp_redistribution/otg_tests/static_route_bgp_redistribution_test/metadata.textproto, feature/bgp/static_route_bgp_redistribution/otg_tests/static_route_bgp_redistribution_test/static_route_bgp_redistribution_test.go
This is a deviation for cisco, Arista and Nokia follow the standard. Fixing the test
=> Fix for Arista and remove unnecessary and invalid deviation from Nokia

feature/bgp/policybase/otg_tests/link_bandwidth_test/link_bandwidth_test.go
Add `extCommunitySetArista` and set the per vendor `extCommunitySet` when being used.
=> RT-7.5: Update link_bandwidth_test

feature/qos/otg_tests/egress_traffic_classification_and_rewrite_test/README.md, testregistry.textproto
* Update the Plan ID for DP-1.19: Egress traffic DSCP rewrite
=> Update the Plan ID for DP-1.19: Egress traffic DSCP rewrite

.github/workflows/readme_oc_path_and_rpc.yml, tools/non_test_readmes.txt
* Maintain a list of non-test READMEs and use it wherever applicable
=> Maintain a list of non-test READMEs and use it wherever applicable

feature/aft/aft_base/otg_tests/afts_prefix_counters/README.md
Adding canonical OC data in the AFT prefix counters readme
=> Adding canonical OC data in the AFT prefix counters readme

testregistry.textproto
README was moved in https://github.com/openconfig/featureprofiles/pull/4415
=> Update URL for RT-3.53 README in testregistry

feature/staticroute/otg_tests/v4_static_route_with_v6_nh/README.md, feature/staticroute/otg_tests/v4_static_route_with_v6_nh/metadata.textproto, testregistry.textproto
adding test cases for v4 static route w/ v6 next-hop
=> README RT-1.66: IPv4 Static Route with IPv6 Next-Hop

tools/addrundata/suite.go, tools/addrundata/suite_test.go
* Add check for package name for all go test files
=> Add check for package name for all go test files

feature/qos/otg_tests/egress_strict_priority_scheduler_test/README.md, feature/qos/otg_tests/egress_strict_priority_scheduler_test/egress_strict_priority_scheduler_test.go, feature/qos/otg_tests/egress_strict_priority_scheduler_test/metadata.textproto, internal/cfgplugins/dut_initialize.go, internal/cfgplugins/qos.go
Readme location: https://github.com/open-traffic-generator/featureprofiles/tree/main/feature/qos/otg_tests/egress_strict_priority_scheduler_test
Deviations identified for test DP-1.15 (same as for DP-1.5):
interface_output_queue_non_standard_name - issue id 409074483
mpls_exp_ingress_classifier_unsupported - issue id 417271869
=> QoS test OTG-DP-1.15

internal/rundata/dut.go
=> Use context based logging

feature/mpls/sr/otg_tests/isis_node_sid_forward/isis_node_sid_forward_test.go
Added the counters inpkts, outpkts for the below OC paths.
/network-instances/network-instance/mpls/signaling-protocols/segment-routing/interfaces/interface/sid-counters/sid-counter/state/in-pkts:
/network-instances/network-instance/mpls/signaling-protocols/segment-routing/interfaces/interface/sid-counters/sid-counter/state/out-pkts:
=> Added changes based on PR4298

internal/components/components.go
* Cache the components fetched from the device to improve test latency
=> Cache the components fetched from the device to improve test latency

topologies/binding/binding.go
Make the binding.go GetRequestMetadata to be dynamic and pick the username/password
=> changing the binding.go to pick the username/password sent using ctx

go.mod, go.sum
Updating ondatra version to v12.2
=> upgrade to ondatra v12.2

feature/ttl/otg_tests/ingress/ingress_handling_of_ttl_test.go, feature/ttl/otg_tests/ingress/metadata.textproto, internal/cfgplugins/dut_initialize.go, internal/cfgplugins/policyforwarding.go
Readme location: https://github.com/openconfig/featureprofiles/blob/main/feature/ttl/otg_tests/ingress/README.md
Deviations identified for test PF-1.8:
policy_forwarding_to_next_hop_oc_unsupported - issue id: 408116507
next_hop_encap_header_oc_unsupported - issue id: 425589983
=> Add test PF-1.8

feature/gnsi/acctz/tests/record_subscribe_partial/record_subscribe_partial_test.go
Just making minor change in the package name
=> minor change for recordsubscribepartial_test

feature/isis/otg_tests/isis_interface_level_passive_test/isis_interface_level_passive_test.go, feature/isis/otg_tests/isis_interface_level_passive_test/metadata.textproto
Added the deviation missing_isis_interface_afi_safi_enable to the code.
=> Rt 2.11-Add_deviation
