openconfig/featureprofiles

- README.md
- cloudbuild/arista.sh
- feature/system/ntp/tests/system_ntp_test.go
- feature/system/tests/system_base_test.go
```
* (M) README.md
- Update README contents to reflect changes required to CLI by
fptest.
* (M) feature/system.../*.go
- Replace ondatra.RunTests with fptest.RunTests.
```
> Update tests to use fptest vs. ondatra.RunTests.

- go.mod
- go.sum
- topologies/binding/binding.go
- topologies/binding/binding_test.go
This commit changes the ondatra version to the latest to enable cisco nodes.
> change ondatra version to the latest to enable cisco nodes

- topologies/kne/arista_ceos.config
This is a prereq for GRIBI/AFT testing
> Enable AFT and IP routing by default for EOS

- cloudbuild/arista.sh
- feature/system/gnmi/feature.textproto
- feature/system/gnmi/get/feature.textproto
- feature/system/gnmi/get/tests/get_test.go
- go.mod
- proto/feature.proto
```
Initial (basic) test for gNMI Get RPC.
* (M) proto/feature.proto
- Add support for specifying a method of the gNMI protocol that
coverage is being implemented for.
* (M) feature/system/gnmi/feature.textproto
- Add feature profile for basic gNMI.
* (M) feature/system/gnmi/get/...
- Add feature profile for gNMI Get.
- Add initial functional tests for gNMI Get against the root.
```
> Initial featureprofile for gNMI's `Get` RPC

- feature/bgp/feature.textproto
- feature/bgp/prefixlimit/feature.textproto
A [OpenConfig PR](https://github.com/openconfig/public/pull/532) moved
various bgp `prefix-limits/(conf|state)/restart-timers` to
`timers/(conf|state)/restart-time`
> Update bgp restart-timer to match current OpenConfig

- topologies/binding/binding.go
Tried to resolve issue https://github.com/openconfig/featureprofiles/issues/95
Just passed ixweb.WithLogin(username, password) function with proper value in ixweb.Connect()
> adding support to start IxNetwork with specific username and password

- feature/system/tests/hostname_test.go
Remove underscore from host-name test due to contention on the character being in host-name
> Remove underscore from host-name test

- .github/workflows/pull_request.yml
Github runners have [7GB](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) of RAM allocated to them.  Static check analysis appears to exceed this limit and crashes sometimes.  This is mostly due to the large generated code in Ondatra/ygot that this repo uses heavily.
Static checks on my dev machine report the following stats:
```
/usr/bin/time -v staticcheck ./...
...
Elapsed (wall clock) time (h:mm:ss or m:ss): 10:07.36
Maximum resident set size (kbytes): 5965512
...
```
Adjusting the GOGC setting, we can lower the memory usage at the cost of some additional CPU time:
```
GOGC=30 /usr/bin/time -v staticcheck ./...
...
Elapsed (wall clock) time (h:mm:ss or m:ss): 11:14.21
Maximum resident set size …
```
> Adjust staticcheck CI settings to lower memory use

- feature/system/gnmi/get/tests/get_test.go
Previously, we had decided that the gNMI `Get` RPC should return exactly one `update` per `Notification`, and this was validated by the functional test in `feature/system/gnmi/get/tests/get_test.go`. We concluded that it should likely be able to support N different updates per notification as long as they:
* have the same path
* can be unmarshalled together
This test is the updated `Get` test to reflect this.
Passes against KNE:
```
[17:53] robjs@robjs0:github.com/openconfig/featureprofiles   update-get ✔                                                                                                                  44m ⚑ ◒  ⍉
▶ go test -v feature/system/gnmi/get/tests/*.go -kne-config $PWD/topologies/kne/testbed.kne.yml -testbed $PWD/topologies/dut.testbed
running test...
*** Reserving …
```
> Update Get test to reflect updated decisions on spec.

- feature/gnoi/tests/complete_chassis_reboot/complete_chassis_reboot_test.go
The first `prevTime` and `latestTime` time could be collected in the same second causing this test to fail occasionally.  This improves the time handling a bit and guarantees some delay has passed.  Resolves #192.
> Chassis Reboot Test: Gather DUT datetime after sleep

- feature/system/tests/osinstall/README.md
- feature/system/tests/osinstall/osinstall_test.go
- feature/system/tests/osinstall/osinstall_test.md
- go.mod
This adds test coverage for GNOI OS.Install, OS.Activate, and OS.Verify RPCs.
> Add gNOI-4.1: Software Upgrade test

- feature/system/gnmi/cliorigin/ate_tests/cli_origin_test/cli_origin_test.go
```
* (M) feature/system/gnmi/cliorigin/ate_test/cli_origin_test.go
- Remove use of gNMI.Get as means to have arbitrary CLI commands run. gNMI
Get should not be used in this manner, but rather gNOI commands that have
the equivalent functionality should be used.
```
This behaviour isn't specified anywhere in the gNMI specification, and I don't believe it is intended to be. If we think that this kind of functionality should be available, we need to primarily update the specifications before adding tests.
> Remove 'show' command parsing via gNMI Get.

- feature/gribi/ate_tests/weighted_balancing_test/port_flap_rebalanced_test.go
> Migrate uses of ate.Operations().SetInterfaceState to ate.Actions().SetPortState

- feature/gribi/ate_tests/base_leader_election_test/base_leader_election_test.go
- internal/deviations/deviations.go
Hello, Currently deviations are enabled by default that causes issue for vendors whose implementation does not deviate from the OC. Ideally, the deviations should be disabled by default. This pull adds a simple function `ConfigVendorDeviations` that can be called at the beginning of the each test to enable/disable the deviations based on the device vendor.
> deviations' config

- feature/isis/feature.textproto
- feature/isis/interface.go
- feature/isis/interface_test.go
- feature/isis/interfacelevel.go
- feature/isis/interfacelevel_test.go
- feature/isis/isis.go
- feature/isis/isis_test.go
- feature/isis/level.go
- feature/isis/level_test.go
Also fixed couple of errors and dependencies in the feature textproto. The config lib is for the entirety of ISIS base feature profile and is broken down into multiple files per sub tree. See BGP base feature profile for a similar pattern.
> Add config lib to ISIS base feature profile

- cloudbuild/cloudbuild.yaml
Cloud Build tasks were failing with the following error:
`ERROR: (gcloud.compute.ssh) INVALID_ARGUMENT: Login profile size exceeds 32 KiB. Delete profile values to make additional space.`
This should prevent the profile from growing.
> Expire Cloud Build SSH keys after 1 day

- feature/sflow/feature.textproto
The OpenConfig model for sflow was updated in [openconfig/public#522](https://github.com/openconfig/public/pull/522).  This syncs the feature profile up with the latest model.
> Sflow feature profile update

- feature/interface/aggregate/ate_tests/balancing_test/balancing_test.go
The "Ratio" subtest fails consistently in the aggregate link load balancing test.  The test would display the reason for the failure already in log messages:
```
outPkts normalized got: [0 0 0 0.33202573136537744 0.33593268058457215 0.3320415880500504]
want: [0 0 0 0]
...
Packet distribution ratios -want,+got:
[]float64{
0,
0,
0,
- 	0,
+ 	0.33202573136537744,
+ 	0.33593268058457215,
+ 	0.3320415880500504,
}
```
These lists get compared and are expected to be similar to eachother.  With this PR, the test returns the following output:
```
outPkts normalized got: [0.3359486895501926 0.3320247218493458 0.33202658860046164]
want: [0.3333333333333333 0.3333333333333333 0.3333333333333333]
```
Against a DUT, the test now passes.  This test was run in a testbed with a total of 4 ports (although …
> Fix Aggregate Load Balancing weight ratio test

- feature/gribi/ate_tests/base_leader_election_test/base_leader_election_test.go
- internal/gribi/gribi.go
Internal invocation ID: 77c4d72a-5a6e-4492-85cc-658e1fca8957
> TE-4.1 use unique nhIndex/nhgIndex to avoid implicit replace

- feature/system/ntp/tests/server_test.go
- feature/system/ntp/tests/system_ntp_test.go
String matching IP addresses may not be sufficient for comparison because there are many valid ways to express an IPv6 address.  This should address #284.
> Validate only RFC5952 formatted IPv6 NTP server addresses

- feature/bgp/policybase/otg_tests/route_installation_test/README.md
- feature/bgp/policybase/otg_tests/route_installation_test/route_installation_test.go
- feature/gribi/otg_tests/base_leader_election_test/README.md
- feature/gribi/otg_tests/base_leader_election_test/base_leader_election_test.go
- feature/interface/staticarp/otg_tests/static_arp_test/README.md
- feature/interface/staticarp/otg_tests/static_arp_test/static_arp_test.go
This is a file copy to serve as a baseline.  No change.
> Forking RT-1.2, TE-1.1 and TE-4.1 ATE tests to OTG for baseline

- feature/gnoi/os/tests/osinstall/osinstall_test.go
A second transferOS may not be possible if the first transfer's streams do not get closed.
> Ensure transfer streams get closed on completion

- feature/gnoi/os/tests/osinstall/osinstall_test.go
On dual supervisor DUT, `tc.dualSup` represents if the DUT has dual supervisors while `standby` represents the supervisor we are currently operating on.  watchStatus needs to know the current supervisor to determine what kind of messages are expected.
This always worked on single supervisor systems since both would be false.
The logs would show the following on dual supervisor systems:
```
osinstall_test.go:140: DUT is detected as dual supervisor.
osinstall_test.go:235: Transfer receive error: unexpected TransferProgress: got &{bytes_received:5046272}, want SyncProgress
```
> Pass current supervisor to watchStatus instead of supervisor capability

- feature/gnmi/ate_tests/telemetry_interface_packet_counters_test/telemetry_interface_packet_counters_test.go
- internal/deviations/deviations.go
This change add deviation functionality for ipv4/ipv6 discard packet counters. By default it checks for discard counters and the test will fail if paths are not supported.
To pass the test, add deviation (deviation_subinterface_counter_supported) - that will skip the discard counter lookup
> Sub Interface packet counter deviation

- feature/gnoi/system/tests/per_component_reboot_test/per_component_reboot_test.go
- Added func findComponentsByType()
Test passed:
- http://sponge2/1e6c1475-0172-4885-81f4-79c1af9f4a72
> Get component list by type instead of matching the component name

- feature/gribi/ate_tests/ordering_ack_test/README.md
* In the case of FIB ACK, RIB ACK is optional. gRIBI does allow a device to only return FIB ACK (skip RIB_ACK) after a success FIB programming. This is also aligned with current implementation that checks either FIB ACK or RIB ACK (with flag), but not both.  
* Remove case#2:
* If case#2 means IPv4Entry -> NHG -> NH, then it's already covered by case#4.
* If case#2 means hierarchical resolution, then it's covered by TE-3.1
* case#2 is not implemented anyway.
> Update TE-3.5 README

- feature/gnoi/os/tests/osinstall/osinstall_test.go
Don't attempt to send data during standby transfer. The data should be synced from primary to standby.
This bug would only be seen if DUT has dual supervisors and does not have the image cached.
PiperOrigin-RevId: 468572156
> OS Install don't send standby supervisor data

- feature/bgp/tests/local_bgp_test/local_bgp_test.go
This is to address #275.  This test is not evaluating the details of hold time behavior, but rather just setting BGP session parameters and ensuring sessions come up.
> BGP keepalive timer should be 1/3 of hold timer

- go.mod
- go.sum
ixia-c OTG doesn't work with gosnappi 0.9.3 and must be downgraded to 0.8.8
@openconfig/featureprofiles-go-reviewers please approve.
> ADMIN PR - Downgrading the gosnappi version on go.mod

- .github/workflows/wiki.yml
- go.mod
- go.sum
- tools/wikidoc/sidebar.tmpl
- tools/wikidoc/wikidoc.go
It is currently difficult to see all test plans in a single location.  This PR creates a Github action triggered on every commit that will update the Github Wiki with all the test plans.
An example of the output can be seen on my fork at https://github.com/bstoll/featureprofiles/wiki
> Add tool to generate wiki docs

- feature/qos/feature.textproto
Added missing qos config and telemetry paths
- Reference:  https://ops.openconfig.net/branches/models/master/openconfig-qos.html#
> feature.textproto for qos add dscp

- feature/gnoi/system/tests/complete_chassis_reboot/complete_chassis_reboot_test.go
Hi, the gnoi reboot tests use the dut.RawAPIs().GNOI().Default(t). This call use the cached connection. However, since rebooting device closes the GNOI, so the cached connection will not be usable by the next testcase.
> complete_chassis_reboot_test: fix gnoi connection issue

- internal/components/components.go
- internal/components/components_test.go
Create package to remove dependency on static mapping to get hardware component type.
This PR fetches all the hardware components based on hardware type defined in enum.go 
After fetching hardware list - validate the properties associated with each component
Run- 13cd3a36-09a9-43b0-a618-786a5ec95b8f
> Helper function to get telemetry components list

- internal/deviations/deviations.go
Per deviation guideline, the default value of a deviation should be false.
> Set --deviation_gribi_preserve_only default to false

- feature/gribi/ate_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
I missed the comment in #506 - add a license header to the Base Hierarchical NHG Update test.
> Add Apache license header

- feature/experimental/qos/ate_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go
Hi, qos_output_queue_counters_test missed to guard ipv4/enabled *deviations.InterfaceEnabled  fix. This pull  fixes that.
> qos_output_queue_counters_test: add deviation quard to sen ipv4/enabled

- feature/bgp/gracefulrestart/ate_tests/bgp_graceful_restart_test/bgp_graceful_restart_test.go
- feature/bgp/policybase/ate_tests/route_installation_test/route_installation_test.go
- feature/bgp/policybase/otg_tests/route_installation_test/route_installation_test.go
- feature/experimental/bgp/ate_tests/base_bgp_session_parameters/base_bgp_session_parameters_test.go
The BGP feature profile router-id path is defined here:
https://github.com/openconfig/featureprofiles/blob/a46e6b1acf1623739d73f4befaf1e26fb20f02a1/feature/bgp/feature.textproto#L56
We should use `/network-instances/network-instance/protocols/protocol/bgp/global/router-id` rather than `/network-instances/network-instance/config/router-id` in tests.  This PR updates tests to utilize the protocol path for BGP router-id rather than the global knob.
Resolves #393.
> Use BGP router-id instead of global router-id

- .github/CODEOWNERS
featureprofiles-maintainers members will choose if a go-reviewer is required.
> Remove featureprofiles-go reviewers as required

- feature/gribi/ate_tests/route_removal_non_default_vrf_test/route_removal_non_default_vrf_test.go
Validate that Flush RPC in gRIBI removes routes in non-default VRF as expected.
TestRouteRemovalNonDefaultVRFFlush test flush with the following operations
1. Flush request from clientA (the primary client) non default VRF should succeed.
2. Flush request from clientB (not a primary client) non default VRF should fail.
3. Failover the primary role from clientA to clientB.
4. Flush from clientB non default VRF should succeed.
5. Flush from default VRF should not delete all the gRIBI objects like NH and NHG.
Resolves #409
> Add test TE-6.2 : Route Removal In Non Default VRF

- feature/gnmi/ate_tests/telemetry_interface_packet_counters_test/telemetry_interface_packet_counters_test.go
- internal/attrs/attrs.go
- internal/deviations/deviations.go
This pull adds a deviation for ipv4/enabled leaf. It is expected that ipv4 to be enabled by default for the devices with this deviation.
> Add ipv4/enabled deviation

- feature/experimental/gnoi/packet_link_qualification/tests/packet_link_qualification_test/packet_link_qualification_test.go
- The fake response can be removed if link qualification is supported by the DUT
> Create packet_link_qualification_test with fake response

- feature/interface/staticarp/otg_tests/static_arp_test/static_arp_test.go
Updated **_TE-1.1: Static ARP_** to include StartProtocols required when running OTG tests on hardware, along with some minor other changes
Fixes #536
> OTG Test - TE-1.1 Update

- .github/workflows/pull_request.yml
The `go vet` step has been failing on some CI builds lately:
https://github.com/openconfig/featureprofiles/actions/runs/3299940756/jobs/5443879777
https://github.com/openconfig/featureprofiles/actions/runs/3299299059/jobs/5442504748
https://github.com/openconfig/featureprofiles/actions/runs/3298815086/jobs/5441414755
I suspect this is a memory utilization problem.  From running on my local machine, I get these memory usages from `/usr/bin/time -v go vet ./...` after clearing the build cache.
```
go vet ./...:
Maximum resident set size (kbytes): 5930296
Maximum resident set size (kbytes): 6366100
```
```
go vet w/ GOGC=30:
Maximum resident set size (kbytes): 4576932
Maximum resident set size (kbytes): 4557508
```
We've already made this change to staticcheck, this is applying the same …
> Add GOGC to go vet

- feature/experimental/isis/ate_tests/base_adjacencies_test/README.md
- feature/experimental/isis/ate_tests/base_adjacencies_test/base_adjacencies_test.go
- feature/experimental/isis/ate_tests/lsp_updates_test/lsp_updates_test.go
- feature/isis/feature.textproto
- internal/deviations/deviations.go
The `init-fails`, `part-changes`, and `manual-address-drop-from-area` are not generally used and shouldn't be tested or required by the IS-IS feature spec (init-fails and manual-...-area were already removed from the spec, but not from the corresponding tests or test plans). This removes them entirely.
This also adds a nil deviation check in the LSP update check, since some vendors return nil instead of false when the value isn't set.
> Fix IS-IS tests

- feature/bgp/tests/local_bgp_test/local_bgp_test.go
RT-1.7 Local BGP Test is currently using Replace(t, nil) to delete configuration which is against GNMI specification.
This PR replaces Replace(t, nil) to Delete(t).
> RT-1.7 : replaced Replace(t, nil) to Delete(t)

- feature/gribi/ate_tests/hierarchical_weight_resolution_test/hierarchical_weight_resolution_test.go
- feature/gribi/ate_tests/ordering_ack_test/ordering_ack_test.go
- internal/deviations/deviations.go
* Filter NextHopGroup using the ProgrammedID.
* Only validate the weights of the NextHops contained in the NextHopGroup.
eb64add8-4a54-4bcb-9022-1ec75a7c9431
> Remove AFT not supported deviation

- feature/system/gnmi/cliorigin/ate_tests/mixed_oc_cli_origin_support_test/mixed_oc_cli_origin_support_test.go
Change string_val used in oc gnmi set to json_ietf_val
Closing #523 and Raising new since test moved to a new location in https://github.com/openconfig/featureprofiles/pull/520
> Change string_val used in oc gnmi set to json_ietf_val

- feature/interface/aggregate/otg_tests/aggregate_test/aggregate_test.go
- topologies/kne/arista_ceos.config
Removed otg minlinks unnecessary configuration 
Removed operStatus check on the aggr
Simplified setDutInterfaceWithState to include only the new state
Added line to dut vendor startup config
Fixes #558
> OTG Test Update - RT-5.2

- feature/gribi/ate_tests/get_rpc_test/get_rpc_test.go
Changes for below error hit during get_rpc_test.go script execution -
[InvalidArgument] failed to set .network-instance{.name=="DEFAULT"}.next-hop-groups.group{.name=="oc-static-198.51.100.192/26"}.nexthop{.index==0}.index - Invalid value "AUTO_0": Must be an integer in range 0..65535
> change GetOrCreateNextHop from 'AUTO_0' to '0'

- feature/experimental/policy/policy_vrf_selection/ate_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
- feature/gribi/ate_tests/gribi_scaling/gribi_scaling_test.go
- feature/gribi/ate_tests/hierarchical_weight_resolution_test/hierarchical_weight_resolution_test.go
- internal/deviations/deviations.go
Vendor support for vlan-id configuration can vary - some support vlan/config/vlan-id and others support the newer vlan/match/single-tagged/config/vlan-id leaf.  This deviation allows us to support both methods.
> Add deviation to support deprecated vlan-id config

- feature/experimental/bgp/ate_tests/base_bgp_session_parameters/base_bgp_session_parameters_test.go
Replace should not be used to remove configuration values - instead, delete should be used.  See https://github.com/openconfig/reference/blob/c243b35b36e366852f9476c87fb2efe6e9050dfe/rpc/gnmi/gnmi-specification.md?plain=1#L1070-L1073.
Resolves #515.
> Use delete instead of nil replace

- internal/check/check.go
- internal/check/check_test.go
Await should always check *a* value if one can be fetched, so this PR changes Await to call Check() first; if the result is invalid, then it subscribes to the path until the deadline expires. This way calling AwaitTimeout with a timeout too short for even one subscribed value to arrive will behave the same way as calling AwaitTimeout with a 0 or negative timeout.
> Ensure that Await always checks values at least once.

- feature/bgp/policybase/ate_tests/route_installation_test/route_installation_test.go
Hi,
Instance type config is required when DUT is assumed to have no network instance configured prior to running the test.
If instance type is not configured prior to script run, config failure will be seen as instance type is mandatory.
If DUT already have instance type configured, it also will be of type DEFAULT_INSTANCE.
Script also does replace with same type, hence replacing instance type is not a problem such DUT devices.
Ref PR #: https://github.com/openconfig/featureprofiles/pull/592
Thanks,
Prabha
> added network instance type to default

- feature/experimental/qos/ate_tests/qos_policy_config_test/qos_policy_config_test.go
Updated both IPv4 and IPv6 NC1 dscp set to []uint8{48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59}
> Update experimental qos_policy_config_test.go

- feature/gribi/ate_tests/gribi_scaling/gribi_scaling_test.go
The last update to the test missed to update the election id for modify requests. This simply fixes that.
Passing log:
```
********************************************
=== RUN   TestScaling
gribi_scaling_test.go:422: 
*** Fetching gRIBI client for SF-D...
gribi_scaling_test.go:308: Config for nonDefaultNI at /network-instances/network-instance[name=vrf1]:
{
"openconfig-network-instance:config": {
"enabled": true,
"enabled-address-families": [
"openconfig-types:IPV4",
"openconfig-types:IPV6"
],
"name": "vrf1",
"type": "openconfig-network-instance-types:L3VRF"
},
"openconfig-network-instance:name": "vrf1"
}
2022/12/06 13:33:09 Test output "TestScaling Config for nonDefaultNI at /network-instances/network-instance[name=vrf1]" is discarded without -outputs_dir.  Please specify -outputs_dir to …
```
> TE-14.1 Fix election id issue

- .github/workflows/rebase_check.yml
#728 introduced a build-breaking change (fixed by #840) but it was not caught by pull request checks because the go.mod in the PR is out of date. To mitigate problems due to stale checks, I'm adding a rebase check that requires PR to be rebased if go.mod and checks are out of date.
> github workflow add pull request rebase check

- feature/gnoi/system/tests/chassis_reboot_status_and_cancel_test/chassis_reboot_status_and_cancel_test.go
- internal/components/components.go
When a reboot test fails, it could leave a pending reboot active scheduled for 2 hours in the future.  For each reboot action, defer a CancelReboot to stop all future reboots.
Additionally, add a check to verify a controller card component exists when building the reboot status request.
> gNOI-3.4: Cancel reboot on test failure

- feature/gnmi/ate_tests/telemetry_port_speed_test/telemetry_port_speed_test.go
Increase timeout from 30 seconds to 60 for STREAM subscription with /interfaces/interface/aggregation/state/lag-speed
> gNMI-1.5: Increase timeout for STREAM subscription with LagSpeed

- feature/interface/staticarp/ate_tests/static_arp_test/static_arp_test.go
- feature/interface/staticarp/otg_tests/static_arp_test/static_arp_test.go
- internal/deviations/deviations.go
- internal/fptest/portspeed.go
This deviation is for device requiring port-speed reconfiguration, where interface configuration using Replace resets the port-speed to default.
This deviation intent to configure port-speed based on the `ondatra.DUTDevice.Port().Speed()` when deviation is set to true.
> Deviation to configure interface port-speed explicitly.

- feature/bgp/addpath/ate_tests/route_propagation_test/route_propagation_test.go
This partially addresses https://github.com/openconfig/ondatra/issues/59
> Fix route_propagation_test to use correct protocol id

- feature/gribi/ate_tests/gribigo_compliance_test/gribigo_compliance_test.go
- feature/gribi/otg_tests/gribigo_compliance_test/gribigo_compliance_test.go
Considering there is no static-route configured by the test, removing `GetOrCreateProtocol`  for `STATIC`. As without route configuration `static-routes` container is not configured.
> TE-15.1: Removing not-required Static-route protocol config

- feature/bgp/feature.textproto
- feature/gribi/ate_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
- feature/gribi/ate_tests/gribi_scaling/gribi_scaling_test.go
- feature/gribi/ate_tests/hierarchical_weight_resolution_test/hierarchical_weight_resolution_test.go
- feature/gribi/ate_tests/route_removal_non_default_vrf_test/route_removal_non_default_vrf_test.go
- feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
- feature/gribi/otg_tests/gribi_scaling/gribi_scaling_test.go
- feature/networkinstance/otg_tests/defaults_test/defaults_test.go
This change supports the discussion in
https://github.com/openconfig/public/pull/738 to remove the
`enabled-address-families` list from the OpenConfig model. This change includes
a feature profile test that validates that IPv4 and IPv6 forwarding works for a
specific network instance (the default) without the need for explicit
configuration.
```
commit 73f54344352d96c18088ef98b67caec71acf0686
Author: Rob Shakir <robjs@google.com>
Date:   Fri Dec 9 18:27:47 2022 -0800
Validate that IPv4 and IPv6 are enabled by default.
* (A) feature/networkinstance/otg_tests/defaults_test/*
- Add a test case that validates that by default a device supports
both IPv4 and IPv6 forwarding within a network instance without
specific additional configuration.
- This PR supports the removal of the …
```
> Remove `enabled-address-families` configuration and add testing to validate defaults.

- feature/gribi/ate_tests/ack_in_presence_other_routes/route_ack_test.go
- feature/gribi/otg_tests/ack_in_presence_other_routes/route_ack_test.go
None of the tests uses enabled leaf to configure static route except this one. This pull removes it. Alternatively, if any of the vendors require enable leaf for static route, I can  change this pull to add a deviation flag instead of removing it.
> TE-3.6: Remove enabled for static route

- feature/qos/ecn/ate_tests/dscp_ecn_encap_decap_test/README.md
Convert QoS test case to README
> Create README.md for DP-1.13: DSCP and ECN bits are copied over during IPinIP encap and decap

- feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
gNMI-1.10: Telemetry: Basic Check : Adding interface type configuration
github issue#https://github.com/openconfig/featureprofiles/issues/591
> gNMI-1.10: Telemetry: Basic Check : Adding interface type configuration

- feature/gnoi/system/tests/per_component_reboot_test/per_component_reboot_test.go
- feature/gnoi/system/tests/supervisor_switchover_test/supervisor_switchover_test.go
- internal/args/args.go
PiperOrigin-RevId: 496441459
Adding support of `arg_num_control_cards` and `arg_num_linecards` flags in *per_component_reboot_test* similarly to https://github.com/openconfig/featureprofiles/pull/914].
Also, replacing the existing `arg_num_supervisors` with `arg_num_control_cards`.
> Project import generated by Copybara.

- feature/experimental/p4rt/ate_tests/base_p4rt/base_p4rt_test.go
Since we are adding Priority while writing table entries, the test is failing because of the missing priority:1 in the expected entity. Added priority to the expected entity inside p4rtutils.ACLWbbIngressTableEntryGet function calls. 
```
Read table.Entity:  &{table_id:33554691 match:<field_id:3 ternary:<value:"`\007" mask:"\377\377" > > action:<action:<action_id:16777480 > > priority:1 }
Expected.Entity:  &{table_id:33554691 match:<field_id:3 ternary:<value:"`\007" mask:"\377\377" > > action:<action:<action_id:16777480 > > }
```
> P4RT-1.1 - added priority field to expected table entity

- feature/networkinstance/ate_tests/defaults_test/defaults_test.go
- feature/networkinstance/otg_tests/defaults_test/defaults_test.go
1. Update otg test to cover non-default vrf.
2. Add equivalent ate test.
> Enhance networkinstances defaults_test 

- feature/experimental/backup_nhg/ate_tests/backup_nhg_test/backup_nhg_test.go
- feature/experimental/backup_nhg/otg_tests/backup_nhg_test/backup_nhg_test.go
- feature/gribi/ate_tests/weighted_balancing_test/port_flap_rebalanced_test.go
- feature/gribi/otg_tests/weighted_balancing_test/port_flap_rebalanced_test.go
The upgrade to do automatic election id sync missed to upgrade this test.
> TE-3.2: fix migration to use election id handshake

- feature/gnoi/system/tests/per_component_reboot_test/per_component_reboot_test.go
- feature/gnoi/system/tests/supervisor_switchover_test/supervisor_switchover_test.go
- feature/gribi/ate_tests/supervisor_failure_test/supervisor_failure_test.go
- feature/system/gnmi/metadata/tests/annotation_test/annotation_test.go
This patch applies  GNOISubcomponentPath to the related tests that use gnoi system APIs. Motivation for GNOISubcomponentPath is discussed in the previous pull https://github.com/openconfig/featureprofiles/pull/717.
> Apply GNOISubcomponentPath deviation to the related tests

- feature/gribi/ate_tests/supervisor_failure_test/supervisor_failure_test.go
The test expects the switchover reason to be  SYSTEM_INITIATED, however the switchover is initiated by user and I do not think SYSTEM_INITIATED is the correct reason.  SYSTEM_INITIATED should be set as a reason when the switch over is performed automatically by the device, e.g., when the device switches over from active to standby due to the active rp crash.  Also, this is confirmed in openconfig doc (https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-platform.html#components-component-state-last-switchover-reason-trigger)
> TE-8.2: Fix the SwitchoverReason from  SYSTEM_INITIATED to USER_INITIATED

- feature/experimental/policy/policy_vrf_selection/ate_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
- feature/system/gnmi/metadata/tests/annotation_test/annotation_test.go
PiperOrigin-RevId: 499558489
Set network instance type while creating L3 VRF
> DSCP Rules for VRF Selection Test: Set network instance type to L3VRF

- feature/bgp/prefixlimit/otg_tests/bgp_prefix_limit_test/bgp_prefix_limit_test.go
Added BGP-PEER-GROUP to the script since BGP neighborship would not come up without peer group config
> Adding BGP-PEER-GROUP to RT1.5 bgp_prefix_limit_test.go

- feature/gnoi/system/tests/complete_chassis_reboot/complete_chassis_reboot_test.go
When a reboot test fails, it could leave a pending reboot active scheduled for 2 hours in the future. For each reboot action, defer a CancelReboot to stop all future reboots.
> gNOI-3.1: Cancel reboot on test failure

- feature/gribi/ate_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
Function [testRecursiveIPv4Entry](https://github.com/openconfig/featureprofiles/blob/5890cc99fb3eec7a4738a5bf264611ee9fb00daa/feature/gribi/ate_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go#L274) tries to verify that hierarchical gribi entries  198.51.100.0/24 (A) -> 203.0.113.1/32 (B) -> 192.0.2.6 (C) through AFT Telemetry. The nexthop for A (198.51.100.0/24) is 203.0.113.1 (B) without recursive resolution  and is C (192.0.2.6) with recursive resolution. 
The test first checks the nexthop for A and then for C. However, the check of the nexthop for A assumes that the device returns the recursively resolved nexthop via AFT.  This pull fixes this issue by checking if the returned nexthop is B when the check for the C fails.
Please note that …
> TE-3.1: Fix checking for nexthop

- feature/lldp/tests/core_lldp_tlv_population_test/core_lldp_tlv_population_test.go
Changed the return value if `!present`, when `!lldpEnabled`. Both `intf` and `present` shouldn't be defined here.
> LLDP disabled change

- .github/CODEOWNERS
Fix team name for featureprofiles-quattro-tl 
Add new owner/group which is configured to be autoassigned for reviews in **/otg-tests/** folders.
> Fix quattro-tl group name and add OTG owners

- .github/workflows/pull_request.yml
We are seeing issues where the GitHub action `arduino/setup-protoc@v1` fails due to an API rate limit:
```
Error: API rate limit exceeded for 172.177.246.179. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```
This change adds an API key to get around this.
Example:
https://github.com/openconfig/featureprofiles/actions/runs/3895957137/jobs/6651901328
https://github.com/openconfig/featureprofiles/actions/runs/3887341411/jobs/6633493259
> GitHub Action: protoc: Use token to avoid API rate limits

- feature/system/gnmi/get/tests/system_gnmi_get_test/system_gnmi_get_test.go
Adding Type as GetRequest_CONFIG in GetRequest
Get will return entire snapshot in the GetResponse message if type is not specified and it not supported  in some platforms due to efficiency reason.
> Adding Type as GetRequest_CONFIG in GetRequest

- feature/experimental/p4rt/internal/p4rtutils/p4rtutils.go
- go.mod
- go.sum
This PR changes explicitP4RTNodes to compute p4rt node names for CISCO devices based on the model number when -deviation_explicit_p4rt_node_component is set.
> P4RT node name mapping for Cisco 8xxx

- feature/bgp/policybase/ate_tests/route_installation_test/route_installation_test.go
- internal/deviations/deviations.go
1. Added global address families
2. Added route-policy configuration under neighbor (under deviation if route-policy is not supported under peer group)
3. Fixed verifyPortsUp to check status of ports used in the test.
4. added two deviations
> Uplift rt1.2 for route_policy under neighbor

- feature/gnoi/system/tests/copying_debug_files_test/copying_debug_files_test.go
There's an additional caveat that I've found with this test. It expects that the BGP process is running, certain vendors might only run certain processes when they're in use. Perhaps the purpose is to run this test after the BGP tests have ran in featureprofiles?
> add map for multiple vendor naming convention

- feature/experimental/p4rt/ate_tests/traceroute_packetout_test/README.md
- feature/experimental/p4rt/ate_tests/traceroute_packetout_test/packetout_test.go
- feature/experimental/p4rt/ate_tests/traceroute_packetout_test/traceroute_packetout_test.go
1. Removed following line from description as its not valid for traceroute packet-out scenario
Install P4RT table entries required for traceroute.
2. Changed submit_to_egress_pipeline to submit_to_ingress
3. Removed Ethernet Headers from packet as the packet is subjected to FIB lookup in submit_to_ingress scenario before sending out (the packet needs to be an L3 packet).
4. TTL/Hoplimit=0 packets should be dropped by the device.
> Fixes for P4RT-5.2

- feature/experimental/qos/ate_tests/mixed_sp_wrr_traffic_test/mixed_sp_wrr_traffic_test.go
Increased traffic run time to 120 seconds to have stable test result
> Update experimental mixed_sp_wrr_traffic_test.go with traffic run time 120 seconds

- feature/gribi/ate_tests/gribi_scaling/gribi_scaling_test.go
- internal/deviations/deviations.go
Changes:
For dutPort2 and atePort2, unit 0 subinterface is configured without vlan(vlan-id 0). Added deviation to configure vlan for all subinterfaces to avoid mix of tagged and untagged subinterfaces.
> Added deviation for adding vlan for all subinterfaces

- feature/experimental/p4rt/ate_tests/lldp_packetout_test/lldp_packetout_test.go
added deviations to p4rt7.2 
This code is a Contribution to the OpenConfig Feature Profiles project (“Work”) made under the Google Software Grant and Corporate Contributor License Agreement (“CLA”) and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia’s intellectual property are granted for any other purpose. This code is provided on an “as is” basis without any warranties of any kind.
> added NI/PortSpeed deviations

- feature/experimental/p4rt/otg_tests/lldp_packetin_test/lldp_packetin_test.go
Log:
[P4RT7.1.docx](https://github.com/openconfig/featureprofiles/files/10675082/P4RT7.1.docx)
> OTG: Making the test P4RT-7.1 align with ATE test

- go.mod
- go.sum
Update gribigo dependency to bring in the openconfig/gribigo#180 change.  This resolves an issue with [TE-15.1: gRIBI Compliance](https://github.com/openconfig/featureprofiles/blob/main/feature/gribi/otg_tests/gribigo_compliance_test/README.md) test failing.
> Update gribigo dependency for TE-15.1: gRIBI Compliance

- feature/interface/aggregate/ate_tests/aggregate_test/aggregate_test.go
- feature/interface/aggregate/ate_tests/balancing_test/balancing_test.go
"This code is a Contribution to the OpenConfig Feature Profiles project (“Work”) made under the Google Software Grant and Corporate Contributor License Agreement (“CLA”) and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia’s intellectual property are granted for any other purpose. This code is provided on an “as is” basis without any warranties of any kind."
> RT-5.2 and RT-5.3 udpated for NI/PortSpeed deviations

- feature/experimental/isis/ate_tests/base_adjacencies_test/base_adjacencies_test.go
Stop validating the PSNP Processed and Received states since the PSNP exchange is not always guaranteed
> ISIS Base Adjacencies Test: Don't validate PSNP states

- feature/experimental/policy/policy_vrf_selection/ate_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
- internal/deviations/deviations.go
Renamed deviation ExplicitInterfaceRefInPolicyForwarding to ExplicitInterfaceRefDefinition since it is applicable under different OC hierarchies as well
> Renamed deviation ExplicitInterfaceRefInPolicyForwarding to ExplicitInterfaceRefDefinition

- feature/interface/aggregate/otg_tests/aggregate_test/aggregate_test.go
Added interface type ethernetCsmacd in setDUTInterfaceWithState
> RT-5.2: Aggregate Interfaces - Adding interface type ethernetCsmacd

- feature/experimental/p4rt/internal/p4rtutils/p4rtutils.go
Hi @Ankur19,
I added a small change on top of #1106 - if a user provided explicit P4RT node names, they will be used instead of inferred names.
Otherwise we default to inferred.
This allows us to use linecards with different interface/asic layouts internally
> Tweak p4rt utils for nokia

- feature/gribi/ate_tests/route_removal_non_default_vrf_test/route_removal_non_default_vrf_test.go
The interface comes up after it is attached to network-instance, thus moving NI configuration before ATE protocol start. 
> TE-6.2: Moving ATE protocol start after DUT NI configuration 

- feature/gribi/ate_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
Moving `port1` interface creation before it is added to to `VRF-1`
> TE-3.7: Moving Interface creation before it is attached to VRF.

- internal/fptest/portspeed.go
This PR adds small (3-second) delay to fptest.SetPortSpeed() function that is used by ExplicitPortSpeed deviation.
This allows for a brief convergence window between an interface reconfiguration with a speed change (e.g. 400G->100G) and initiating traffic streams from ATE
> Update ExplicitPortSpeed deviation

- feature/gnmi/ate_tests/telemetry_interface_packet_counters_test/telemetry_interface_packet_counters_test.go
- feature/gnmi/otg_tests/telemetry_interface_packet_counters_test/telemetry_interface_packet_counters_test.go
Modifying script to add deviation block for `ExplicitPortSpeed` and `ExplicitInterfaceInDefaultVRF`.
> GNMI-1.11: Adding support for ExplicitPortSpeed & ExplicitInterfaceInDefaultVRF deviation

- feature/experimental/isis/otg_tests/internal/session/session.go
"The Connection specification for portName on Ethernet object instead of direct portName" is changed with reference commit id  https://github.com/open-traffic-generator/featureprofiles/commit/04f106f81b85b7060d3c2100e1b397419a97b49d
This PR helps to align with the above commit
resolves #589
> OTG RT2.1: Fix for Retrieving port name using Eth.Connection

- feature/platform/tests/optics_power_and_bias_current_test/optics_power_and_bias_current_test.go
Appending value for `ondatra.Nokia` into `transceiverMap` variable and updating `transceiverName` accordingly.
> GNMI-1.13: Updating vendor based transceiverMAP and transceiverName

- feature/platform/tests/optics_power_and_bias_current_test/optics_power_and_bias_current_test.go
PR contains
1. Modification of mini. power range as per standards and observed on physical platform
_Fiber optic sources may vary from -20dBm to +20dBm and receiver power may go as low as -40dBm._
2. Correction of "if check"
> Power range update as per standards

- feature/experimental/policy/policy_vrf_selection/ate_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
- feature/experimental/policy/policy_vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
This PR adds missing instances of InterfaceEnabled deviation:
1. ipv6 subif config in ATE version of the test
2. interface, ipv4 subif, ipv6 subif in the OTG version of the test
Reference - https://github.com/openconfig/featureprofiles/pull/1136
> RT-3.2: add missing instances of InterfaceEnabled deviation

- feature/experimental/bgp/ate_tests/base_bgp_session_parameters/base_bgp_session_parameters_test.go
- internal/deviations/deviations.go
* Add deviation to handle BGP MD5 config changes.  This is required for devices which do not immediately use a new BGP MD5 password with an ESTABLISHED BGP session.
* Add test support for existing MissingValueForDefaults deviation.
* When deleting BGP protocol configuration, remove the /network-instances/network-instance/tables/table and /network-instances/network-instance/protocols/protocol paths together.
> RT-1.1: Base BGP Session Parameters: Support additional deviations

- feature/gribi/ate_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
- feature/gribi/ate_tests/route_removal_non_default_vrf_test/route_removal_non_default_vrf_test.go
- feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
- feature/gribi/otg_tests/route_removal_non_default_vrf_test/route_removal_non_default_vrf_test.go
- internal/fptest/networkinstance.go
Adding deviation to enable gribi explicitly under network-instance.
> TE-3.7 and TE-6.2: Enabling "ExplicitGribiUnderNetworkInstance" deviation

- feature/gribi/ate_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
- feature/gribi/ate_tests/gribigo_compliance_test/gribigo_compliance_test.go
- feature/gribi/ate_tests/route_removal_non_default_vrf_test/route_removal_non_default_vrf_test.go
- feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
- feature/gribi/otg_tests/gribigo_compliance_test/gribigo_compliance_test.go
- feature/gribi/otg_tests/route_removal_non_default_vrf_test/route_removal_non_default_vrf_test.go
- internal/deviations/deviations.go
- internal/fptest/networkinstance.go
Changes are made for 2 usage -
1. For variable - ExplicitGRIBIUnderNetworkInstance
2. For function - EnableGRIBIUnderNetworkInstance
Reference - https://github.com/openconfig/featureprofiles/pull/1222#discussion_r1128242618
> Renaming GribiUnderNetworkInstance to GRIBIUnderNetworkInstance

- feature/experimental/system/gnmi/benchmarking/ate_tests/internal/setup/setup.go
- Adding MissingIsisInterfaceAfiSafiEnable deviation for ISIS configs to gNMI-1.2
> Adding MissingIsisInterfaceAfiSafiEnable deviation to gNMI-1.2

- feature/gribi/ate_tests/hierarchical_weight_resolution_test/README.md
Updated test step for ATE port-2 and DUT port-2 config with subinterface indices. This is duplicate of PR#1086. Raised this PR as 1086 is having CLA issue.
> Updated test step for ATE port-2 and DUT port-2 config with subinterface indices

- feature/gribi/ate_tests/weighted_balancing_test/setup_test.go
- internal/fptest/portspeed.go
Enabling ExplicitPortSpeed deviation for TE-3.2, to achieve this `SetPortSpeed` function needs to be updated to accept `testing.TB` , similar to change made for another deviation - https://github.com/openconfig/featureprofiles/pull/948#issuecomment-1385848941.
> TE-3.2: Enabling ExplicitPortSpeed deviation

- feature/experimental/bgp/ate_tests/base_bgp_session_parameters/base_bgp_session_parameters_test.go
- internal/deviations/deviations.go
Made below changes to the testcase:
- As per https://github.com/openconfig/featureprofiles/issues/1043, When BGP is in Established state & it receives a notification message BGP should go into IDLE state. Made changes to check for Not Established BGP state instead of Active.
- For TestEstablishAndDisconnect case "Test the iBGP session establishment: Neighbor AS", changed localAS (the Global AS) numberto be different than for nbrLocalAS (per-neighbor local-as). https://github.com/openconfig/featureprofiles/issues/1044
- Added a deviation for TestPassword to skip the mismatched password.
> RT-1.1 Changes to base_bgp_session_parameters_test

- feature/experimental/qos/ate_tests/bursty_traffic_test/README.md
- feature/experimental/qos/ate_tests/bursty_traffic_test/bursty_traffic_test.go
QoS: Check TransmitOctets and DroppedOctets counters are updated in addition to TransmitPkts and DroppedPkts
- TransmitPkts
- TransmitOctets
- DroppedPkts
- DroppedOctets
The change is similar to https://github.com/openconfig/featureprofiles/pull/1219
> Update experimental bursty_traffic_test.go to check TransmitOctets and DroppedOctets counters

- feature/interface/singleton/ate_tests/singleton_test/singleton_test.go
- feature/interface/singleton/otg_tests/singleton_test/singleton_test.go
There are 2 changes -
1. Adding deviations ExplicitInterfaceInDefaultVRF and  ExplicitPortSpeed
2. Fixing mac-address to upper-case
> RT-5.1: Enabling deviation ExplicitInterfaceInDefaultVRF and ExplicitPortSpeed

- topologies/binding/gnoi.go
The [Packet-based Link Qualification](https://github.com/openconfig/featureprofiles/blob/main/feature/gnoi/packet_link_qualification/tests/packet_link_qualification_test/README.md) test needs the GNOI LinkQualification service.
> Add link qualification GNOI client to Ondatra binding

- feature/bgp/gracefulrestart/ate_tests/bgp_graceful_restart_test/bgp_graceful_restart_test.go
Currently RT-1.4 subtest `VerifyTrafficPasswithGRTimerWithAclApplied` is verifying traffic to pass while holdtime expires as there is no graceful restart getting triggered.
This PR adds the graceful restart trigger on TGN before ACL gets added.
> BGP RT-1.4 : Added graceful restart trigger from ATE

- feature/experimental/gribi/ate_tests/backup_nhg_action/backup_nhg_action_test.go
- internal/gribi/gribi.go
There are 2 changes made here -
1. Enabling following deviations - 
- `ExplicitInterfaceInDefaultVRF`
- `ExplicitPortSpeed` 
- `ExplicitGRIBIUnderNetworkInstance`
2. Updating static-route NextHop index to an integer
> TE-11.3: Enabling deviation, updating NH index to integer and adding network-instance for DECAP lookup

- feature/experimental/gribi/ate_tests/backup_nhg_action/backup_nhg_action_test.go
Network instance type is set to "DEFAULT".
It is mandatory for user to specify type of network instance. For DEFAULT network instance type is "DEFAULT"
> TE-11.3: Setting DefaultNetworkInstance on the device 

- feature/experimental/system/gnmi/benchmarking/ate_tests/drained_configuration_convergence_time/drained_configuration_convergence_time_isis_test.go
- Use WatchAll instead of GetAll for verifying metric changes in ate
> gNMI-1.3: Use WatchAll for verifying metric changes in ate

- feature/experimental/policy/policy_vrf_selection/ate_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
- feature/experimental/policy/policy_vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
Test case#3 (duplicated DSCP values) updated according to the new README (#1272).
We introduce a new bool flag "rejectable" that indicates that the test case can be skipped if PF config is rejected by a DUT
---
<sup>
> rt-3.2: update case#3 to skip the test if PF config is rejected

- feature/experimental/gribi/otg_tests/backup_nhg_action/backup_nhg_action_test.go
- Add the deviations.InterfaceConfigVrfBeforeAddress logic that was added to the ATE version of the test shortly before the OTG version merged.
> Replicate missed deviation from backup_nhg_action ATE test

- feature/gribi/otg_tests/supervisor_failure_test/supervisor_failure_test.go
- Ensure that in/out packet counts for traffic verification are queried in the same request as traffic is still running so they will vary if queried separately.
> Query full counter state one time in supervisor_failure_test

- feature/gribi/ate_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go
In Openconfig AFT model, it's not yet defined/concluded that if the viability of a NH should be represented by the existence of the NH, or should it be indicated by a new leaf container. Therefore, this PR suggests relax the AFT checking on NH now.
> TE-11.2, remove AFT check on NH viability

- tools/validate_paths.go
This avoids running the validate_paths check on metadata.textproto files
> Feature files are just those named feature.textproto

- feature/experimental/p4rt/tests/p4rt_election/p4rt_election_test.go
- internal/deviations/deviations.go
Moving deviation flag P4RTMissingDelete to an accessor method. Tests which require deviation should call these methods instead of the deviation flags.
> Moving deviation flag P4RTMissingDelete to an accessor method

- feature/experimental/interface/my_station_mac/ate_tests/my_station_mac_test/my_station_mac_test.go
- internal/deviations/deviations.go
Adds -deviation_mac_address_missing for devices that do not support /system/mac-address/state
> TE-1.2: add deviation for /system/mac-address/state

- feature/bgp/prefixlimit/ate_tests/bgp_prefix_limit_test/bgp_prefix_limit_test.go
- internal/deviations/deviations.go
PiperOrigin-RevId: 522249454
Moving deviation flags BGPPrefixOverlimit and BGPTrafficTolerance to an accessor method. 
Both deviations flags are only used in the `bgp_prefix_limit_test`
> Moving deviation flags BGPPrefixOverlimit and BGPTrafficTolerance to an accessor method

- feature/bgp/gracefulrestart/ate_tests/bgp_graceful_restart_test/bgp_graceful_restart_test.go
- internal/deviations/deviations.go
- Added `configACLNative()`, `configAdmitAllACLNative()`, `configACLInterfaceNative()` for ACL configurations on native SRL model
- Added a Deviation flag `deviation_use_native_acl_config` to enable using the above mentioned functions
> RT-1.4 Adding Native SRL ACL compatibility

- feature/experimental/qos/ate_tests/qos_basic_test/qos_basic_test.go
- internal/deviations/deviations.go
DP-1.14 : QoS basic test - Adding required QoS config.
 
1. Pull request https://github.com/openconfig/featureprofiles/pull/1385 got closed by accident, Opening this pull request with similar changes.
2. Added Queue ID as required by Juniper. 
Other pull request containing such changes: https://github.com/openconfig/featureprofiles/pull/1087
    Related OC model change: https://github.com/openconfig/public/pull/772 
3. Introducing new deviation - ECNProfileRequiredDefinition
* Using percentages instead of bytes for min-threshold 
Related OC model pull request(pending): https://github.com/openconfig/public/pull/688
* Adding max-threshold and max-drop-probability-percent for ECN config.
4. Included existing deviation  ExplicitInterfaceRefDefinition for interface configuration under …
> DP-1.14 : QoS basic test - Adding required QoS config

- Makefile
- tools/clone_oc_public.sh
I don't think it's necessary to require manual intervention when it comes to updating major OC releases. We can start to provide failure signals as soon as a new version of OC has been released. Affected PRs will be given signal to update themselves, and repo maintainers are given a signal to start fix existing tests.
> Change `make openconfig_public` to update in lock-step with new OC releases

- feature/experimental/p4rt/internal/p4rtutils/p4rtutils.go
- feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
This PR updates P4RTNodesByPort and the P4RT subtests of gNMI-1.10 to allow multiple ports to map to the same hardware-port. It also remove inferP4RTNodeName for CISCO.
> P4RT: update P4RTNodesByPort to support breakout ports

- internal/deviations/deviations.go
Remove GRIBIPreserveOnly deviation flag since it is not used by tests anymore.
> Remove GRIBIPreserveOnly deviation

- feature/networkinstance/ate_tests/defaults_test/defaults_test.go
In EOS, the interface ip address in removed when the interface is configured under a new network instance and hence the ip address configuration for that inteface needs to be pushed again. This caused an issue in the test where the dut interface ip address is not present when gnmi.update was done with a configuration that had 1 - new non default nwInstance configuration
2 - interface configuration in that non default nwInstance 3 - interface ip address configuration
when the interfaces were configured under default nwInstance with the same ipaddress before.
Due to the above behavior in EOS, I have added a new deviation check that causes the test do a gnmi update for (1) and (2) first followed by gnmi update for (3)
> Fix OC-1.2: Default Address Families Test failure due to ip address configuration missing

- feature/bgp/tests/local_bgp_test/local_bgp_test.go
- internal/deviations/deviations.go
Removing deviation for MissingBgpNeighborStatePeerGroup in RT1.7.
> Removing deviation for MissingBgpNeighborStatePeerGroup

- feature/gribi/otg_tests/ack_in_presence_other_routes/route_ack_test.go
1. fixed static route NH index to be inline with ATE test 
2. updated with deviation ExplicitGRIBIUnderNetworkInstance
This code is a Contribution to the OpenConfig Feature Profiles project ("Work") made under the Google Software Grant and Corporate Contributor License Agreement ("CLA") and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia's intellectual property are granted for any other purpose. This code is provided on an as is basis without any warranties of any kind.
> fixed static route NH index 

- feature/gribi/ate_tests/hierarchical_weight_resolution_test/README.md
- feature/gribi/ate_tests/hierarchical_weight_resolution_test/hierarchical_weight_resolution_test.go
- internal/deviations/deviations.go
Opened PR to address CLA check failure for PR https://github.com/openconfig/featureprofiles/pull/1417
PR is based on a request to enhance TE3.3 based on https://github.com/openconfig/featureprofiles/pull/1133 and https://github.com/openconfig/featureprofiles/pull/1239
Issues addressed:
- Case1: Basic hierarchical weight, changed tolerance to 0.2
- Case2: Hierarchical weight in boundary scenarios, changed the programming to 16 NHs
- For better UCMP results, added ipinip flow with inner 64k prefixes
- Update PBR to match ipinip flow
- Added deviation "ucmpTrafficTolerance" for Case 2 tolerance (need to run TC with 1.5 tolerance for us)
> TE-3.3-uprev: Opened PR to address CLA check failing for PR 1417

- feature/experimental/policy/policy_vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
Changed the ATE source MAC  from "01:00:02:01:01:01" to "00:12:01:00:00:01".
01:00:02:01:01:01 is a group address and source MAC must not be a group address. In the Source Address field, the first bit is reserved and set to 0. When MAC "01:00:02:01:01:01" is used, there are is no ARP reply being sent from DUT since "01:00:02:01:01:01" is a group address.
Please refer to - IEEE 802.3-2002, Section 3.2.3(b) - https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=988967
> RT-3.2: OTG: Changed the ATE source MAC  from "01:00:02:01:01:01" to "00:12:01:00:00:01"

- feature/gribi/otg_tests/gribi_scaling/gribi_scaling_test.go
Porting changes from #1356 to OTG location
As per testplan , nexthop address for instance "vrf3" should not be >> tunnelDstIP = "198.18.208.1"
> TE-14.1 - OTG: Fixed nexthop address for instance vrf3

- feature/system/ntp/tests/system_ntp_test/server_test.go
- internal/deviations/deviations.go
Moving deviation flag NTPAssociationTypeRequired to accessor method
> Moving deviation flag NTPAssociationTypeRequired to accessor method

- cloudbuild/cloudbuild.yaml
- test.md
Fixes the presubmit, 8000e now passes. Due to os-login, by default non-root users need to provide a password to sudo. sudo is required for 8000e due to limitations around kernel.pid_max (see https://github.com/openconfig/kne/tree/main/examples/cisco/8000e#check-perquisites-and-create-a-kne-topology-using-topology-8000e-ixiapbtxt). This change allows the user the test runs as to be able to sudo without providing a password to fix the issue.
> Fix presubmit for cisco 8000e

- feature/qos/otg_tests/wrr_traffic_test/README.md
Test functionality matches. README was initially out of date on both, ATE version was fixed already.
> Update wrr_traffic_test OTG README to match ATE version

- feature/gnoi/system/tests/traceroute_test/traceroute_test.go
- internal/deviations/deviations.go
Move TraceRouteL4ProtocolUDP and TraceRouteFragmentation to accessor methods
> Move TraceRouteL4ProtocolUDP and TraceRouteFragmentation to accessors

- feature/experimental/isis/ate_tests/base_adjacencies_test/base_adjacencies_test.go
- feature/experimental/isis/ate_tests/internal/session/session.go
- feature/experimental/isis/otg_tests/base_adjacencies_test/base_adjacencies_test.go
- feature/experimental/isis/otg_tests/internal/session/session.go
- feature/experimental/system/gnmi/benchmarking/ate_tests/internal/setup/setup.go
- internal/deviations/deviations.go
PiperOrigin-RevId: 529597588
Move ISISInterfaceLevel1DisableRequired and MissingIsisInterfaceAfiSafiEnable to accessor methods.
> Move ISISInterfaceLevel1DisableRequired and MissingIsisInterfaceAfiSafiEnable to accessor methods.

- feature/platform/ate_tests/telemetry_inventory_test/telemetry_inventory_test.go
This Pull Req is bringing in run time improvements to gNMI-1.4 (Telemetry Inventory Test) as detailed below:
- Function 'findComponentsListByType' does a gNMI Subscribe for 'All Components', orders the components by type and returns the names of the components (ordered by type)
- Testcases TestHardwarecards and TestSwitchChip obtain the component names from the above, pass the names on to the function 'ValidateComponentState' which subsequently runs multiple gNMI Subscribe operations for verifying the data under each component
- Depending on the number of components of a given type present on the DUT, the number of gNMI operations could end up being quite high leading to increased script run time
Optimization proposed in this Pull Req:
- Modify the function 'findComponentsListByType' to …
> gNMI-1.4: Telemetry Inventory Test - runtime improvements

- feature/experimental/backup_nhg/ate_tests/backup_nhg_test/backup_nhg_test.go
- feature/experimental/gribi/ate_tests/backup_nhg_action/backup_nhg_action_test.go
- feature/experimental/gribi/ate_tests/route_addition_during_failover_test/route_addition_during_failover_test.go
- feature/experimental/gribi/ate_tests/route_removal_during_failover_test/route_removal_during_failover_test.go
- feature/experimental/gribi/otg_tests/backup_nhg_action/backup_nhg_action_test.go
- feature/experimental/gribi/otg_tests/route_addition_during_failover_test/route_addition_during_failover_test.go
- feature/experimental/gribi/otg_tests/route_removal_during_failover_test/route_removal_during_failover_test.go
- feature/gribi/ate_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go
- feature/gribi/ate_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
- feature/gribi/ate_tests/gribi_scaling/gribi_scaling_test.go
- feature/gribi/ate_tests/gribigo_compliance_test/gribigo_compliance_test.go
- feature/gribi/ate_tests/hierarchical_weight_resolution_test/hierarchical_weight_resolution_test.go
- feature/gribi/ate_tests/route_removal_non_default_vrf_test/route_removal_non_default_vrf_test.go
- feature/gribi/otg_tests/ack_in_presence_other_routes/route_ack_test.go
- feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go
- feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
- feature/gribi/otg_tests/gribi_scaling/gribi_scaling_test.go
- feature/gribi/otg_tests/gribigo_compliance_test/gribigo_compliance_test.go
- feature/gribi/otg_tests/route_removal_non_default_vrf_test/route_removal_non_default_vrf_test.go
- internal/deviations/deviations.go
PiperOrigin-RevId: 529577328
Move ExplicitGRIBIUnderNetworkInstance to accessor method
> Move ExplicitGRIBIUnderNetworkInstance to accessor method

- feature/experimental/policy/policy_vrf_selection/ate_tests/base_vrf_selection/base_vrf_selection_test.go
- feature/experimental/policy/policy_vrf_selection/ate_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
- feature/experimental/policy/policy_vrf_selection/otg_tests/base_vrf_selection/base_vrf_selection_test.go
- feature/experimental/policy/policy_vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
- feature/gribi/ate_tests/gribi_scaling/gribi_scaling_test.go
- feature/gribi/ate_tests/hierarchical_weight_resolution_test/hierarchical_weight_resolution_test.go
- feature/gribi/otg_tests/gribi_scaling/gribi_scaling_test.go
- feature/qos/ate_tests/bursty_traffic_test/bursty_traffic_test.go
- feature/qos/ate_tests/mixed_sp_wrr_traffic_test/mixed_sp_wrr_traffic_test.go
- feature/qos/ate_tests/one_sp_queue_traffic_test/one_sp_queue_traffic_test.go
- feature/qos/ate_tests/qos_basic_test/qos_basic_test.go
- feature/qos/ate_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go
- feature/qos/ate_tests/qos_policy_config_test/qos_policy_config_test.go
- feature/qos/ate_tests/two_sp_queue_traffic_test/two_sp_queue_traffic_test.go
- feature/qos/ate_tests/wrr_traffic_test/wrr_traffic_test.go
- feature/qos/otg_tests/bursty_traffic_test/bursty_traffic_test.go
- feature/qos/otg_tests/qos_basic_test/qos_basic_test.go
- feature/qos/otg_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go
- feature/qos/otg_tests/wrr_traffic_test/wrr_traffic_test.go
- internal/deviations/deviations.go
PiperOrigin-RevId: 529593573
Move ExplicitInterfaceRefDefinition to accessor method
> Move ExplicitInterfaceRefDefinition to accessor method

- feature/experimental/gribi/ate_tests/backup_nhg_action/backup_nhg_action_test.go
- feature/experimental/gribi/otg_tests/backup_nhg_action/backup_nhg_action_test.go
- feature/gribi/ate_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
- feature/gribi/ate_tests/route_removal_non_default_vrf_test/route_removal_non_default_vrf_test.go
- feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
- feature/gribi/otg_tests/route_removal_non_default_vrf_test/route_removal_non_default_vrf_test.go
- feature/networkinstance/ate_tests/defaults_test/defaults_test.go
- internal/deviations/deviations.go
PiperOrigin-RevId: 529580090
Move InterfaceConfigVrfBeforeAddress to accessor.
> Move InterfaceConfigVrfBeforeAddress to accessor.

- feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
- feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
for Arista 7280:
"/components/component[name=EOS]/state/parent"
{
"components": {
"component": {
"EOS": {
"state": {
"parent": "Chassis"
}
}
}
}
}
"/components/component[name=Chassis]/state/type"
{
"components": {
"component": {
"Chassis": {
"state": {
"type": "openconfig-platform-types:CHASSIS"
}
}
}
}
}
for Arista 7808:
"/components/component[name=Supervisor1-EOS]/state/parent"
{
"components": {
"component": {
"Supervisor1-EOS": {
"state": {
"parent": "Supervisor1"
}
}
}
}
}
"/components/component[name=Supervisor1]/state/type"
{
"components": {
"component": {
"Supervisor1": {
"state": {
"type": "openconfig-platform-types:CONTROLLER_CARD"
}
}
}
}
}
"/components/component[name=Supervisor1]/state/parent"
{
"components": {
"component": {
"Supervisor1": {
"state": {
"parent": "Chassis"
}
}
} …
> Arista_7280 OC component EOS has parent type Chassis

- feature/experimental/gribi/ate_tests/route_addition_during_failover_test/route_addition_during_failover_test.go
- feature/experimental/gribi/ate_tests/route_removal_during_failover_test/route_removal_during_failover_test.go
- feature/experimental/gribi/otg_tests/route_addition_during_failover_test/route_addition_during_failover_test.go
- feature/experimental/gribi/otg_tests/route_removal_during_failover_test/route_removal_during_failover_test.go
- feature/gnoi/system/tests/chassis_reboot_status_and_cancel_test/chassis_reboot_status_and_cancel_test.go
- feature/gnoi/system/tests/per_component_reboot_test/per_component_reboot_test.go
- feature/gnoi/system/tests/supervisor_switchover_test/supervisor_switchover_test.go
- feature/gribi/ate_tests/supervisor_failure_test/supervisor_failure_test.go
- feature/gribi/otg_tests/supervisor_failure_test/supervisor_failure_test.go
- internal/components/components.go
- internal/deviations/deviations.go
PiperOrigin-RevId: 529713463
Move GetSubcomponentPath to accessor method.
> Move GetSubcomponentPath to accessor method.

- feature/experimental/p4rt/internal/p4rtutils/p4rtutils.go
- feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
- feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
- internal/deviations/deviations.go
PiperOrigin-RevId: 532155770
Move `ExplicitP4RTNodeComponent` to accessor.
> Move `ExplicitP4RTNodeComponent` to accessor.

- topologies/kne/arista_ceos.textproto
- topologies/kne/arista_ceos_lag.textproto
- topologies/kne/juniper_cptx.textproto
- topologies/kne/juniper_cptx_dutdut.textproto
- topologies/kne/juniper_cptx_lag.textproto
Specify the cptx image path in `juniper_cptx_lag.textproto` and remove optional commas from textprotos for consistency.
> KNE Textproto Updates

- feature/platform/tests/power_admin_down_up_test/power_admin_down_up_test.go
Adding deviations.MissingValueForDefaults for SUP power-admin-state which the default value is not streamed in telemetry to make the test the deviation aware!
gNMI GET "/components/component[name=Supervisor1]/controller-card/state/power-admin-state"
{
}
> Adding deviations.MissingValueForDefaults for SUP power-admin-state which the default value is not streamed in telemetry

- cloudbuild/virtual.sh
- cloudbuild/virtual.yaml
- tools/ci-trigger/README.md
- tools/ci-trigger/config.go
* Update docs to recommend 1GB memory for CI Trigger.
* Update Cloud Build to use `/tmp/featureprofiles` for working directory: metadata file detection requires a root directory with this name.
* Add a 'Help' link to docs to PR comments.
> Update KNE CI Trigger

- feature/platform/tests/telemetry_inventory_test/telemetry_inventory_test.go
Manufacturer name is not required for CPU per conversation in b/283934938
---
<sup>
> gnmi-1.4: disable mfg-name validation for cpu component type

- tools/ci-trigger/pr.go
- tools/ci-trigger/pr_test.go
The metadata protobuf is regularly changing as deviations evolve in pull requests.  Currently, ci-trigger will fail to parse the metadata.textproto if any new fields are introduced.  This PR allows for the unknown fields to be ignored, as it only needs to be aware of the PlanID and Description fields.
> ci-trigger: Allow unknown fields when decoding metadata.

- internal/gribi/gribi.go
In #1740, code for gribi addNH() helper was modified to remove interface-ref from intf+MAC NH case statement, that doesn't seem to be correct
restoring the previous version
---
<sup>
</sup>
> restore mac+interface-ref addNH() code in gribi.go helper

- feature/gnoi/system/tests/per_component_reboot_test/metadata.textproto
the non-modular 7280 doesn't support dedicated fabric chip for OC query nor reboot operation., same to the cEOS instance.
> adding 7280 and cEOS to the fabric_component_reboot_unsupported exception list 

- internal/check/check_test.go
We occasionally see an error such as `check_test.go:279: Error [/parent/child/state/two: got no value, want "correct" (deadline exceeded)]: Missing substring "EOF"` in `go test` output in GitHub Actions CI. This change raises the deadline from 50ms to 500ms. I have not been able to reproduce this flake on my machine except when significantly lowering the deadline (i.e. 10ms). These flakes might be explained if the CPU is being preempted on the GitHub runner side.
Fixes #1759.
> Increase await timeouts for slower systems

- feature/gribi/ate_tests/base_hierarchical_route_installation_test/metadata.textproto
- feature/gribi/otg_tests/base_hierarchical_route_installation_test/metadata.textproto
Adding following 2 missing deviations to `metadata.textproto` -
explicit_gribi_under_network_instance: true
explicit_interface_ref_definition: true
> TE-3.1: Updating metadata.textproto with missing deviation

- tools/ci-trigger/cloudbuild.go
- tools/ci-trigger/config.go
- tools/ci-trigger/pr.go
This PR adds support for raw logs to be exported to buckets by Cloud Build.  The existing link to the GCP Cloud Build log/console has some issues with how logs are rendered and we do not want to broadly expose access to this anyway.  With this change, log text files are exported to buckets by vendor.  This will allow for giving more fine-grained access to these logs in the future.
> ci-trigger: Add support for raw log buckets

- cloudbuild/cleanup.sh
- cloudbuild/cloudbuild.yaml
- cloudbuild/test.sh
- cloudbuild/virtual.sh
- cloudbuild/virtual.yaml
In some cases, it is possible for Cloud Build to terminate a job immediately without cleanup.  This can leave VM instances orphaned because Cloud Build is the only task that can clean up an instance.  With this change, VMs will delete themselves after 2 hours.  This is greater than the 2700s (45min) limit currently set, so it should only be possible to trigger this event if something has gone wrong.
> Support for self-deletion of CI VM instances.

- feature/experimental/policy/policy_vrf_selection/ate_tests/base_vrf_selection/base_vrf_selection_test.go
- feature/experimental/policy/policy_vrf_selection/otg_tests/base_vrf_selection/base_vrf_selection_test.go
The test was failing for the following reasons:
- parent interface was not routed causing the subinterfaces to not be routed as well.
- DUT egress interface ip address was getting configured before the VRF assignment. So when the interface was moved to VRF-10, the interface ipv4 address got reset.
- Unsupported interface ref leaf was set in the interface OC configuration
- The match source ip in the vrf selection policy rule was incorrectly set and hence the incoming traffic flows expected to pass through VRF-10 were not getting forwarded correctly
After fixing the above issues the test is passing correctly
> Fix base_vrf_selection_test failure for ARISTA

- feature/experimental/policy/policy_vrf_selection/ate_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
- feature/experimental/policy/policy_vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
The test was failing for the following reasons
- The subinterface was not a routed port which is not supported in EOS when the parent is routed
- OC configuration for applying vrf selection policy in the ingress interface was incorrect and erroring out. After fixing the above 2, the test is passing fine
> Fix for protocol_dscp_rules_for_vrf_selection_test failure in EOS

- feature/experimental/bgp/ate_tests/bgp_always_compare_med/bgp_always_compare_med_test.go
- feature/experimental/bgp/ate_tests/bgp_always_compare_med/metadata.textproto
Added route-policy to import routes on ebgp sessions under peer-group under deviation and peer-group/afisafi/
> RT-1.12: adding route-policy import for ebgp sessions

- feature/experimental/p4rt/ate_tests/base_p4rt/base_p4rt_test.go
- feature/experimental/p4rt/ate_tests/google_discovery_protocol_packetin_test/google_discovery_protocol_packetin_test.go
- feature/experimental/p4rt/ate_tests/google_discovery_protocol_packetout_test/google_discovery_protocol_packetout_test.go
- feature/experimental/p4rt/ate_tests/lldp_packetin_test/lldp_packetin_test.go
- feature/experimental/p4rt/ate_tests/lldp_packetout_test/lldp_packetout_test.go
- feature/experimental/p4rt/ate_tests/performance_test/performance_test.go
- feature/experimental/p4rt/ate_tests/traceroute_packetin_test/traceroute_packetin_test.go
- feature/experimental/p4rt/ate_tests/traceroute_packetout_test/traceroute_packetout_test.go
- feature/experimental/p4rt/otg_tests/base_p4rt/base_p4rt_test.go
- feature/experimental/p4rt/otg_tests/google_discovery_protocol_packetin_test/google_discovery_protocol_packetin_test.go
- feature/experimental/p4rt/otg_tests/google_discovery_protocol_packetout_test/google_discovery_protocol_packetout_test.go
- feature/experimental/p4rt/otg_tests/lldp_packetin_test/lldp_packetin_test.go
- feature/experimental/p4rt/otg_tests/lldp_packetout_test/lldp_packetout_test.go
- feature/experimental/p4rt/otg_tests/performance_test/performance_test.go
- feature/experimental/p4rt/otg_tests/traceroute_packetin_test/traceroute_packetin_test.go
- feature/experimental/p4rt/otg_tests/traceroute_packetout_test/traceroute_packetout_test.go
- feature/experimental/p4rt/tests/p4rt_election/p4rt_election_test.go
- go.mod
- go.sum
This PR updates go-p4 library and p4rt tests to address https://github.com/cisco-open/go-p4/issues/16
> Update go-p4 library

- feature/gribi/ate_tests/hierarchical_weight_resolution_test/hierarchical_weight_resolution_test.go
Some devices require a Routed SubInterface 0 for other SubInterfaces to be active.
Adding the relevant deviation for the same.
> add RequireRoutedSubinterface0 deviation

- tools/ci-trigger/pr.go
- tools/ci-trigger/trigger.go
If a pull request was created by an authorized user, launch tests for all virtual device types instead of waiting for the user to post `/fptest virtual` in a comment.  This mimics the previous Cloud Build native behavior where tests would automatically run when the PR was submitted by a contributor.
> ci-trigger: Launch virtual tests if PR author is authorized

- go.mod
- go.sum
- tools/wikidoc/wikidoc.go
The [wiki](https://github.com/openconfig/featureprofiles/wiki) has a list of all test plans auto generated into a single reference.  With the introduction of metadata.textproto in test directories, we can now identify tests more reliably. The logic previously only considered "ate_tests" or "tests" as valid directories. Now, OTG tests can be considered.  Tests are deduplicated by UUIDs.
> Update Wiki to parse test metadata

- tools/ci-trigger/cloudbuild.yaml
Create a cloudbuild.yaml file to auto-deploy ci-trigger.
After merging, the Cloud Build trigger will need to be created/enabled in GCP.  This trigger will only run on the main branch when a change in tools/ci-trigger (or protos) occurs.
> Deploy ci-trigger automatically with Cloud Build

- feature/isis/feature.textproto
Adding additional adjacency state telemetry paths to isis/feature.textproto:
- .../circuit-counters/state/adj-changes
- .../levels/level/adjacencies/adjacency/state/up-timestamp
> adding additional adjacency state telemetry to isis/feature.textproto

- feature/system/ntp/tests/system_ntp_test/metadata.textproto
This PR enables ntp_non_default_vrf_unsupported deviation for Nokia
---
<sup>
</sup>
> OC-26.1: enable deviation for Nokia

- feature/experimental/p4rt/ate_tests/performance_test/performance_test.go
- feature/experimental/p4rt/otg_tests/performance_test/performance_test.go
The test was failing intermittently in EOS because the ATE ingress counters check for verifying the expected packetOut counters was done right after injecting the traceroute/LLDP/GDP packets with no delay.
There is no guarantee that all the packetOut requests have been guaranteed by that time. Added a 30s delay, to account for any trailing inflight packets.
> Fix P4Runtime performance test in EOS

- feature/experimental/backup_nhg/ate_tests/backup_nhg_test/backup_nhg_test.go
- feature/experimental/backup_nhg/otg_tests/backup_nhg_test/backup_nhg_test.go
- feature/experimental/gribi/ate_tests/dut_daemon_failure/dut_daemon_failure_test.go
- feature/experimental/gribi/otg_tests/dut_daemon_failure/dut_daemon_failure_test.go
- feature/experimental/p4rt/ate_tests/p4rt_daemon_failure_test/p4rt_daemon_failure_test.go
- feature/experimental/p4rt/otg_tests/p4rt_daemon_failure_test/p4rt_daemon_failure_test.go
- feature/gribi/ate_tests/ack_in_presence_other_routes/route_ack_test.go
- feature/gribi/ate_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go
- feature/gribi/ate_tests/base_leader_election_test/base_leader_election_test.go
- feature/gribi/ate_tests/get_rpc_test/get_rpc_test.go
- feature/gribi/ate_tests/ordering_ack_test/ordering_ack_test.go
- feature/gribi/ate_tests/persistence_mode_test/persistence_mode_test.go
- feature/gribi/ate_tests/route_removal_non_default_vrf_test/route_removal_non_default_vrf_test.go
- feature/gribi/ate_tests/supervisor_failure_test/supervisor_failure_test.go
- feature/gribi/otg_tests/ack_in_presence_other_routes/route_ack_test.go
- feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go
- feature/gribi/otg_tests/base_leader_election_test/base_leader_election_test.go
- feature/gribi/otg_tests/get_rpc_test/get_rpc_test.go
- feature/gribi/otg_tests/ordering_ack_test/ordering_ack_test.go
- feature/gribi/otg_tests/persistence_mode_test/persistence_mode_test.go
- feature/gribi/otg_tests/route_removal_non_default_vrf_test/route_removal_non_default_vrf_test.go
- feature/gribi/otg_tests/supervisor_failure_test/supervisor_failure_test.go
- go.mod
- go.sum
Per ondatra@v0.2.0 `telemetry-atomic` nodes no longer provide path access to descendants: https://github.com/openconfig/ondatra/releases/tag/v0.2.0
> Use latest version of Ondatra and enable atomic-aware ygnmi API

- tools/ci-trigger/cloudbuild.yaml
The build https://github.com/openconfig/featureprofiles/runs/15034045050 failed to deploy. This was the first time a change was made that triggered a rebuild of the service.  It failed because the service name is actually `featureprofiles-ci-trigger` not `ci-trigger`.
> Fix ci-trigger Cloud Build service name

- feature/gnoi/packet_link_qualification/tests/packet_link_qualification_test/metadata.textproto
update packet_link_qual metadata to enable deviation_link_qual_wait_after_delete_required
> set link_qual_wait_after_delete_required in metadata.proto

- feature/experimental/p4rt/tests/metadata_validation_test/metadata_validation_test.go
This PR fixes writeReadTableEntry(), previous version was ignoring `action` argument and always used an insert 
---
<sup>
> p4rt-2.2: fix writeReadTableEntry()

- tools/ci-trigger/main.go
- tools/ci-trigger/pr.go
- tools/ci-trigger/trigger.go
Improve logging of ci-trigger.  If there are any errors while handling an event, it is difficult to figure out which event caused the error.  Additionally, there was no logging for when a job was successfully created - this makes it a bit easier to understand which user approved a job.
> Add logging details to ci-trigger

- feature/security/gnsi/authz/tests/README.md
Call out that we should not pre-configured local users 1:1 mapped to SPIFFE-ID.
> gNSI.Authz test plan update

- feature/experimental/isis/ate_tests/internal/session/session.go
- feature/experimental/isis/otg_tests/internal/session/session.go
- go.mod
- go.sum
This introduced a slight backwards-incompatibility with the generated packages. Which is fixed in the relevant tests.
> Update Ondatra to v0.2.7

- tools/ci-trigger/Dockerfile
- tools/ci-trigger/README.md
- tools/ci-trigger/cloudbuild.go
- tools/ci-trigger/cloudbuild.yaml
- tools/ci-trigger/cloudbuild_test.go
- tools/ci-trigger/main.go
- tools/ci-trigger/pr.go
- tools/ci-trigger/trigger.go
This PR updates ci-trigger code archive creation behavior.  This is necessary to support offline compilation of Go tests.
* Generate/reuse a single code archive for all vendors instead of per-vendor.
* Vendor go deps into code archive to support offline compilation.
* Process events asynchronously from the GitHub API HTTP triggering event.
* Write PR and SHA to code archive metadata.
* Use go1.21 for ci-trigger container.
* Enable stderr logging in ci-trigger container.
* Add badge_pubsub arg to optionally disable processing badge pubsub events.
* Fix a typo in metadata restoration that could break the "raw log" comment link.
> Update ci-trigger archive creation

- feature/experimental/p4rt/tests/metadata_validation_test/metadata.textproto
This PR removes `p4rt_modify_table_entry_unsupported` deviation for nokia 
---
<sup>
</sup>
> p4rt-2.2: remove deviation for nokia

- feature/experimental/system/health/tests/system_generic_health_check/system_generic_health_check_test.go
the var is per vendor specific for Core file checks
> Adding support for vendor ARISTA in Core file check test

- feature/experimental/bgp/ate_tests/bgp_2byte_4byte_asn/metadata.textproto
- feature/experimental/bgp/ate_tests/bgp_2byte_4byte_asn_policy_test/metadata.textproto
- feature/experimental/bgp/ate_tests/bgp_always_compare_med/metadata.textproto
- feature/experimental/bgp/ate_tests/bgp_long_lived_graceful_restart/metadata.textproto
- feature/experimental/bgp/otg_tests/bgp_afi_safi_defaults/metadata.textproto
- feature/experimental/bgp/otg_tests/bgp_always_compare_med/metadata.textproto
- feature/experimental/isis/ate_tests/isis_change_lsp_lifetime_test/metadata.textproto
- feature/experimental/isis/otg_tests/isis_interface_hello_padding_enable_test/metadata.textproto
- feature/experimental/isis/otg_tests/isis_interface_passive_test/metadata.textproto
- feature/experimental/isis/otg_tests/isis_metric_style_wide_enabled_test/metadata.textproto
- feature/experimental/isis/otg_tests/isis_metric_style_wide_not_enabled_test/metadata.textproto
- feature/experimental/system/health/tests/system_generic_health_check/metadata.textproto
- feature/experimental/tunnel/otg_tests/tunnel_acl_based_test/metadata.textproto
Updating metadata.textproto for the following tests with `tags: TAGS_AGGREGATION`:
- RT-1.12
- RT-2.7
- RT-1.19
- RT-1.14
- RT-2.10
- RT-1.24
- Health-1.1
- RT-2.8
- RT-2.9
- RT-2.6
- TUN-1.9
- RT-1.23
> Adding tags to metadata.textproto

- feature/experimental/bgp/ate_tests/bgp_2byte_4byte_asn/bgp_2byte_4byte_asn_test.go
- feature/experimental/bgp/ate_tests/bgp_2byte_4byte_asn/metadata.textproto
* Test was setting GlobalAS and validating the same value in LocalAS leaf.
* Updated test to configure separate LocalAS, GlobalAS and PeerAS.
* Update required deviation for Arista.
> Fix BGP 2byte 4byte asn test

- feature/gribi/otg_tests/mpls_compliance/gribi_mpls_compliance_test.go
- feature/gribi/otg_tests/mpls_forwarding/README.md
- feature/gribi/otg_tests/mpls_forwarding/gribi_mpls_forwarding_test.go
- feature/gribi/otg_tests/mpls_forwarding/metadata.textproto
```
* (A) feature/gribi/otg_tests/mpls_forwarding:
- Add traffic validation to MPLS forwarding test - this validates
that traffic is forwarded according to the pushed label stack.
* (M) feature/gribi/otg_tests/mpls_compliance:
- Minor change to remove sleepFn from being in-line declared.
```
> [1/5] Add traffic forwarding test for gRIBI MPLS label push.

- feature/experimental/bgp/ate_tests/bgp_2byte_4byte_asn/bgp_2byte_4byte_asn_test.go
Current test fails while verifying Global AS an localAS variable is used for configuration
Using globalAS solves the issue
> Using correct global AS variable for bgp_2byte_4byte_asn_test

- tools/allowed_file_types.sh
current script only allows PEM Certificate, but we should allow more:
```
dloher@nettool:~/src/moji$ find . -name .git -prune -o -name openconfig_public -prune -o     -type f -exec file \{} \+ |   egrep -vi '(ASCII|UTF-8|JSON|Perl|shell|PEM certificate)'
./internal/security/svid/testdata/rsa/ca-rsa-key.pem:                                                                                                  PEM RSA private key
./internal/security/svid/testdata/ecdsa/ca-ecdsa-key.pem:                                                                                              PEM EC private key
```
Fixes an issue in PR #2092 CI checks
> Relax filter to allow all pem file types

- feature/gnoi/packet_link_qualification/tests/packet_link_qualification_test/metadata.textproto
- feature/gnoi/packet_link_qualification/tests/packet_link_qualification_test/packet_link_qualification_test.go
1. Added portSpeed deviation
2. set Reflector to ASIC loopback
> gNOI-2.1: Add support for Nokia to PLQ test

- CONTRIBUTING.md
There's still one reference to the directory as an example of structuring ATE test paths, but choosing to leave that while ATE-based tests still exist.
> Switch from ATE->OTG example in CONTRIBUTING doc

- feature/platform/controllercard/tests/controller_card_redundancy_test/README.md
- feature/platform/controllercard/tests/controller_card_redundancy_test/metadata.textproto
* It was conflicting with gNMI-1.15: Set Requests.
* Also moved the files to the correct test path.
> Reassign controller card redundancy test to gNMI-1.17

- proto/testregistry.proto
- testregistry.textproto
Add test registry to track an index of all tests in one place for ease of use.
In a future PR, a github CI check should be added to confirm (or even auto-generate)  the README contains a matching ID and link in the registry.
> Introduce testregistry

- feature/bgp/policybase/otg_tests/default_policies_test/README.md
Following expectation for default-policies at the peer-group and neighbor levels for BGP
*   Default import and export policies are expected to be functional for both IBGP and EBGP peers when policy definition in the policy chain is not satisfied.
*   For IBGP and EBGP peers, when no policy is attached, actions defined in the default-policy (when one exists) should apply.
*   For IBGP peers when no policy is attached including the default-policy, default should be import and export all BGP routes.
*   For EBGP peers when no policy is attached includign the default-policy, default should be to disallow import and export of all BGP routes.
*   In all the above cases, BGP default-policy is applicable only to the BGP learnt routes or the routes that are redistributed in to BGP from other …
> BGP Default Policies README.md

- .github/workflows/go.yml
- .github/workflows/protobufs.yml
- .github/workflows/wiki.yml
This roughly doubles the available disk space for staticcheck from 20GB to 40GB in my testing by removing other language tooling from the base github action image.
This is intended to help this CI step failure:
```
Run GOGC=30 staticcheck ./...
-: # github.com/openconfig/featureprofiles/feature/system/gnmi/get/tests/system_gnmi_get_test_test [github.com/openconfig/featureprofiles/feature/system/gnmi/get/tests/system_gnmi_get_test.test]
compile: writing output: write $WORK/b1301/_pkg_.a: no space left on device (compile)
-: # github.com/openconfig/featureprofiles/feature/system/gnmi/metadata/tests/annotation_test_test [github.com/openconfig/featureprofiles/feature/system/gnmi/metadata/tests/annotation_test.test]
compile: writing output: write $WORK/b1303/_pkg_.a: no space left on device …
```
> Free up space for staticcheck

- feature/gribi/mplsutil/compliance.go
- feature/gribi/otg_tests/mpls_compliance/README.md
- feature/gribi/otg_tests/mpls_compliance/gribi_mpls_compliance_test.go
```
* (M) feature/gribi/mplsutil:
- Add compliance test for popping N labels from an incoming packet
programmed by gRIBI.
* (M) feature/gribi/otg_tests/mpls_compliance:
- Add test with no traffic verification for validating gRIBI
programming API.
```
> [4/5] gRIBI MPLS compliance test for popping N labels from stack.

- feature/gribi/mplsutil/compliance.go
- feature/gribi/otg_tests/mpls_compliance/README.md
- feature/gribi/otg_tests/mpls_compliance/gribi_mpls_compliance_test.go
- feature/gribi/otg_tests/mpls_forwarding/gribi_mpls_forwarding_test.go
```
commit 37e396225e625adff4c628d0414821749cc5cabd
Author: Rob Shakir <robjs@google.com>
Date:   Fri Sep 22 23:17:04 2023 +0000
Add gRIBI control plane only pop top MPLS label test.
* (M) feature/gribi/mplsutil:
- Add test case for popping top MPLS label.
* (M) feature/gribi/otg_tests/mpls_compliance:
- Add control plane only test for popping the top MPLS label from a
stack.
```
> [3/5] Add gRIBI control plane only pop top MPLS label test.

- .github/workflows/go.yml
- internal/core/core.go
Static analysis checks were having issues after #2270 ([example](https://github.com/openconfig/featureprofiles/actions/runs/6672480176/job/18136468288)).  #2270 included a change to free up disk space, but the increased disk usage got cached and filled up the CI runner disk after uncompressing the cache.  This change frees up space earlier so the entire process has extra disk space to work with.
The go build cache & staticcheck cache are around 20GB combined, and the CI runner only has about 20GB of disk space to work with.  By removing some tooling for languages not used, we get about 40GB of space to work with.
The build cache dramatically reduces CI run times so we really want to have caching available.
> Improve staticcheck available disk space

- README.md
- cloudbuild/virtual.sh
- topologies/kne/nokia/srlinux/config.cfg
- topologies/kne/nokia/srlinux/dut.textproto
- topologies/kne/nokia/srlinux/dutate.textproto
- topologies/kne/nokia/srlinux/dutate_lag.textproto
- topologies/kne/nokia/srlinux/dutdut.textproto
- topologies/kne/nokia/srlinux/dutdutate.textproto
- topologies/kne/nokia/srlinux/topology.textproto
1. Add cpm filters for grIBI/gNMI/gNOI IANA ports
2. Change the default login to admin/admin
3. Change the gNMI port the server is listening on (9339)
4. Change the gRIBI port the server is listening on (9340)
5. Add the Service Key/Value pairs for gRIBI/gNOI/P4RT/SSH 
> Nokia KNE fixes for OC-1.1

- feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
adds nokia support for qos counters test 
---
> gnmi-1.10: add default num of queues for nokia

- feature/gnmi/otg_tests/telemetry_basic_check_test/metadata.textproto
- feature/gnmi/otg_tests/telemetry_interface_packet_counters_test/metadata.textproto
`interface_counters_from_container` deviation is not required for nokia 
---
> gnmi-1.10 & gnmi-1.11: remove an unused deviation for nokia

- feature/experimental/bgp/otg_tests/bgp_afi_safi_defaults/bgp_afi_safi_defaults_test.go
Test should look for `active` leaf instead of only looking at the `afi-safi-name`
> Add afi safi change

- go.mod
- go.sum
- proto/ocrpcs.proto
- tools/internal/ocpaths/ocpaths.go
- tools/internal/ocpaths/ocpaths_test.go
- tools/internal/ocpaths/testdata/models/ietf/iana-if-type.yang
- tools/internal/ocpaths/testdata/models/ietf/ietf-inet-types.yang
- tools/internal/ocpaths/testdata/models/ietf/ietf-interfaces.yang
- tools/internal/ocpaths/testdata/models/ietf/ietf-yang-metadata.yang
- tools/internal/ocpaths/testdata/models/ietf/ietf-yang-types.yang
- tools/internal/ocpaths/testdata/models/oc-models/interfaces/openconfig-interfaces.yang
- tools/internal/ocpaths/testdata/models/oc-models/openconfig-extensions.yang
- tools/internal/ocpaths/testdata/models/oc-models/platform/openconfig-platform.yang
- tools/internal/ocpaths/testdata/models/oc-models/types/openconfig-inet-types.yang
- tools/internal/ocpaths/testdata/models/oc-models/types/openconfig-types.yang
- tools/internal/ocpaths/testdata/models/oc-models/types/openconfig-yang-types.yang
- tools/nosimage/README.md
- tools/nosimage/example/example_nosimageprofile.textproto
- tools/nosimage/example/example_nosimageprofile_invalid.textproto
- tools/nosimage/example/generate_example.go
- tools/nosimage/validate/validate.go
**Limitation**: Validator script currently only validates OCPaths, and not RPCs.
Tested generator manually:
```
go run validate/validate.go -file example/example_nosimageprofile.textproto; rm -rf public
```
```
go run validate/validate.go -file example/example_nosimageprofile_invalid.textproto; rm -rf public
```
> Example nosimage.textproto and validator script.

- feature/gribi/mplsutil/mplsutil.go
- feature/gribi/otg_tests/mpls_compliance/gribi_mpls_compliance_test.go
- feature/gribi/otg_tests/mpls_compliance/metadata.textproto
- feature/gribi/otg_tests/mpls_forwarding/gribi_mpls_forwarding_test.go
- feature/gribi/otg_tests/mpls_forwarding/metadata.textproto
```
- Fix error in `gribi/mpls_compliance`, add EOS deviations.
- Fix label assingmentas in MPLS forwarding test.
```
Note that these tests should be run with a reset so that gRIBI starts with
acquiring a new election ID.
> Minor fixes for gRIBI MPLS tests.

- feature/interface/aggregate/otg_tests/aggregate_forwarding_viable_test/metadata.textproto
put deviations under one platform exception per vendor
> Fix metadata.textproto changed from PR 2461

- feature/interface/ip/ipv6_link_local/otg_tests/ipv6_link_local_test/README.md
Add traffic verification when both a global and link local address are configured.
> Update ipv6 link local test -  Add traffic to subtest 3

- feature/system/gnmi/metadata/tests/large_set_consistency_test/metadata.textproto
Test uses 2 ports. This allows run this test to run without explicitly calling the `--testbed` (to point to a 2port testbed file) flag. 
> Changed testbed file for gNMI-1.14

- feature/platform/fabric/otg_tests/sampled_backplane_capacity_counters_test/README.md
As per correct definitions:
- ```consumed-capacity``` is the sum of the admin-up front panel interface speeds connected to the integrated-circuit
- ```available-percent``` is ```total-operational-capacity / consumed-capacity``` client will subscribe ```ON_CHANGE``` to available-percent and take action if available-percent < 100
Updating the tests to validate that gNMI subscribe with SAMPLE and ON-CHANGE mode works as intended for the paths
*   /components/component/integrated-circuit/backplane-facing-capacity/state/available-pct
*   /components/component/integrated-circuit/backplane-facing-capacity/state/consumed-capacity
*   /components/component/integrated-circuit/backplane-facing-capacity/state/total
*   /components/component/integrated-circuit/backplane-facing-capacity/state/total-oper …
> Updating the tests to validate subscribe with on-change mode works as intended

- testregistry.textproto
Updated the test case number for IPv6 ND RA disable to RT-9 based on the comment in pull/2485
> Updated the test case id number for IPv6 ND RA disable.

- feature/staticroute/static_route_support/README.md
- testregistry.textproto
- Static route ECMP must be supported
- Static route metric must be supported
- Static route Administrative Distance / Preference must be supported
- ```set-tag``` attribute must be supported for static routes
- Disabling recursive nexthop resolution must be supported
Only for IPv4 static route with IPv4 next hop and Ipv6 static route for IPv6 next Hop
ISSUE: https://github.com/openconfig/featureprofiles/issues/2489
> Static route support readme

- feature/interface/singleton/otg_tests/singleton_test/README.md
https://github.com/openconfig/featureprofiles/issues/2338
> Interface breakout configuration and removal test

- .github/workflows/go.yml
The latest release tag on revive has a problem that breaks `go install`.  Issue is tracked in mgechev/revive#956 - it seems like the bug is fixed but there isn't a new release tag with the fix yet.  This change will pin the older working version.
> Pin revive CI check to v1.3.4

- feature/sflow/otg_tests/sflow_base_test/metadata.textproto
Adding deviation `static_protocol_name` to metadata.textproto.
> SFLOW-1.1: Updating metadata with static_protocol_name deviation

- topologies/binding/binding.go
should point to `ateSvcParams` not `dutSvcParams`
> Fix GRPC timeout for OTG

- internal/security/svid/svid.go
openssl 3.X defaults to PKCS8
This prevents the requirement to use openssl 1.x or migrate certs from PKCS8->PKCS1
Using `PRIAVE KEY` as case since the preamble is `-----BEGIN PRIVATE KEY-----` "This code is a Contribution to the OpenConfig Feature Profiles project ("Work") made under the Google Software Grant and Corporate Contributor License Agreement ("CLA") and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia's intellectual property are granted for any other purpose. This code is provided on an "as is" basis without any warranties of any kind."
> Adding PKCS8 to LoadKeyPair()

- feature/isis/static-route_isis_redistribution/README.md
- testregistry.textproto
https://github.com/openconfig/featureprofiles/issues/2494
- Static metric to ISIS Extended IP Reachability / IPv6 IP Reachability (TLV135 / TLV236)
- Redistribution to ISIS L2
- Static routes selected for redistribution base on combination of prefix-set and set-tag
- ISIS wide metric set to value of metric of static route (metric propagation)
> Static route redistribution to IS-IS readme

- feature/system/tests/system_base_test/g_protocol_test.go
- topologies/binding/options.go
fix dialer to call the svc (was hardcoded to gNMI) fix gRIBI iana port to 9340
> Fix for system_base_test

- .gitattributes
- feature/experimental/replay/tests/diff_command_trees/diff_command_trees_test.go
- feature/experimental/replay/tests/diff_command_trees/grpclog.pb
- feature/experimental/replay/tests/p4rt_replay/grpclog.pb
- feature/experimental/replay/tests/p4rt_replay/p4rt_replay_test.go
- feature/experimental/replay/tests/presession_test/grpclog.pb
- feature/experimental/replay/tests/presession_test/presession_test.go
Storing the files in a public cloud storage bucket prevents the messiness of keeping them in the git repo while ensuring the file is accessible by the test both in open source and when running internally.
> Move binary logs to google cloud object storage

- feature/bgp/bgp_isis_redistribution/README.md
- testregistry.textproto
- Source-protocol: BGP, destination-protocol: ISIS L2
- Using Community (Source-protocol: BGP)
- Using defined prefix set
https://github.com/openconfig/featureprofiles/issues/2570
> RT-1.28: BGP to IS-IS redistribution

- feature/experimental/gribi/otg_tests/backup_nhg_action/backup_nhg_action_test.go
The fix to address below error 
"Error occurred while setting Traffic config for user common:Total tracking bits configured for port \\\"port2\\\" is 13, which exceeds max value of 12; check trackings [ipDstTracking ipSrcTracking],\"\n ]\n}
There is a limitation of tracking bits for ixia-c in KNE environment, depending on the number of flows (as ^2) the tracking bits will be used up. So, updated the test to work seamlessly with ixia-c in KNE and OTG-Hw
> OTG TE11.3 Update Flow tracking bits from 12 to 10 & removed deviation ATEPortLinkStateOperationsUnsupported

- feature/bgp/static-route_bgp_redistribution/README.md
- testregistry.textproto
- Static routes selected for redistribution base on combination of: prefix-set, set-tag
- MED set to value of metric of static route (metric propagation)
- AS-Path set to contain one AS with value provided in configuration
- Local-Preference to a value provided in configuration
- Community list set to defined community set
- BGP protocol next-hop set to value provided in configuration
- Redstribute static-route with "DROP" as the next-hop
https://github.com/openconfig/featureprofiles/issues/2568
> Static route to BGP redistribution

- feature/bgp/policybase/otg_tests/3level_nested_policies/README.md
- testregistry.textproto
- AS-path prepending by more the 10 repetitions
- Recursive policy subroutines (multi-level nesting). At least 3 levels
- match-set-options of ANY, INVERT for match-prefix-set conditions
- Applicable to both IPv4 and IPv6 BGP neighbors
https://github.com/openconfig/featureprofiles/issues/2612
>  RT-1.31: BGP 3 levels of nested import/export policy with match-set-options

- feature/bgp/policybase/otg_tests/chained_policies/README.md
- testregistry.textproto
- A list of policies to be attached to a neighbor's import-policy
- A list of policies to be attached to a neighbor's export-policy
https://github.com/openconfig/featureprofiles/issues/2594
> RT-1.29 BGP chained policies README

- feature/bgp/policybase/otg_tests/nested_policies/README.md
- testregistry.textproto
- A policy calling another policy to be attached to a neighbor's import-policy
- A policy calling another policy to be attached to a neighbor's export-policy
- Applicable to both IPv4 and IPv6 BGP neighbors
- Single level nesting is sufficient
https://github.com/openconfig/featureprofiles/issues/2608
> RT-1.30: BGP nested import/export policy attachment

- feature/bgp/policybase/otg_tests/aspath_and_community_test/README.md
- feature/bgp/policybase/otg_tests/aspath_and_community_test/metadata.textproto
- feature/bgp/policybase/otg_tests/aspath_test/README.md
- feature/bgp/policybase/otg_tests/aspath_test/metadata.textproto
- feature/bgp/policybase/otg_tests/community_test/README.md
- feature/bgp/policybase/otg_tests/community_test/metadata.textproto
- feature/bgp/policybase/otg_tests/default_policies_test/README.md
- feature/bgp/policybase/otg_tests/default_policies_test/bgp_default_policies_test.go
- feature/bgp/policybase/otg_tests/default_policies_test/metadata.textproto
- testregistry.textproto
* Renumbered existing readmes (and two test automations) to  move BGP policy related tests into RT-7.x numbering.
* Updated metadata.textproto where present to match
* Added testregistry entry for RT-7.9: BGP Policy - Import/Export Policy Action Using Communities
* RT-7.9 README will appear in a future PR
> move bgp policy tests to rt-7.x

- feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
Modifies TE-3.7 to make sure default NI name is configured when configuring protocols.
> TE-3:7: make sure ni key 'name' is configured

- tools/ci-trigger/cloudbuild.go
Previous change #2647 got the formatting of the service account field wrong; the Cloud Build API wants it in the format `projects/[ACCOUNT]/serviceAccounts/[USER_NAME]` instead of simply the username string.
> Update ci-trigger service account formatting

- feature/interface/singleton/otg_tests/singleton_test/singleton_test.go
Changing the counter for drop variable to use in-errors leaf instead of in-discards.
As per OC definition/rfc2863, 
in-discards packets are number of inbound packets that were chosen to be discarded even though no errors had been detected to prevent their being deliverable to a higher-layer protocol
& in-errors packets are he number of inbound packets that contained errors preventing them from being deliverable to a higher-layer protocol.
So, the for Packets with size > MTU should be increment the interface error counters.
> RT-5.1 change from in-discards to use in-errors for drop

- feature/interface/ip/ipv6_link_local/otg_tests/ipv6_link_local_test/ipv6_link_local_test.go
```
* (M) feature/interface/ip/ipv6_link_local/otg_tests/ipv6_link_local_test
- Add check for
`/interfaces/interface/subinterfaces/subinterface/ipv6/{config,state}/enabled
in link local test. This validates that the config and state
indicating that IPv6 is enabled on an interface is properly
updated and reflected.
```
> Add check of IPv6 enabled leaf to `ipv6_link_local_test`.

- topologies/binding/binding.go
- topologies/binding/binding_test.go
- topologies/binding/options.go
- topologies/binding/options_test.go
* Make the logic more easy to read and straightforward as to what dimensions its matching
* Reduce use of the ambiguously named "resolver" type
* Add TODOs to remove the copying of testbed values to bound values
> Simplify and improve binding dimension logic

- feature/gribi/encap_frr/README.md
The backup next hop group that specifies the fallback to default is currently missing from the gRIBI that specifies the encap and frr actions.
> [TE-16.2] Include backup NHG for REPAIRED tunnels

- feature/gnoi/os/tests/osinstall/metadata.textproto
The test still fails due to some recently added strict expectations in the test but, the deviations are needed nevertheless. There is an open discussion about the other test issues causing the test to fail.
> Adding applicable deviations for Arista to os_install test metadata.textproto file

- topologies/binding/binding.go
- topologies/binding/binding_test.go
DO NOT SUBMIT until 2/26/24.
This is a necessary step to unblock dynamic reservation for the static FP binding.
> Stop copying testbed dimensions to bound dimensions

- CONTRIBUTING.md
- README.md
- feature/bgp/policybase/otg_tests/actions-MED_LocPref_prepend_flow-control/actions_MED_LocPref_prepend_flow_control_test.go
- tools/check_ip_addresses.pl
* Add a WARNING that users who run the test own the responsibility of not leaking test traffic to internet.
* Add `100.64.0.0/10`, a non-globally routable CGN range, which usually is used inside service providers. https://www.iana.org/go/rfc6598.
* Correct the name of `198.18.0.0/15` to `Device Benchmark Testing` (RFC 2544).
* Removed other "arbitrary" IP ranages, we'd like to deprecate them from the tests.
* Update IP check script accordingly.
Formatting:
* Simplify the wording in the `IP Addresses Assignment` section.
> Update IP assignment guidance

- internal/security/authz/authz.go
- internal/security/gnxi/rpcexec.go
Alias imports of protobufs in packages to {package}pb instead of using the default name.  This makes it significantly easier to manage copybara/bazel builds because generated code follows different naming patterns in that world.
All other protobuf imports in this repo follow this pattern already.
> Alias protobuf package imports

- cloudbuild/virtual.yaml
Virtual device tests will sometimes hang on the "setup" phase.  An example can be seen in #2731 - the logs will show the following when trying to connect to the KNE instance:
```
ERROR: (gcloud.compute.ssh) INVALID_ARGUMENT: Login profile size exceeds 32 KiB. Delete profile values to make additional space.
```
This is because the remote-builder container generates a new SSH key each time which gets cached into the cloud build service account profile (related to OS Login enforcement).  This was previously mitigated by #298 by adding key expiration, however this is still a problem if too many tests run in a 24-hour window.  Very short timeouts did not work well because `gcloud compute scp...` would not refresh the keys similar to how `gcloud compute ssh...` would.
This change eliminates the …
> Update virtual device testing CI SSH key

- feature/bgp/policybase/otg_tests/comm_match_action_test/metadata.textproto
- feature/bgp/policybase/otg_tests/extcomm_action_test/metadata.textproto
- tools/wikidoc/wikidoc.go
```
* (M) tools/wikidoc/wikidoc.go
- Make wikidoc report what file it failed to parse.
* (M) feature/bgp/policybase/otg_tests/comm_match_action_test/metadata.textproto
* (M) feature/bgp/policybase/otg_tests/extcomm_action_test/metadata.textproto
- Fix missing [] to indicate a list of tags.
```
> Fix incorrect textproto syntax in metadata.

- internal/cfgplugins/staticroute.go
Updating batch configuration to configure static protocol along with static-route prefix item config.
This change is used by script - https://github.com/openconfig/featureprofiles/blob/213058e930e0b7d75a84a9093838a70ae43a5f25/feature/sflow/otg_tests/sflow_base_test/sflow_base_test.go#L127
> SFLOW-1: static-route configuration need static protocol configuration.

- .github/workflows/go.yml
- .github/workflows/protobufs.yml
- .github/workflows/wiki.yml
staticcheck was failing with container disk full in [some PRs](https://github.com/openconfig/featureprofiles/actions/runs/8169538025/job/22333812800):
```
Run GOGC=30 staticcheck ./...
-: # github.com/openconfig/featureprofiles/feature/qos/tests/qos_ecn_config_test_test [github.com/openconfig/featureprofiles/feature/qos/tests/qos_ecn_config_test.test]
compile: writing output: write $WORK/b1526/_pkg_.a: no space left on device (compile)
-: # github.com/openconfig/featureprofiles/feature/qos/tests/qos_policy_config_test_test [github.com/openconfig/featureprofiles/feature/qos/tests/qos_policy_config_test.test]
compile: writing output: write $WORK/b1528/_pkg_.a: no space left on device (compile)
...
```
In the run log for the last time [go.sum …
> Remove restore-keys from Github Actions

- .github/workflows/go.yml
Some PRs were still having issues with staticcheck and disk usage (#2202 ([link](https://github.com/openconfig/featureprofiles/actions/runs/8196457547/job/22416721843)), #2718 ([link](https://github.com/openconfig/featureprofiles/actions/runs/8205704582/job/22443163513?pr=2718))).  This change moves the cache directory to the sdb1 partition at /mnt. Previously everything would go into / and the disk would fill up.
Disk usage after staticcheck runs on an example large run:
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        73G   39G   34G  54% /
tmpfs           7.9G  172K  7.9G   1% /dev/shm
tmpfs           3.2G  1.1M  3.2G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sda15      105M  6.1M   99M   6% /boot/efi
/dev/sdb1        74G   30G   40G  44% /mnt …
```
> staticcheck CI: Move cache directory to scratch disk partition

- feature/bgp/policybase/otg_tests/community_test/README.md
This is documentation clean up and brings the readme in sync with the test code
> Fix references to community-set in RT-7.2

- feature/gribi/otg_tests/basic_encap_test/metadata.textproto
TE-16.1 requires 5 DUT-TGEN ports, so changed testbed metadata field to use TESTBED_DUT_ATE_8LINKS
> TE-16.1 | Changed testbed metadata field to use 8 link testbed

- feature/gribi/otg_tests/basic_encap_test/basic_encap_test.go
The test is passing now the following changes
- Increase the number of flows from 1000 to 10000
- Randomize the source/dst port set in the UDP header of the pacKet flows
- Enable the extended hashing feature in EOS by setting the right TCAM profile configuration in startup configuration
> Fix basic_encap_test failure due to unexpected traffic distribution ratio

- feature/experimental/gribi/otg_tests/vrf_policy_driven_te/metadata.textproto
- feature/experimental/gribi/otg_tests/vrf_policy_driven_te/vrf_policy_driven_te_test.go
- Add static route to a special fictitious IP address pointing to all TE egress interfaces
- Add static arp entries to the fictitious IP address pointing to the magic mac address
- Publish GRIBI AFT entries with fictitious IP address in the nexthop AFT entry
> Add Arista specific deviation for TE-17.1 (VRF selection policy driven TE)

- feature/system/management/metadata.textproto
This file looks like it was moved to `feature/system/management/otg_tests/management_ha_test/metadata.textproto` but the old file was not removed.
> Remove stray metadata.textproto

- feature/gribi/otg_tests/static_lsp/README.md
- testregistry.textproto
fixing duplicate test id issue for mpls forwarding static lsp test TE-9.1 -> TE-9.2
> fixing duplicate test id issue for mpls forwarding static lsp test

- feature/bgp/policybase/otg_tests/nested_policies/nested_policies_test.go
There needs some changes in the original script to make this testcase work. Below are captured at high level changes to script in the original script.
1. comment 180-183 as verification is done before applying the policy
2. line no 271, 337, 422, 487 needs modification from GetConditions() to GetorCreateConditions()\
for example line no 271\
statPath := rpPolicy.GetOrCreatePolicyDefinition(v4LPPolicy).GetStatement(v4LPStatement).GetConditions() \
to be corrected to\
statPath := rpPolicy.GetOrCreatePolicyDefinition(v4LPPolicy).GetStatement(v4LPStatement).GetorCreateConditions()
3. line no 278,429 policy.SetDefaultExportPolicy(oc.RoutingPolicy_DefaultPolicyType_REJECT_ROUTE) needs to be commented out as defaultexportpolicy is failing due to the the error An unexpected element "enabled" is …
> Fixing RT 1.30 Nested Policy Test

- doc/test-requirements-template.md
This changes the requirement for featureprofiles test READMEs to format OC path and RPCs from plain text to a structured format (yaml).
This format is intended to be easy for humans who are writing README's for test requirements and may not be a developer.  It is also more simple to maintain the path list with the test which is using the paths versus today's practice where the path is listed in a readme and in feature.textproto files.  To keep feature.textproto files accurate, they must be manually kept in sync with README's from multiple tests across potentially many child folders with multiple levels.  In addition the feature.textproto files lack the ability to indicate which tests are intended to cover a path.  It is useful to know which test(s) a path is intended to cover.
The …
> Add yaml for OCPaths/RPC to test README

- feature/platform/tests/telemetry_inventory_test/telemetry_inventory_test.go
Changed parent type validation to use lookup instead of get.
Some of the parent component may not map to any of identity types defined under OPENCONFIG_HARDWARE_COMPONENT, for those components type leaf would not be returned .
> gNMI-1.4 | change parent type validation to use lookup

- feature/system/management/otg_tests/management_ha_test/metadata.textproto
This test won't be used for aggregation at this time
> Remove AGGREGATION tag from MGT-1

- feature/experimental/gribi/otg_tests/vrf_policy_driven_te/metadata.textproto
- feature/experimental/gribi/otg_tests/vrf_policy_driven_te/vrf_policy_driven_te_test.go
The fix adds
- Arista deviation for static protocol name required for static route configuration
- Remove deletion of the policy forwarding parent path and instead do a replace when replacing cluster vrf selection policy with wan vrf selection policy
>    Fix static configuration and vrf selection policy configuration failure in TE-17.1 VRF selection policy driven TE

- feature/gribi/otg_tests/basic_encap_test/basic_encap_test.go
- feature/gribi/otg_tests/basic_encap_test/metadata.textproto
1. added back code to use deviation for default class by using l2 rules
2. added function to generate sequence IDs off a base value to avoid out of order rule sequences in a policy-map configuration.
3. optimized traffic flow generation code
> TE-16.1 Basic Encap Test - fix for using l2 rules and sequenceID

- tools/fpcli/cmd/root.go
- tools/fpcli/cmd/rpc.go
- tools/fpcli/cmd/rpcs.go
- tools/fpcli/cmd/show.go
- tools/fpcli/main.go
- tools/internal/ocrpcs/ocrpcs.go
Example:
```bash
go install ./tools/fpcli
fpcli show rpcs gnoi -d tmp
```
output:
```
gnoi.bgp.BGP.ClearBGPNeighbor
gnoi.bootconfig.BootConfig.GetBootConfig
gnoi.bootconfig.BootConfig.SetBootConfig
gnoi.certificate.CertificateManagement.CanGenerateCSR
gnoi.certificate.CertificateManagement.GenerateCSR
gnoi.certificate.CertificateManagement.GetCertificates
gnoi.certificate.CertificateManagement.Install
...
...
...
```
> Helper CLI tool initially for listing all OC RPCs for easy browsing

- feature/interface/ip/ipv6_link_local/otg_tests/ipv6_link_local_test/README.md
- feature/interface/ip/ipv6_link_local/otg_tests/ipv6_link_local_test/ipv6_link_local_test.go
Update configureDUTLinkLocalInterface() to enable ipv4 if InterfaceEnabled deviation exists and ipv4 is not enabled,
> RT-5.8: Update configureDUTLinkLocalInterface()

- feature/bgp/policybase/otg_tests/prefix_set_test/bgp_prefix_set_test.go
- feature/bgp/policybase/otg_tests/prefix_set_test/metadata.textproto
Value for deviation flag `default_import_export_policy` is set to `false` in the metadata file, and default value for vendor not using this deviation is also `false`.
Due to this `else` part of the code which does not need this deviation never gets executed. Also restoring the original prefix count value applicable for non-deviation scenario.
“This code is a Contribution to the OpenConfig Feature Profiles project (“Work”) made under the Google Software Grant and Corporate Contributor License Agreement (“CLA”) and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia’s intellectual property are granted for any other purpose. This code is provided on an “as is” basis without any warranties of any kind.”
> RT-1.33: Fixing value for deviation flag

- feature/experimental/isis/otg_tests/lsp_updates_test/metadata.textproto
Remove isis_interface_level1_disable_required deviation for RT-2.2 is-is test
> RT-2.2 | Remove isis_interface_level1_disable_required deviation

- feature/aft/aft_summary/otg_tests/route_summary_counters_test/route_summary_counters_test.go
RT-4.10 Use Await to check for route summary to avoid flakiness in test runs
```
--- PASS: TestRouteSummaryWithISIS (42.62s)
...
--- PASS: TestRouteSummaryWithBGP (49.53s)
--- PASS: TestRouteSummaryWithBGP/propagate_IPv4_over_IPv4 (26.23s)
--- PASS: TestRouteSummaryWithBGP/propagate_IPv6_over_IPv6 (23.30s)
```
> RT-4.10 Use Await to check for route summary

- feature/bgp/policybase/otg_tests/import_export_multi_test/import_export_multi_test.go
I have replaced GetSetCommunity with GetOrCreateSetCommunity , other script will fail with panic error.
Also gnmi.update is needed  instead of gnmi.replace, since protocol is still pointing to routing policy.
> RT-7.11  : import_export_multi_test.go

- feature/platform/healthz/tests/status/README.md
- feature/platform/healthz/tests/status/metadata.textproto
- testregistry.textproto
Adds README for test requirements covering the OC paths related to healthz
> Health-1.2 - Healthz component status paths README

- feature/bgp/policybase/otg_tests/prefix_set_test/README.md
- feature/bgp/policybase/otg_tests/prefix_set_test/bgp_prefix_set_test.go
- feature/bgp/policybase/otg_tests/prefix_set_test/metadata.textproto
- internal/helpers/helpers.go
Made below changes to the test
- Change AS# for Port2 DUT-ATE BGP sessions for routes to be advertised to that eBGP Peer , same AS wont work due to AS PATH loop prevention.
- Added soft reconfiguration inbound CLI with MissingPrePolicyReceivedRoutes deviation for pre-policy routes
- Increase timeouts in watch in validatePrefixCount to account for default sample interval with gnmi target-defined sub
> RT-1.33 changes

- feature/platform/transceiver/tests/zr_tunable_parameters_test/README.md
- feature/platform/transceiver/tests/zr_tunable_parameters_test/zr_tunable_parameters_test.go
* Configured frequency should be streamed in the `/state/` path even when the interface is DOWN.
> Update zr tunable parameters test plan and fix test

- feature/platform/transceiver/tests/zr_supply_voltage_test/zr_supply_voltage_test.go
Bring interface back up at the end of the port test
> FDix zr_supply_voltage_test

- feature/bgp/policybase/otg_tests/default_policies_test/README.md
- feature/bgp/policybase/otg_tests/default_policies_test/bgp_default_policies_test.go
- feature/bgp/policybase/otg_tests/default_policies_test/metadata.textproto
the diff contains the following changes to make the test pass for
Arista
- Add "bgp_default_policy_unsupported" deviation for Arista since default bgp policy action will not be applied for prefixes that do not match on any condition in an inbound/outbound policy applied for a given neighbor.
- Fix the "configureRoutingPolicyDefaultAction()" to not create raw json object to create the default accept/reject rule in the policy when "bgp_default_policy_unsupported" is present.
- set mode if the prefix-set definition ( which is a requirement for arista ) for the prefix-set to be applied on a policy
- Fix another issue for 7.1.3 and 7.1.4 case to make sure the prefix-set match condition is deleted before applying the default accept/deny rule
>    Fix RT-7.1: BGP default policies test for Arista

- feature/system/ntp/tests/system_ntp_test/metadata.textproto
- feature/system/ntp/tests/system_ntp_test/system_ntp_test.go
Made below changes:
- Remove deviation 
- In verification for ntpServer NI , right now got and want are switched, so fixed it.
> OC-26.1 | remove deviation and fix verification 

- feature/bgp/policybase/otg_tests/default_policies_test/bgp_default_policies_test.go
- feature/bgp/policybase/otg_tests/default_policies_test/metadata.textproto
fix bgp_default_policies_test.go to work on Cisco, Nokia, Arista
* fix isis configuration for cisco
* fix the configuration when default policy is not supported 
* Add skip_prefix_set_mode in textproto for nokia
* add missing_isis_interface_afi_safi_enable,  bgp_default_policy_unsupported, prepolicy_received_routes deviation for cisco
> fix bgp_default_policies_test.go

- feature/bgp/policybase/otg_tests/import_export_multi_test/import_export_multi_test.go
- feature/bgp/policybase/otg_tests/import_export_multi_test/metadata.textproto
* Delete PERMIT-ALL policy applied to neighbor
* Add native command for community member regex match
* Add deviations:
bgp_conditions_match_community_set_unsupported: true
bgp_community_set_refs_unsupported: true
community_member_regex_unsupported: true
skip_setting_statement_for_policy: true
default_route_policy_unsupported: true
> fix import_export_multi_test for cisco

- feature/bgp/multipath/otg_tests/bgp_multipath_wecmp_lbw_community_test/bgp_multipath_wecmp_test.go
- feature/bgp/multipath/otg_tests/bgp_multipath_wecmp_lbw_community_test/metadata.textproto
1. Added below deviations as the OC path for MultipleAS is not supported under the AFI_SAFI_Path.
'skip_setting_allow_multiple_as'
'skip_afi_safi_path_for_bgp_multiple_as'
2. Added dmz related command for the peer-group
'ebgp-recv-extcommunity-dmz'
'ebgp-send-extcommunity-dmz'
4. Enabled "maximum-paths ebgp" under the BGP neighbor AFI/SAFI address-family
> fix link bandwidth with deviations

- feature/bgp/policybase/otg_tests/comm_match_action_test/bgp_comm_match_action_test.go
send-community-type is missing in the configuration
> RT-7.8: Configure send-community-type

- feature/platform/tests/optics_power_and_bias_current_test/metadata.textproto
Since Transceiver thresholds are now supported on Juniper platform, removing the transceiver_thresholds_unsupported deviation for Juniper.
> gnmi-1.13: Optics Power And Bias Current Test Deviation removal

- feature/platform/tests/telemetry_inventory_test/README.md
- feature/platform/tests/telemetry_inventory_test/telemetry_inventory_test.go
If a component has either `components/component/subcomponents/subcomponent/name` or `components/component/subcomponents/subcomponent/state/name`, then the leafref value of this path should be for a component that exists on that device.
> Update gNMI-1.4 to validate subcomponents paths.

- feature/experimental/gribi/otg_tests/route_addition_during_failover_test/metadata.textproto
- feature/experimental/gribi/otg_tests/route_removal_during_failover_test/metadata.textproto
- feature/experimental/gribi/otg_tests/vrf_policy_driven_te/metadata.textproto
- feature/experimental/policy/policy_vrf_selection/otg_tests/base_vrf_selection/README.md
- feature/experimental/policy/policy_vrf_selection/otg_tests/base_vrf_selection/metadata.textproto
- feature/experimental/policy/policy_vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/README.md
- feature/experimental/policy/policy_vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/metadata.textproto
- feature/gribi/otg_tests/encap_decap_scale/metadata.textproto
- feature/gribi/otg_tests/gribi_scaling/metadata.textproto
- feature/gribi/otg_tests/hierarchical_weight_resolution_pbf_test/metadata.textproto
- feature/gribi/otg_tests/hierarchical_weight_resolution_test/README.md
- feature/gribi/otg_tests/hierarchical_weight_resolution_test/metadata.textproto
Changes to remove the 'deprecated_vlan_id' deviation from metadata.proto as it is no longer required now
> Changes to remove the 'deprecated_vlan_id' deviation from metadata.proto

- feature/bgp/static_route_bgp_redistribution/otg_tests/static_route_bgp_redistribution_test/README.md
NOTE: default-import-poilicy is set to reject_route by default and is tested in this FNT
Reordering steps and removing default-import-poilicy to be set to accept.
Using an explicit route-map to override default-import-poilicy set to reject route
> Reordering readme steps and fixing issues with default-import-policy

- feature/platform/integrated_circuit/otg_tests/utilization_test/README.md
- feature/platform/integrated_circuit/otg_tests/utilization_test/utilization_test.go
As discussed in internal bug b/281931161#comment37, removing 
* /components/component/integrated_circuit/utilization/resources/resource/state/used-threshold-upper
* /components/component/integrated_circuit/utilization/resources/resource/state/used-threshold-upper-clear
> gNMI-1.21 - Remove threshold state validation for /components OC path

- testregistry.textproto
Add Test# for:
1. BGP route-refresh capability
2. Support for MP-BGP w/ Multiple AFI-SAFI Tuples on a single neighborship
> Update testregistry.textproto for BGP route-refresh test

- internal/vrfpolicy/vrfpolicy.go
Please note that the test is still continuing to fail at a later point in our internal testbed with the following error
encap_frr_test.go:1122: SetControlState(t) on ATE{Dims:Dims{Name:google-ondatra-keng:40051 Vendor:VENDOR_UNSPECIFIED HardwareModel: SoftwareVersion: Ports:map[port1:Port{Name:ixas120/89 Speed:SPEED_UNSPECIFIED CardModel: PMD:PMD_UNSPECIFIED} port2:Port{Name:ixas120/90 Speed:SPEED_UNSPECIFIED CardModel: PMD:PMD_UNSPECIFIED} port3:Port{Name:ixas120/91 Speed:SPEED_UNSPECIFIED CardModel: PMD:PMD_UNSPECIFIED} port4:Port{Name:ixas120/92 Speed:SPEED_UNSPECIFIED CardModel: PMD:PMD_UNSPECIFIED} port5:Port{Name:ixas120/93 Speed:SPEED_UNSPECIFIED CardModel: PMD:PMD_UNSPECIFIED} port6:Port{Name:ixas120/94 Speed:SPEED_UNSPECIFIED CardModel: PMD:PMD_UNSPECIFIED} …
> Fix encap_frr tests to add the network instance for REPAIR_VRF

- feature/platform/tests/telemetry_inventory_test/telemetry_inventory_test.go
For some components, they don't have subcomponents such as 'Storage' and some 'SENSOR'.
In the existing validations, it always assumes the subcomponent exists for all the components.
Therefore, skip validating the subcomponent's existance and  name if component doesn't have it.
> gNMI-1.4: Skip subcomponent check if subcomponent doesn't exist

- feature/platform/tests/telemetry_inventory_test/metadata.textproto
- feature/platform/tests/telemetry_inventory_test/telemetry_inventory_test.go
adding deviation to skip power-admin-state for controllers
---
> gNMI-1.4 deviation addition

- feature/gribi/otg_tests/basic_encap_test/basic_encap_test.go
The test incorrectly expects the encapsulated egress packet to have a TTL value of 0. But the expectation should be to have a TTL value  = ingress pkt's TTL - 1 ( accounting for the TTL decrement on the encapsulating router ).  The fix changes the expected TTL value to reflect this behavior
> Fix basic_encap_test failure due to incorrect TTL validation in the test

- feature/qos/otg_tests/ingress_traffic_classification_and_rewrite_test/README.md
These qos features are not inherently dependent on FFF vs. MFF devices.  So the minimum platform to be used is FFF.
> DP-1.16: Remove MFF as a requirement

- feature/experimental/policy/otg_tests/prefix_set_test/metadata.textproto
- feature/experimental/policy/otg_tests/prefix_set_test/prefix_set_test.go
- delete pfx2 from var as it was never "replaced" - see below
Before the change, we can see that the var was never replaced and always carried pfx2 which seems to not be the intended behavior by the author.
```
prefix_set_test.go:65: Printing the value after re-assignment, &{out-of-range E_PrefixSet_Mode enum value: 0 0xc001e93e80 map[{10.240.31.48/28 exact}:0xc001e93eb0 {173.36.128.0/20 exact}:0xc001e93ee0]}
prefix_set_test.go:69: Printing the value after L68, &{out-of-range E_PrefixSet_Mode enum value: 0 0xc001e93e80 map[{10.240.31.48/28 exact}:0xc001e93eb0 {173.36.128.0/20 exact}:0xc001e93ee0 {173.36.144.0/20 exact}:0xc002171a90]}
```
- add deviation 
---
<sub>This code is a Contribution to the OpenConfig Feature Profiles project ("Work") made under the Google Software Grant and …
> RT-1.53 fix

- feature/interface/aggregate/otg_tests/aggregate_all_not_viable_test/aggregate_all_not_forwarding_viable_test.go
- feature/interface/aggregate/otg_tests/aggregate_all_not_viable_test/metadata.textproto
1. Corrected use of deviation as per PR-2953 , i.e deviation is need to skip ecmp config . 
2. Modified gnmi Await timeout to 90 seconds to verify ISIS session state , this to accommodated 3 hello packets drop interval 
3. Using LACP System ID as destination MAC in flow creation is not reliable  so changed to get interface MAC  while creating traffic flow. 
4. Added additional check to verify either session DOWN or no adjacencies presence.  
"This code is a Contribution to the OpenConfig Feature Profiles project ("Work") made under the Google Software Grant and Corporate Contributor License Agreement ("CLA") and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia's intellectual property are granted for any other purpose. This code is provided on an "as …
> corrected deviation usage and  isis await timeout

- feature/lldp/ate_tests/core_lldp_tlv_population_test/README.md
- feature/lldp/ate_tests/core_lldp_tlv_population_test/core_lldp_tlv_population_test.go
- feature/lldp/otg_tests/core_lldp_tlv_population_test/README.md
- feature/lldp/otg_tests/core_lldp_tlv_population_test/core_lldp_tlv_population_test.go
use `GetOrCreate()` for lldp interface configs
ref b/358044619
---
> RT-6.1 Fix

- feature/platform/tests/telemetry_inventory_test/metadata.textproto
This deviation was added in #3046 likely by mistake, hence removing it once again. 
---
<sup>
> gnmi-1.4: fix deviations for nokia

- feature/gribi/otg_tests/supervisor_failure_test/supervisor_failure_test.go
`validateTelemetry()` was incorrectly assuming the newly active had a last-reboot-reason. Fetching the reboot-related queries from new-standby. 
ref: b/352496075
---
> TE-8.2 fix telemetry fetching for standby

- feature/experimental/bgp/ate_tests/bgp_long_lived_graceful_restart/bgp_long_lived_graceful_restart_test.go
- feature/experimental/gribi/otg_tests/dut_daemon_failure/dut_daemon_failure_test.go
- feature/experimental/policy/otg_tests/prefix_set_test/prefix_set_test.go
- feature/p4rt/otg_tests/p4rt_daemon_failure_test/p4rt_daemon_failure_test.go
- internal/gnoi/gnoi.go
1. PR- 3376 changes changed the signal type to KILL instead of TERM  that resulted to non graceful application restart , fixed by adding that as an parameter to the  KillProces() function.
2. Also, added parameter option for restart after kill to have more flexibility  
"This code is a Contribution to the OpenConfig Feature Profiles project ("Work") made under the Google Software Grant and Corporate Contributor License Agreement ("CLA") and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia’s intellectual property are granted for any other purpose. This code is provided on an "as is" basis without any warranties of any kind."
> fixed the failure that was introduced by PR-3376

- feature/platform/controllercard/tests/port/README.md
The README currently specifies using a 'cpu' type interface, but the correct type is 'management.
> Fix gNMI-1.22 requirement for management port

- internal/gnoi/gnoi.go
hotfix for proc-name -- Ref b/361472906
---
> RT-1.53 - fix process name

- internal/components/components.go
- Corrected the logic to get the opticalComponentName, in accordance with the YANG documentation.
- In the previous logic the code was to get the optical component name by traversing through the parents of the PORT component, this was leading to no results. Hence changed it to find the OPTICAL_CHANNEL comp first and match its parent against HARDWARE_PORT of the interface.
- Current flow :                     PORT <-- TRANSCIEVER <-- OPTICAL_CHANNEL
> Updates to Transceiver-3:zr_firmware_version_test 

- feature/security/gnsi/credentialz/tests/README.md
With the addition of GLOME configuration bits in gnsi credentialz we are adding featureprofiles test case to README.md.
> Adding GLOME featureprofile tests

- internal/fptest/runtests.go
adding 400g zr testbed file to mapping for automatic allocation
---
> adding 400gzr testbed file to tb mapping

- .github/CODEOWNERS
Removing ownership for Policy_forwarding for swetha-haridasula.
> added changes to .github/CODEOWNERS to remove ownership for policy_forwarding

- feature/platform/transceiver/tests/zr_low_power_mode_test/zr_low_power_mode_test.go
-  Changed readme to also accept -40dbm as outputpower in low power mode. As per  https://github.com/openconfig/featureprofiles/tree/main/feature/platform/transceiver/tests/zr_input_output_power_test test -40 dbm is correct value when interface is down.
- Changed the components path to use opticalComponent name instead of using transceiver-name for opticalChannelComponent paths.
- Corrected the logic to get the opticalComponentName, in accordance with the YANG documentation.
In the previous logic the code was to get the optical component name by traversing through the parents of the PORT component, this was leading to no results. Hence changed it to find the OPTICAL_CHANNEL comp first and match its parent against HARDWARE_PORT of the interface.
Current flow : PORT <-- TRANSCIEVER <-- …
> Transceiver13: Changes to zr_low_power_mode test

- feature/interface/aggregate/otg_tests/aggregate_forwarding_viable_test/aggregate_forwarding_viable_test.go
Traffic is sent without waiting for ARP and that is causing for flakiness in result , this change will make sure ARP is resolved
> adding waitForARP to fix flakiness

- feature/security/gnsi/certz/client_certificates/README.md
- feature/security/gnsi/certz/test_data/README.md
- feature/security/gnsi/certz/test_data/cleanup.sh
- feature/security/gnsi/certz/test_data/mk_cas.sh
- feature/security/gnsi/certz/trust_bundle/README.md
Update test_data creation and destruction.
Account for the new requirement to handle 20000 certificates.
Additionally, create a p7b form of the trust-bundle, this will be used in the certz interactions instead of the pem file.
> Issue #3525: Increase test_data and documentation.

- feature/bgp/otg_tests/bgp_afi_safi_defaults/bgp_afi_safi_defaults_test.go
This test is failing with the below errors
1) Leaf 'name' inside the 'config' container must also be set to value 'DEFAULT' to satisfy the leafref constraint on the list key"
2) "'BGP' detected the 'warning' condition 'The address family has not been initialized'"
The changes here would fix the above two errors.
> fix leaf constraint error and address family initialisation error

- feature/gribi/otg_tests/fib_failed_due_to_hw_res_exhaust_test/fib_failed_due_to_hw_res_exhaust_test.go
currently after test is complete OTG retains its config and due to which following tests are failing as fib is full and not able to install any more routes.  added defer function to stop BGP protocol that will clear all routes injecected .
> Added defer function to cleanup fib table

- internal/deviations/deviations.go
Do not reach into a snake pit without first checking if snakes in pit! Patterns like:
```
pb "myprotofile"
...
var f pb.Foo
snakesBhere := f.THINGS.N.Snakes
```
get you a panic().
Let's not do that, ok?
> [Issue:3569] Do better about reaching into proto structs.

- feature/security/gnsi/acctz/tests/record_subscribe_full/record_subscribe_full_test.go
- feature/security/gnsi/acctz/tests/record_subscribe_non_grpc/record_subscribe_non_grpc_test.go
- feature/security/gnsi/acctz/tests/record_subscribe_partial/record_subscribe_partial_test.go
- feature/security/gnsi/credentialz/tests/hiba_authentication/hiba_authentication_test.go
- feature/security/gnsi/credentialz/tests/host_certificates/host_certificates_test.go
- feature/security/gnsi/credentialz/tests/password_console_login/password_console_login_test.go
- feature/security/gnsi/credentialz/tests/ssh_password_login_disallowed/ssh_password_login_disallowed_test.go
- feature/security/gnsi/credentialz/tests/ssh_public_key_authentication/ssh_public_key_authentication_test.go
The package name config for each golang test package could have been more specified.
Supposedly this might fix the copy action into google's internal  repository?
> Rename Packages in features/security.

- feature/security/gnsi/acctz/tests/record_history_truncation/record_history_truncation_test.go
- feature/security/gnsi/acctz/tests/record_payload_truncation/record_payload_truncation_test.go
Impossible to have 2 imports with the same name (acctz). 
Follow the standard protobuf import naming standard.
> Separate the imports named acctz, make the PB - acctzpb

- feature/bgp/policybase/otg_tests/link_bandwidth_test/link_bandwidth_test.go
earlier regex matches only single char for bandwidth.  Now it will match any number of chars in the bandwidth portion of the community
> fix linkbw_any regex

- feature/gribi/otg_tests/basic_encap_test/basic_encap_test.go
- feature/gribi/otg_tests/basic_encap_test/metadata.textproto
updated metadata with deviations for nokia
added code to add itnerfaces into default vrf with deviation removed the duplicate append in pbf rules
> updated metadata for nokia with deviations

- feature/bgp/otg_tests/bgp_override_as_path_split_horizon_test/bgp_override_as_path_split_horizon_test.go
Hi,
Fixing issue with route policy, it was commented out in previous git pull.
If we dont add condition install protocol eq to BGP, all direct routes will be installed and sent prefixes does not match.
Thanks,
Prabha
> RT-1.54 bgp_override_as_path_split_horizon_test.go

- feature/platform/tests/telemetry_inventory_test/telemetry_inventory_test.go
- For gnmi-1.4 TestDefaultPowerAdminState subtest changing power-admin-state path to use State leaf.
- By Default LC/FC/Controller cards are POWER_ENABLED, and state leafs return this state.
config leaf would be set when they are POWER_DISABLED.
> gnmi-1.4 | change to use state path for power-admin-state leaf

- .github/CODEOWNERS
```
commit e7aa0b4e6e5baf2b3312d92ad733e0b879b0b452
Author: Rob Shakir <robjs@google.com>
Date:   Tue Dec 17 12:06:46 2024 -0800
Add @morrowc as a security codeowner.
* (M) .github/CODEOWNERS
- annoint @morrowc as a security codeowner.
commit ea2f92bd745fb9170267a5c52c269069309f8d7e
Author: Rob Shakir <robjs@google.com>
Date:   Tue Dec 17 12:04:39 2024 -0800
🧹: housekeeping to ensure well-scoped CODEOWNERS.
* (M) .github/CODEOWNERS
- `s/featureprofiles-maintainers/featureprofiles-approvers/g` to
have a clear group of folks that are the default CODEOWNERS.
```
> 🧹: Clean up `CODEOWNERS` to reflect approvers.

- feature/isis/otg_tests/isis_interface_hello_padding_enable_test/isis_interface_hello_padding_enable_test.go
- feature/isis/otg_tests/isis_interface_hello_padding_enable_test/metadata.textproto
1) Changes to disable only level1 and enable level2
2) Added deviations for DIS and the overload bit
3) Changes for hello padding check such that it checks for ISIS down/init state.
> fixing isis_interface_hello_padding_enable_test

- feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
The test case is checking for the status of various telemetry parameters of LACP and is failing if the traffic is 0 or if member links are down. But is incorrect as these links are not part of testlinks and are management links. Hence changing the errorf function with Logf to lof the value but not fail the case.
> “LACPmemberTelemetry”

- feature/bgp/policybase/otg_tests/route_installation_test/README.md
As per PROCEDURE description below path is needed: `/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-as-path-prepend/config/asn `
This patch is adding it explicitly in "Config Parameter Coverage"
> adding missing path

- feature/platform/transceiver/tests/zr_laser_bias_current_test/zr_laser_bias_current_test.go
- feature/platform/transceiver/tests/zr_low_power_mode_test/zr_low_power_mode_test.go
bug fixes: 1) in zr_laser_bias_current_test file, the time.Duration function returns value in nanosecond by default, needs to convert it to second; 2) in zr_low_power_mode_test file, to use the transceiver disable OC path, the input needs to be transceiver name instead of interface name.
> Bug fixes: 1) time.Duration function wrong unit; 2) transceiver disable OC path

- feature/platform/tests/power_admin_down_up_test/power_admin_down_up_test.go
Added check for the fabrics which are removable
> FP-1.1: Power admin DOWN/UP Test 

- feature/platform/storage/README.md
The README is to verify the below storage OC paths. 
/components/component/storage/state/counters
/components/component/storage/state/counters/soft-read-error-rate
/components/component/storage/state/counters/reallocated-sectors
/components/component/storage/state/counters/end-to-end-error
/components/component/storage/state/counters/offline-uncorrectable-sectors-count
/components/component/storage/state/counters/life-left
/components/component/storage/state/counters/percentage-used
> Create README for Storage-1.1: Storage File System Check

- feature/isis/otg_tests/isis_interface_hello_padding_enable_test/isis_interface_hello_padding_enable_test.go
Below changes were added back as part of PR3658.
1.adding ISISInterfaceAfiUnsupported deviation back
2.adding back the hellopadding related config
> fix collateral from PR3658

- feature/gribi/otg_tests/gribigo_compliance_test/gribigo_compliance_test.go
gribigo_compliance_test.go 
- entries with rib fib ack were not cleaned up
-  Adding defer () function to flush all entries before exit
> Adding defer () function to flush all entries before exit

- feature/bgp/otg_tests/bgp_override_as_path_split_horizon_test/bgp_override_as_path_split_horizon_test.go
Disable add path on ixia since the test does not rely on add path.
> RT-1.54: Remove add path configuration

- feature/platform/transceiver/logical_channels/tests/zrp_logical_channels_test/README.md
- feature/platform/transceiver/logical_channels/tests/zrp_logical_channels_test/metadata.textproto
- feature/platform/transceiver/logical_channels/tests/zrp_logical_channels_test/zrp_logical_channels_test.go
- feature/platform/transceiver/tunable_parameters/tests/zrp_tunable_parameters_test/README.md
- feature/platform/transceiver/tunable_parameters/tests/zrp_tunable_parameters_test/metadata.textproto
- feature/platform/transceiver/tunable_parameters/tests/zrp_tunable_parameters_test/zrp_tunable_parameters_test.go
These two files have the same functional tests as the following two files:
https://github.com/openconfig/featureprofiles/blob/main/feature/platform/transceiver/logical_channels/tests/zr_logical_channels_test/zr_logical_channels_test.go
https://github.com/openconfig/featureprofiles/blob/main/feature/platform/transceiver/tunable_parameters/tests/zr_tunable_parameters_test/zr_tunable_parameters_test.go
Main differences:
1. optics PMD, operational mode, Tx power
2. clean up the codes by using the existing functions of OpticalChannelComponentFromPort and ToggleInterface
3. add OC telemetry type check
> Adding test files for 400G ZR++ logical channel test and tunable parameter test

- feature/bgp/bgp_isis_redistribution/otg_tests/bgp_isis_redistribution_test/bgp_isis_redistribution_test.go
The testcase was waiting for the prefix to exist, but checking for it to NOT exist. It would fail when the prefix hasn't been removed by the time Await() function gets called. The fix is to invert the check and wait for the prefix removal.
> RT-1.28: Invert the verification for removal testcases

- feature/isis/otg_tests/isis_interface_hello_padding_enable_test/metadata.textproto
RT-2.6: Add deviation missing_isis_interface_afi_safi_enable for Arista
> RT-2.6: Add deviation missing_isis_interface_afi_safi_enable

- feature/bgp/otg_tests/bgp_override_as_path_split_horizon_test/bgp_override_as_path_split_horizon_test.go
- feature/isis/otg_tests/isis_interface_hello_padding_enable_test/isis_interface_hello_padding_enable_test.go
bgp_override_as_path_split_horizon_test - Removed install-protocol-eq which is not needed
isis_interface_hello_padding_enable_test - Increasing timeout to avoid flakiness
> AnCX tests correction

- feature/gribi/otg_tests/encap_decap_scale/encap_decap_scale_test.go
Reduce the encap NHG scale to 200 per encap_vrf which brings the total to 800 ( This is the expected scale in DcGate )
> Fix for Encap decap test regression

- feature/platform/transceiver/laser_bias_current/tests/zr_laser_bias_current_test/README.md
- feature/platform/transceiver/laser_bias_current/tests/zrp_laser_bias_current_test/README.md
since they are no longer required
> Remove laser-bias-current avg, min, max from README

- feature/isis/otg_tests/isis_metric_style_wide_not_enabled_test/README.md
- feature/isis/otg_tests/isis_metric_style_wide_not_enabled_test/isis_metric_style_wide_not_enabled_test.go
- feature/isis/otg_tests/isis_metric_style_wide_not_enabled_test/metadata.textproto
- testregistry.textproto
1. Add level 2 related changes in the script
2. disable igp-ldp-sync and making sure the metric is properly set and there is no failures
3. change the metric on the DUT to narrow metric
> add igp-ldp-sync related tests and fix the isis metric

- feature/bgp/otg_tests/bgp_2byte_4byte_asn/bgp_2byte_4byte_asn_test.go
1. Add the AFI-SAFI for IPv6 family at Global level
2. Add fptest.ConfigureDefaultNetworkInstance(t, dut) for installing the default instance
> fix bgp_2byte_4byte_asn for Cisco

- feature/isis/otg_tests/base_adjacencies_test/base_adjacencies_test.go
Explicitly enabling isis level 2 not needed.
> RT-2.1-Fix TestAuthentication

- tools/ci-trigger/Dockerfile
I missed the references to go 1.21 in #3842 for the Dockerfile - this should hopefully fix the build https://github.com/openconfig/featureprofiles/runs/37634960038
```
Step 4/8 : RUN CGO_ENABLED=0 GOOS=linux go build -mod=readonly -v -o server github.com/openconfig/featureprofiles/tools/ci-trigger
193 | ---> Running in 861a72e83c78
194 | go: go.mod requires go >= 1.22.0 (running go 1.21.13; GOTOOLCHAIN=local)
195
```
> Update ci-trigger's Dockerfile to use newest go1.x

- feature/gribi/otg_tests/ipv4_entry_test/ipv4_entry_test.go
Fixing ipv4_entry_test
1. replaced the instance creation using utility fptest
2. few changes in staticARPWithMagicUniversalIP function, gnmi.replace was changed to gnmi.update
> fixing ipv4_entry_test

- feature/bgp/otg_tests/bgp_tcp_mss_path_mtu/bgp_tcp_mss_path_mtu_test.go
Fix the issue with the global AFI-SAFI family initialization for Cisco. Because of this the entire test was failing without execution. Below are the error messages
"error-path": "openconfig-network-instance//[openconfig.net/yang/bgp-types:network-instances/network-instance[name](https://www.google.com/url?q=http://openconfig.net/yang/bgp-types:network-instances/network-instance%5Bname&sa=D) = 'DEFAULT']/protocols/protocol[name = 'BGP' and identifier = 'BGP']/bgp/neighbors/neighbor[neighbor-address = '192.0.2.2']/afi-safis/afi-safi[afi-safi-name = 'ns2:IPV4_UNICAST']/config/enabled",
"error-message": "'BGP' detected the 'warning' condition 'The address family has not been initialized'"
"error-path": "openconfig-network-instance//[openconfig.net/yang/bgp-types:network-instances/network-insta …
> fix bgp_tcp_mss_path_mtu_test for issue with address family initialization

- feature/gribi/otg_tests/gribi_scaling/gribi_scaling_test.go
- feature/gribi/otg_tests/gribi_scaling/metadata.textproto
Removed the deviation block for overrideScaleParams as the feature is delivered.
> Te 14.1 remove cisco deviation

- feature/system/health/tests/system_generic_health_check/metadata.textproto
- feature/system/health/tests/system_generic_health_check/system_generic_health_check_test.go
removing deviations that are not required and adding code for components presence
Includes changes that were done in pull requests 2820 and 2936
> Health 1.1 system_generic_health_check

- feature/isis/otg_tests/isis_drain_test/isis_drain_test.go
- feature/isis/otg_tests/isis_drain_test/metadata.textproto
Made below changes to the RT-2.14 test:
- Add deviation interface_ref_config_unsupported, remove missing_isis_interface_afi_safi_enable
- Explicitly disable igp-ldp-sync enabled leaf.
- This is enabled by default in OC https://github.com/openconfig/public/blob/master/release/models/isis/openconfig-isis.yang#L504
- When this config is enabled and LDP is not active on link, is-is sets max metric to the routes per https://datatracker.ietf.org/doc/html/rfc5443#section-2
- So the metric config changes are not reflected.
> RT-2.14 | Changes to isis drain test

- feature/interface/holdtime/otg_tests/holdtime_test/holddown_timers_test.go
- feature/interface/holdtime/otg_tests/holdtime_test/metadata.textproto
Add deviation for Arista and update Arista specific expected interface states in code.
> RT-5.5 changes

- feature/bgp/otg_tests/bgp_afi_safi_defaults/metadata.textproto
Adding pertinent deviations for the test RT-1.23 for Cisco devices:
skip_bgp_session_check_without_afisafi 
bgp_global_extended_next_hop_encoding_unsupported
> RT-1.23 Cisco deviations.

- feature/bgp/otg_tests/bgp_afi_safi_defaults/metadata.textproto
reverting changes in PR3852 as it was skipping bgp_session_check_without_afisafi
> reverting changes in PR3852 as it was skipping bgp_session_check_without_afisafi

- feature/system/system_base_test/tests/system_g_protocol_test/metadata.textproto
In PR #2855 the commit
https://github.com/openconfig/featureprofiles/commit/87f3397bc322ec35e34a470cd793b070db882e63 made a change to the path being requested when the  connection is being tested. 
Previously an empty GetRequest was being sent, which meant that the GetResponse would also be empty. 
This was changed so that now the test is requesting the root node.
However, its possible that the GetResponse for the root node is larger than the maximum response size for which the client is configured (i.e. the gRPC  default max response size of 4MiB)
To get around this we should run the request to a defined path so that we are guaranteed a small response. The response is ignored anyway, so it doesnt matter what path we request here.
Use the `gnmi_get_on_root_unsupported` introduced in …
> system_base_test: run TestGNMIClient for defined path

- feature/gnmi/subscribe/tests/gnmi_subscriptionlist_test/gnmi_subscriptionlist_test.go
Subscribe requests for the OC paths in cable audit ("batch 1") is timing out and hence adding these coverages for below OC paths in the FNT.
/interfaces/interface[name=%s]/state/oper-status
/interfaces/interface[name=%s]/state/last-change
/interfaces/interface[name=%s]/state/admin-status
/interfaces/interface[name=%s]/state/physical-channel
/interfaces/interface[name=%s]/state/transceiver
> gnmi_subscriptionlist enhancements to add some OC path coverage

- proto/ocpaths.proto
This allows specifying a constraint to assert OC Paths which are restricted to a specific GRPC service. (ie: the use of gnmi, gnsi, gnpsi, gribi in the /system/grpc-servers/grpc-server subtree)
The relevant identity-ref is at `/system/grpc-servers/grpc-server/config/services`
> Add grpc-services constraint to ocpaths.textproto

- feature/bgp/policybase/otg_tests/default_policies_test/bgp_default_policies_test.go
- feature/bgp/policybase/otg_tests/default_policies_test/metadata.textproto
- feature/bgp/policybase/otg_tests/prefix_set_test/bgp_prefix_set_test.go
RT-7.1
1. The test adds bgp_default_policy_unsupported deviation in Arista
2. The initial prefix verification only checks if all the prefixes advertised by otg port 1 is received and advertised to otg port 2 in the absence of import/export routing policies. 
RT-1.33
1. Remove initial prefix validation as it is not mentioned in the README. The test would eventually fail if there is a miss in otg prefix advertisement. 
2. Validate prefixes only on ebgp neighbor 1 after applying import policy on ebgp neighbor 1. Neigbour 2 will anyways be validated after applying the export policy.
> RT-7.1 & RT-1.33-Code and deviation changes

- feature/gribi/otg_tests/encap_decap_scale/encap_decap_scale_test.go
- feature/gribi/otg_tests/ipv4_entry_with_aggregate_ports_test/ipv4_entry_with_aggregate_ports_test.go
- feature/p4rt/tests/metadata_validation_test/metadata.textproto
P4RT-2.2 was failing because the testbedType is wrong in metadata.textproto. This is used to construct the right binding file to use for the test TE-2.2 needs a interlock between shut/unshut of the link and when the traffic is started to validate the traffic.
> Fix P4RT-2.2 and TE-2.2 intermittent test failures for EOS

- feature/platform/transceiver/temperature/tests/zr_temperature_test/metadata.textproto
- feature/platform/transceiver/temperature/tests/zr_temperature_test/zr_temperature_test.go
- Added operationalMode flag & initialized it.
- Using deviation `missing_zr_optical_channel_tunable_parameters_telemetry` as per  https://partnerissuetracker.corp.google.com/issues/334189916
> TRANSCEIVER-8 Fixed with operationalMode inititization

- feature/bgp/policybase/otg_tests/chained_policies_test/chained_policies_test.go
PR 3366 added export policy to satisfy the default behavior of BGP.
For Cisco this is not required as the default behavior of BGP is to reject all routes when there is no policy for the BGP peer. 
Hence removing the changes that is not required.
> Fixing chained_policies_test for the export policy changes PR 3366

- feature/aft/afts_summary/otg_tests/scale_aft_summary/metadata.textproto
- feature/bgp/bgp_session_mode/otg_tests/bgp_session_mode_configuration_test/metadata.textproto
- feature/gribi/otg_tests/gribi_route_test/metadata.textproto
- feature/interface/lacp/tests/lacp_interval_test/metadata.textproto
- feature/mtu/otg_tests/pmtu_handing/metadata.textproto
-Removed port speed deviation from below IDs.
`RT-1.55, MTU-1.5, RT-14.2, RT-4.11, RT-5.11 `
> Removed 'explicit_port_speed' deviations from remaining files.

- feature/lldp/otg_tests/core_lldp_tlv_population_test/core_lldp_tlv_population_test.go
Added check - for some cases gnmi.Get() query when LLDP is disabled; should be handled carefully; such that value not found exception can be handled gracefully instead of test cases ended abruptly.
> changing the tests to handle gnmi.Get() response gracefully

- feature/gribi/otg_tests/mpls_in_udp/README.md
it is a good idea to make https://github.com/openconfig/featureprofiles/pull/3865 (# PF-1.4 - MPLSoGRE IPV4 encapsulation of IPV4/IPV6 payload) take the place of TE-18.1.2.
> Clean up PF-1.4 will take place of TE-18.1.2

- feature/security/gnsi/credentialz/tests/hiba_authentication/hiba_authentication_test.go
- feature/security/gnsi/credentialz/tests/ssh_password_login_disallowed/ssh_password_login_disallowed_test.go
Add ssh retry mechanism when rotating host parameters to allow time in case ssh server needs to restart on the dut.
> Credentialz: Add ssh retry mechanism when rotating host parameters

- feature/interface/holdtime/otg_tests/holdtime_test/README.md
- feature/interface/holdtime/otg_tests/holdtime_test/holddown_timers_test.go
Increasing the holdtime down tolerance to 700ms. This is to account for processing delays after issuing RF request to OTG.
> Rt 5.5 increase holdtime down tolerance

- feature/interface/aggregate/otg_tests/aggregate_all_not_viable_test/README.md
- feature/interface/aggregate/otg_tests/aggregate_all_not_viable_test/aggregate_all_not_forwarding_viable_test.go
- internal/fptest/portspeed.go
Ensure that the total bandwidth computation for the bundle interface does not include links where "forwarding viable" is set to false.
> Bandwidth computation for forwarding-unviable links

- feature/interface/lacp/tests/lacp_interval_test/lacp_interval_test.go
> Executed this new script on Juniper platform and figured a failure due to a typo
> fixing possible typo in lacp_interval_test.go

- feature/platform/tests/power_admin_down_up_test/metadata.textproto
Hi 
This pull is to remove the deviation  skip_controller_card_power_admin for FP1.1 for power_admin_down_up_test.
Thanks
> removing deviation skip_controller_card_power_admin

- feature/gribi/otg_tests/gribi_scaling/metadata.textproto
In Arista, we rely on the tags specified in the metadata.textproto to determine if the test needs to be run with transit prerequisite vendor specific configs.  This test was failing because it was missing the right tag in the proto file.
> Add "TRANSIT" tag to TE-14.1 test since it has transit VRF selection Transit tag

- feature/interface/otg_tests/telemetry_interface_packet_counters_test/README.md
- feature/interface/otg_tests/telemetry_interface_packet_counters_test/telemetry_interface_packet_counters_test.go
- feature/qos/otg_tests/qos_output_queue_counters_test/README.md
- feature/qos/otg_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go
gNMI-1.11: Telemetry: Interface Packet Counters
Start traffic and subscribe to packet counters every 30s. Collect 10 or more samples and verify if counters are being incremented for below paths. 
* /interfaces/interface[name='port']/state/counters/in-pkts
* /interfaces/interface[name='port']/state/counters/out-pkts
* /interfaces/interface[name='port']/subinterfaces/subinterface[index='index-id']/ipv4/state/counters/in-pkts
* /interfaces/interface[name='port']/subinterfaces/subinterface[index='index-id']/ipv6/state/counters/in-pkts
gNMI-1.11: Telemetry: Interface Packet Counters
Start traffic and subscribe to packet counters every 30s. Collect 10 or more samples and verify if counters are being incremented for below paths. 
* /qos/interfaces/interface[interface-id='id']/output/queues/queue[ …
> Counter subscription subtest

- feature/gnmi/otg_tests/aggregate_interface_counters_test/aggregate_interface_counters_test.go
The aggregate interface counters test package was named "telemetry_interface_packet_counters_test", which is duplicated with the test at https://github.com/openconfig/featureprofiles/blob/main/feature/gnmi/otg_tests/telemetry_interface_packet_counters_test/telemetry_interface_packet_counters_test.go.  This is a little confusing because this is a different test and is differently named in the metadata/directory name, just not the package name.
> Update the aggregate interface counters pkg name

- feature/platform/tests/breakout_configuration/breakout_base_test.go
- feature/platform/tests/breakout_configuration/breakout_test.go
- feature/platform/tests/breakout_configuration/metadata.textproto
Modified the test to be more vendor agnostic. Also the test runs on the assumption that 4 x 100g ports already configured for breakouts are only selected. Thus the index and schema value are also changed.
> Plt1.1 breakout test

- feature/bgp/otg_tests/bgp_remove_private_as/bgp_remove_private_as_test.go
Remove AddPath config from ATE since it's not used in the test
> RT-1.11 Remove add path config

- feature/bgp/routereflector/otg_tests/route_reflector_scale/route_reflector_scale_test.go
- internal/cfgplugins/bgp.go
Remove prepended 0 from IPv6 address, other usage of IPv6 does not prepend the 0.
Increase wait time for sending prefixes to 30 seconds.
> RT-1.8 Update waitTime and IPv6 address

- feature/gribi/otg_tests/fib_failed_due_to_hw_res_exhaust_test/README.md
- feature/gribi/otg_tests/gribi_scaling/README.md
```
* (M) feature/gribi/fib_failed_due_to_hw_res_exhaust_test/README.md
- Fix typo in README.
* (M) feature/gribi/gribi_scaling/README.md
- Resolve TODO covering adding traffic validation in this test as it is
covered in the implementation.
- Resolve TODO covering gRIBI route programming as it has been added.
```
It wasn't clear to me whether the TODO #3676 was requesting that the programmed entries are validated using `Get` or not. It seemed like this isn't necessarily required because traffic generation will also do this verification.
> 🧹: Fix typo & remove TODO for gRIBI tests.

- feature/p4rt/tests/p4rt_device_down_test/README.md
- testregistry.textproto
Verify that the P4RT server handles Read/Write RPCs for a device/node as follows:
- Accepts them when the device is available and
- Returns a `NOT_FOUND` error when it is unavailable or down
Point-1 P4RT Spec: https://p4.org/p4-spec/docs/p4runtime-spec-working-draft-html-version.html#_setforwardingpipelineconfig_rpc
> P4RT device down validation

- feature/interface/aggregate/otg_tests/aggregate_all_not_viable_test/aggregate_all_not_forwarding_viable_test.go
While calculating the balance, subtracted the traffic received for profile pfx1ToPfx4 in lag2 and calculated the weight using rest of the traffic in lag2
> Modification to "func trafficRXWeights" to calculate the rxPackets by subtracting the traffic received for lag profile

- feature/platform/transceiver/laser_bias_current/tests/zr_laser_bias_current_test/zr_laser_bias_current_test.go
- feature/platform/transceiver/laser_bias_current/tests/zrp_laser_bias_current_test/zrp_laser_bias_current_test.go
change gnmi update request to use the name of transceiver leaf resolved from interface container by port name, instead of the port name itself.
> TRANSCEIVER-9: transceiver component key fix

- feature/platform/transceiver/logical_channels/tests/zr_logical_channels_test/zr_logical_channels_test.go
- feature/platform/transceiver/logical_channels/tests/zrp_logical_channels_test/zrp_logical_channels_test.go
Cisco devices now return the correct format, meaning this workaround would cause a failure
Old e.g: `OpticalChannel0_0_0_18`
instead of : `Ex: OpticalChannel0/0/0/18`
> TRANSCEIVER-11: remove stale workaround for optical channel format

- feature/interface/ip/ipv6_link_local/otg_tests/ipv6_link_local_test/ipv6_link_local_test.go
- Added Sleep of 15sec after start traffic to have the packets flow in DUT.
> RT-5.8: IPv6 Link Local: Added Sleep of 15sec after start traffic to have the got packets flow in DUT.

- feature/bgp/ate_tests/bgp_long_lived_graceful_restart/bgp_long_lived_graceful_restart_test.go
Updated code to proceed with BGP config based on interface status.
> RT-1.14: Added code to proceed with BGP config based on interface status.

- feature/isis/otg_tests/static_route_isis_redistribution/static_route_isis_redistribution_test.go
- Replaced GetAll with WatchAll for Metric propagation sub-cases in both v4 & v6.
- Fixed watchAll condition in `func verifyPrefix` for 2.12.5 & 2.12.7 sub-cases.
- Minor Log message fixes.
> RT-2.12: Replaced GetAll with WatchAll & fixed watchAll conditions

- internal/gnoi/gnoi.go
Fixes procname for OCAGENT for latest release onward
---
> Fix Vendor OCAGENT procname in gnoi.go

- feature/isis/otg_tests/static_route_isis_redistribution/static_route_isis_redistribution_test.go
The config was being updated which was causing more config to be added without cleaning up the previous config, so replacing it would resolve the issue.
> Fix RT-2.12 to use replace instead of update

- go.mod
- go.sum
- internal/cntrsrv/cntrsrv_test.go
- internal/security/gen/generate.go
`go mod tidy` is updating the gNMI version when I'm looking to update the Ondatra version. This requires a change in `internal/security/gen/generate.go`, separating the patch to update gNMI to clarify intent.
> Update to GNMI v0.14.1

- feature/gribi/otg_tests/route_leakage_between_nondefault_vrfs/README.md
- testregistry.textproto
Adding new testcase for the readme for route leakage between two non-default VRF's
> add new testcase TE-6.3 readme for route leakage

- feature/platform/transceiver/chromatic_dispersion/tests/zr_cd_test/zr_cd_test.go
- feature/platform/transceiver/fec_uncorrectable_frames/tests/zr_fec_uncorrectable_frames_test/zr_fec_uncorrectable_frames_test.go
- feature/platform/transceiver/firmware_version/tests/zr_firmware_version_test/zr_firmware_version_test.go
- feature/platform/transceiver/input_output_power/tests/zr_input_output_power_test/zr_input_output_power_test.go
- feature/platform/transceiver/inventory/tests/zr_inventory_test/zr_inventory_test.go
- feature/platform/transceiver/logical_channels/tests/zr_logical_channels_test/zr_logical_channels_test.go
- feature/platform/transceiver/low_power_mode/tests/zr_low_power_mode_test/zr_low_power_mode_test.go
- feature/platform/transceiver/performance_metrics/tests/zr_pm_test/zr_pm_test.go
- feature/platform/transceiver/supply_voltage/tests/zr_supply_voltage_test/zr_supply_voltage_test.go
- feature/platform/transceiver/temperature/tests/zr_temperature_test/zr_temperature_test.go
- feature/platform/transceiver/tunable_parameters/tests/zr_tunable_parameters_test/zr_tunable_parameters_test.go
- internal/cfgplugins/interface.go
Update vendor specific operational mode values for ZR optic channels. 
Update: Logic is updated to use vendor specific values when '0' is passed as the OperationalMode variable.
> Vendor specific ZR optical channel operational mode

- feature/isis/otg_tests/weighted_ecmp_test/README.md
- feature/isis/otg_tests/weighted_ecmp_test/metadata.textproto
- feature/isis/otg_tests/weighted_ecmp_test/weighted_ecmp_test.go
(M) feature/isis/otg_tests/weighted_ecmp_test/weighted_ecmp_test.go
- Removed unrequired ExplicitInterfaceInDefaultVRF in ISIS code block and added that deviation to handle LAG/Interface
- Added MaxECMP paths to be 3 (as many as the number of Lags)
- Added necessary deviations for interface/LAGs association in DEFAULT VRF
(M) feature/isis/otg_tests/weighted_ecmp_test/README.md
- Added MaxECMP in the ConfigPaths
(M) feature/isis/otg_tests/weighted_ecmp_test/metadata.textproto
- Additions of Vendor specific deviations
---
"This code is a Contribution to the OpenConfig Feature Profiles project ("Work") made under the Google Software Grant and Corporate Contributor License Agreement ("CLA") and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia's …
> RT-2.13 Adding MaxECMP Paths and Deviations

- feature/isis/otg_tests/static_route_isis_redistribution/metadata.textproto
- feature/isis/otg_tests/static_route_isis_redistribution/static_route_isis_redistribution_test.go
1. Script is replacing the policy without deleting the policy reference  in table connections. Updated script to handle this.
2. Removed deviation skip_setting_disable_metric_propagation
> Modification to RT2.12-static_route_isis_redistribution_test.go

- feature/gribi/otg_tests/vrf_policy_driven_te/vrf_policy_driven_te_test.go
This PR replaces the stale PR: https://github.com/openconfig/featureprofiles/pull/2976
> Correct typo in TE-17.1

- feature/bgp/otg_tests/bgp_tcp_mss_path_mtu/bgp_tcp_mss_path_mtu_test.go
To set the BGP TCP Segment size to desired value, no separate Api is needed in the BGP, rather setting the MTU in the Ixia port achieves the desired purpose. Hence modified the test and corresponding function signatures and calls to set the MTU values correctly on the IXIA ports.
> Modified the test and corresponding function calls to set the MTU values correctly on the NTE ports

- feature/bgp/addpath/otg_tests/route_propagation_test/route_propagation_test.go
this is to cover usage of /network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/timers/config/minimum-advertisement-interval
> add update interval

- feature/policy_forwarding/policy_vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/README.md
- feature/policy_forwarding/policy_vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/metadata.textproto
- feature/policy_forwarding/policy_vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
Adding a subtest to cover DUT forwarding behaviour when more than one vrf selection policies are configured.
> Rt 3.2-Test multiple vrf selection policies

- feature/policy_forwarding/otg_tests/mpls_gre_ipv4_decap_test/mpls_gre_ipv4_decap_test.go
- feature/policy_forwarding/otg_tests/mpls_gre_ipv4_encap_test/mpls_gre_ipv4_encap_test.go
- internal/deviations/deviations.go
- internal/otg_helpers/packetvalidationhelpers/packetvalidationhelpers.go
Some checks are failing. We fix them. :)
* Removed the unused `top` parameter from the `CaptureAndValidatePackets` function in `packetvalidationhelpers.go` to simplify its signature. All calls to this function across various test cases were updated accordingly. ([[1]](diffhunk://#diff-e59a1678d2eded1caaed6126b3061b81e11a259df05d4115e8314287808cce97L159-R159), [[2]](diffhunk://#diff-2e1f4bf0ec85a1bcf0e4be5fc860d688f8abf18f09bb90de2798697f99e3b646L337-R337), [[3]](diffhunk://#diff-c84fa280fa822959d00c1588087dc984d972637a0f3a6661ae83f32c3eec1935L436-R436), [[4]](diffhunk://#diff-c84fa280fa822959d00c1588087dc984d972637a0f3a6661ae83f32c3eec1935L484-R484))
* Fixed a typo in the comment for the `MplsExpIngressClassifierOcUnsupported` function in `deviations.go` to improve clarity. The updated …
> Fix failing static checks

- feature/isis/otg_tests/base_adjacencies_test/base_adjacencies_test.go
- feature/isis/otg_tests/base_adjacencies_test/metadata.textproto
Removed deviation and leaf validation "checks = append(checks, check.Equal(isisRoot.Level(2).Enabled().State(), true))" since its deprecated https://github.com/openconfig/public/blob/master/release/models/isis/openconfig-isis.yang#L386
> deviated removed for RT-2.1

- feature/afts/otg_tests/afts_base/afts_base_test.go
- feature/afts/otg_tests/afts_base/metadata.textproto
Update Arista deviations for AFT-1.1 to enable interfaces and correctly configure ISIS. Also add a check for ISIS when configuring and establishing an adjacency.
> AFT-1.1: Update Arista deviations

- feature/afts/otg_tests/afts_base/afts_base_test.go
- feature/afts/otg_tests/afts_base/metadata.textproto
- internal/telemetry/aftcache/aft_cache.go
Changes include:
1. Instead of having 1 stream for entire test, creating new stream and cancelling the context results in faster aft convergence. Made the change
2. Changing periodic hook interval and deadline
3. Adding few unused paths
4. Removing unnecessary warning
> Perfomance improvements in AFT FNT

- feature/gribi/otg_tests/vrf_policy_driven_te/vrf_policy_driven_te_test.go
* Fix iteration and validation of captured packets
* DSCP & ECN checks for inner packet after decapsulation
Requirements: DSCP and ECN bits are copied after decapsulation
https://screenshot.googleplex.com/B6B8jbscgiK7UDz
After decapsulation, the current status after running on KNE. 
- cisco copies to encapsulated packet the ECN bits, but not DSCP bits
- arista copies the DSCP bits, but not the ECN bits
> Verify DSCP & ECN bits are copied after decap in vrf policy te test

- feature/afts/otg_tests/afts_base/afts_base_test.go
- feature/afts/otg_tests/afts_base/metadata.textproto
- internal/cfgplugins/bgp.go
Add bgp_neighbor_prefix_limit_required deviation for Arista to configure prefix-limit per
neighbor via augmented model.
> AFT-1.1: Configure prefix-limit per neighbor 

- feature/bgp/policybase/otg_tests/Import_Export_Policy/bgp_import_export_policy_test.go
- feature/bgp/policybase/otg_tests/Import_Export_Policy/metadata.textproto
- internal/cfgplugins/bgp_policy.go
Test log: https://partnerissuetracker.corp.google.com/issues/415458482 (contains logs for Arista vendor)
> test rt1.64

- feature/gnsi/acctz/tests/record_payload_truncation/record_payload_truncation_test.go
Fixing record_payload_truncation_test by adding the cisco specific cli for truncation to work. Below is the CLI
aaa accounting queue-size 10
aaa accounting history-memory 10
> added cli commands

- internal/components/components.go
This logging doesn't really belong in a util and often ends up obfuscating more important logs
> remove excessive logging from FindComponent utils

- feature/sflow/otg_tests/sflow_base_test/sflow_base_test.go
As part of code refactoring, Pull/4590 changed the source address configured for the sFlow collector from the device's lo0 address to the ip address of the interface where sampling is enabled. This was leading to discrepancy between what was configured on the device and what the verification parts (OTG captures) were based on. This PR addresses the discrepancy.
> Address failure caused due to discrepancy between config and verification data

- feature/mpls/otg_tests/mpls_tc/metadata.textproto
- feature/mpls/otg_tests/mpls_tc/mpls_traffic_class_marking_test.go
Readme location here: https://github.com/openconfig/featureprofiles/tree/main/feature/mpls/otg_tests/mpls_tc
> Otg mpls 1.2

- feature/policy_forwarding/decapsulation/otg_tests/ipv4_guev1_decap_and_hashing_test/metadata.textproto
Update testbed for `ipv4_guev1_decap_and_hashing_test` as the test requires more than 4 ports.
> Update testbed for ipv4_guev1_decap_and_hashing_test
